ADAPT-2114 Hero component
SU-SWS/saa_alumni pull request #11
Opened 2021-04-13 08:25 UTC by yvonnetangsu

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-04-20 22:28 UTC, sherakama commented on src/components/composite/hero.js
> +            imageClasses='su-w-full su-h-full su-object-cover'
From a DX perspective, having two props for classes has me confused. I haven't looked at the FullWidthImage yet so I have my guesses but I would have suspected this component to be without a wrapper for the image element.

2021-04-20 22:29 UTC, sherakama commented on src/components/composite/hero.js
> +              <p className='su-max-w-prose su-font-serif su-leading-display su-text-m1 md:su-text-m2 su-text-shadow su-mx-auto su-mb-05em'>{props.blok.serifSuper}</p>
Are any of these fields optional? If so, they should have checks in this template.

2021-04-20 22:32 UTC, sherakama commented on src/components/composite/hero.js
> +                <SrOnlyText srText='Jump to main content' />
After reading this, I think I would rather see the format `<SrOnlyText>Jump to main content</SrOnlyText>` but no need to refactor.

2021-04-20 22:52 UTC, sherakama requested changes
Looks good. Overall, pretty minor feedback.

One visual thing I did notice was that the scroll down arrow was below the fold for me. Not sure if that was intentional or not.

2021-04-20 22:52 UTC, sherakama commented on src/components/composite/hero.js
> +                <SrOnlyText srText='Jump to main content' />
Is this ALWAYS going to jump to main content? Or should the text be configurable?

2021-04-20 22:52 UTC, sherakama commented on src/components/cta/ctaButton.js
> +          <span className='su-sr-only'>{` ${props.blok.srText}`}</span>
Why not use the `SrOnlyText` component here?

2021-04-20 22:52 UTC, sherakama commented on src/tailwind/plugins/components/gradient-border/gradient-border.js
> +      },
Any chance you are going to have more than one gradient border? Might want to think of a different name or to create a combination of all the classes using the predefined color options.

2021-04-20 22:52 UTC, sherakama commented on src/tailwind/plugins/components/shadow/text-shadow.js
> +module.exports = function () {
This one would be a good candidate for the core Decanter product. Consider moving it into v7.

2021-04-20 22:52 UTC, sherakama commented on src/utilities/dataSource.js
> +export const ctaGroupDisplay = {
Where did we leave off with pulling these with a static query?

2021-04-20 22:52 UTC, sherakama commented on src/components/media/fullWidthImage.js
> +  const Element = element ?? 'figure';
Would we ever want the option for no wrapping element?

2021-04-20 22:52 UTC, sherakama commented on src/components/media/fullWidthImage.js
> +      />
What about a props for the image as well for things like title, data, or aria attributess?

2021-04-21 05:41 UTC, yvonnetangsu commented on src/components/composite/hero.js
> +            imageClasses='su-w-full su-h-full su-object-cover'
Yeah I know what you mean, though having a figure wrapper allows for object-fit (for image focus) and aspect ratio stuff - which is used a lot in components. Perhaps I could rename it 🤔

2021-04-21 05:42 UTC, yvonnetangsu commented on src/components/composite/hero.js
> +              <p className='su-max-w-prose su-font-serif su-leading-display su-text-m1 md:su-text-m2 su-text-shadow su-mx-auto su-mb-05em'>{props.blok.serifSuper}</p>
Good catch - how did I forget this one geez

2021-04-21 05:45 UTC, yvonnetangsu commented on src/components/composite/hero.js
> +                <SrOnlyText srText='Jump to main content' />
I think it is always going to jump to main content since they're only going to use it on the homepage. Maybe leave it like this for now and if there's a need later, I'll make it configurable.

2021-04-21 05:45 UTC, yvonnetangsu commented on src/components/cta/ctaButton.js
> +          <span className='su-sr-only'>{` ${props.blok.srText}`}</span>
Yeah good point

2021-04-21 05:48 UTC, yvonnetangsu commented on src/tailwind/plugins/components/gradient-border/gradient-border.js
> +      },
I believe there's only going to be one gradient border for this SAA theme. I agree that if there will be different color options, then the classname should be different.

2021-04-21 05:49 UTC, yvonnetangsu commented on src/tailwind/plugins/components/shadow/text-shadow.js
> +module.exports = function () {
Good idea. Maybe we can get Jacob to help out 😄

2021-04-21 05:51 UTC, yvonnetangsu commented on src/utilities/dataSource.js
> +export const ctaGroupDisplay = {
For now, I like having them all in the one dataSource.js file since I can easily tweak them there (and easier to see), and works well with the JIT mode. I don't have any classnames on the storyblok side.

2021-04-21 05:54 UTC, yvonnetangsu commented on src/components/media/fullWidthImage.js
> +  const Element = element ?? 'figure';
I could split it into 2 components - the FullWidthImage (just the img), and the optional Figure component that acts as wrapper 🤔 . Maybe next sprint 😛

2021-04-21 05:55 UTC, yvonnetangsu commented on src/components/media/fullWidthImage.js
> +      />
Good point - I'll tackle this in the above mentioned splitting FullWidthImage ticket (will add).

2021-04-21 06:43 UTC, yvonnetangsu commented
> Looks good. Overall, pretty minor feedback.
> 
> One visual thing I did notice was that the scroll down arrow was below the fold for me. Not sure if that was intentional or not.

Yeah, it's a pretty large hero banner. Kerri did say that she doesn't intend for them to add every field to the banner, so it might become shorter. I suspect we will finetune spacing and things after adding in the masthead though 😃

2021-04-21 07:09 UTC, yvonnetangsu commented on src/components/cta/ctaButton.js
> +          <span className='su-sr-only'>{` ${props.blok.srText}`}</span>
Done, also used it in ctaLink

2021-04-21 07:09 UTC, yvonnetangsu commented on src/components/composite/hero.js
> +              <p className='su-max-w-prose su-font-serif su-leading-display su-text-m1 md:su-text-m2 su-text-shadow su-mx-auto su-mb-05em'>{props.blok.serifSuper}</p>
All done

2021-04-21 07:17 UTC, yvonnetangsu commented
@sherakama Ready for another look. I'll work on the image component stuff next sprint. Thanks! Heads up I might be in and out today. Starting to feel weird chills.

2021-04-21 20:00 UTC, yvonnetangsu commented
@sherakama , I did some experiments and found that basically, the JIT modes doesn't like our custom link utilities when they have the `.hover:` typed prefixes. Those TW variant prefixes confuse the JIT mode and thus, in the global footer, when we add a class like `.hover:su-link-no-underline` to the `nav` element, it does not respect the custom utility that we add.

We want this:
```
.hover:su-link-underline {
  a:hover {
  text-decoration: underline;
  }
}
```

Instead, this is what it will generate:
```
.hover:su-link-underline {
  :hover a {
  text-decoration: underline;
  }
}
```

I tried a number of things, including moving them to "components" instead of "utilities", disable variants, manually write out everything and none of those methods really worked. So now I'm going with my last resort, which is to create a SAA `base.js` file, which adds to the Decanter `base.js` file. It includes overrides to some of the styles that we can't change (eg, we don't have access to the link classes in the global footer `nav` so can't use dedupe). Currently, the global footer is working using this method. Let me know what you think. I know it's not great, but at least the global footer is working 😬

2021-04-21 20:14 UTC, sherakama commented on src/utilities/dataSource.js
> +export const ctaGroupDisplay = {
> I don't have any classnames on the storyblok side

Ah right. PurgeCSS is going to be the bain of my existence for some time I foresee. We've got to give this a hard think as it isn't a great DX experience to have EVERY CSS STRING IN THE SOURCE CODE and can cause brittleness between our CMS and code.

2021-04-21 20:27 UTC, yvonnetangsu commented on src/utilities/dataSource.js
> +export const ctaGroupDisplay = {
Argghh....yeah. It's definitely a bit of a pain with PurgeCSS and JIT.

2021-04-21 20:29 UTC, yvonnetangsu commented on src/utilities/dataSource.js
> +export const ctaGroupDisplay = {
I did see another option that we haven't explored. It looks like for Storyblok option fields, instead of datasource, you could pick "eternal json" - maybe we can give that a try.

2021-04-21 20:31 UTC, sherakama commented on src/utilities/dataSource.js
> +export const ctaGroupDisplay = {
Oh, that sounds like an interesting option. I'll create a ticket to explore that later.

2021-04-21 20:33 UTC, sherakama commented on src/utilities/dataSource.js
> +export const ctaGroupDisplay = {
Ah, but that gets us roughly to the same place as the datasource as I want to have options configured on the storyblok side and not the code side. I suppose this might be a limitation we have to live with.

2021-04-21 20:36 UTC, yvonnetangsu commented on src/utilities/dataSource.js
> +export const ctaGroupDisplay = {
Yeah - it's still roughly the same. I find the datasource stuff works pretty well most of the time since they tend to include classes that we'll need to write out explicitly anyway. Maybe we'll just need to generate our own safelist.txt file like TW suggested for the ones that we don't want to write out, like the grid column classes. Not ideal, but looks like TW is aware of the limitation that JIT mode doesn't allow safelisting classes, so they might add a feature later on to enable that.

2021-04-22 20:27 UTC, sherakama commented on src/components/composite/hero.js
> +            imageClasses='su-w-full su-h-full su-object-cover'
Break it out into two components? I'll let you deliberate on that and revise/refactor later.

2021-04-22 20:28 UTC, sherakama commented on src/components/composite/hero.js
> +                <SrOnlyText srText='Jump to main content' />
SG2M. One of the practices of XP (Extreme Programming) is to never write code for the future. That pairs well with Agile.

2021-04-22 20:30 UTC, sherakama approved these changes
GTG

2021-04-22 20:31 UTC, merged