Adapt 3124
SU-SWS/saa_alumni pull request #116
Opened 2021-08-10 17:59 UTC by Lyafel

# Summary
Various styling fixes for search

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to /search
3. Verify changes to the search page and search overlay mentioned in the ticket

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-08-10 18:16 UTC, yvonnetangsu commented on src/components/search/searchModal.js
> +        <div className="su-mb-108">
```suggestion
        <div className="su-rs-mb-4">
```
Please use responsive-spacing su-rs-______ classes for these larger spacings

2021-08-10 18:19 UTC, yvonnetangsu commented on src/components/search/searchModal.js
> +          <div className="su-mt-78">
Please use responsive-spacing here also

2021-08-13 17:00 UTC, Lyafel commented on src/components/search/searchModal.js
> +          <div className="su-mt-78">
Removed. Looks like it's configurable in storyblok but there's also a different ticket for this

2021-08-17 05:42 UTC, sherakama commented
@yvonnetangsu can you resolve the merge conflict here. I am unsure which styles are correct in this PR.

2021-08-17 18:56 UTC, yvonnetangsu requested changes
@Lyafel For this ticket, looks like there are a couple of items still:

- Search red button needs to be circular (looks like it’s taller vertically than horizontally currently)

- Magnifying glass submit button should be `su-digital-red-xlight` (#F83535) on-hover/focus

we have some spacing/font size clean up to do, but that could be done in the other ticket.

2021-08-17 19:37 UTC, yvonnetangsu commented on src/components/search/searchFieldModal.js
> +  const submitBtnClasses = `su-min-w-[70px] su-w-70 su-h-70 su-rounded-full su-transition-colors su-bg-digital-red-xlight hocus:su-bg-black
We'd like the normal state of the button to be digital-red, and only digital-red-xlight on hover/focus.

2021-08-17 19:39 UTC, yvonnetangsu requested changes
Please revise button color.

2021-08-17 20:08 UTC, Lyafel commented
@yvonnetangsu Sorry I missed that.. Changed

2021-08-17 20:17 UTC, yvonnetangsu approved these changes
GTG

2021-08-17 20:20 UTC, yvonnetangsu commented on src/components/page-types/searchPage.js
> +
@sherakama Does this look good to you?

2021-08-19 20:17 UTC, yvonnetangsu commented on src/components/page-types/searchPage.js
> +
@sherakama I'm going to merge this in so I can continue to work on the UI tweaks for search. I tested this and does seem to me that it's working as expected now. Please review retro when you have time 😄

2021-08-19 20:17 UTC, merged