Adapt 3117
SU-SWS/saa_alumni pull request #118
Opened 2021-08-10 20:30 UTC by Lyafel

# Summary
Added scroll to the search modal

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-08-10 21:34 UTC, yvonnetangsu commented on src/components/layout/modal.js
> +      su-fixed su-w-full su-h-full su-top-0 su-left-0 su-items-center su-bg-saa-black su-justify-center su-z-50
@Lyafel  I see that you added the background color `su-bg-saa-black`, which makes it 100% opaque. I think the background color was working ok previously, why this change?

2021-08-10 21:37 UTC, yvonnetangsu commented on src/components/layout/modal.js
> +      <div className="su-absolute su-w-full su-h-full su-opacity-95 su-pt-70 su-overflow-auto">
Please move the opacity class to follow the background color, and I think you could use the TW bg-opacity 😃 
https://tailwindcss.com/docs/background-opacity

2021-08-10 21:37 UTC, yvonnetangsu commented on src/components/search/searchModal.js
> +          <div className="su-mt-108 su-mb-70">
Please use responsive spacing classes, the su-rs-_____ custom Tailwind classes we created

2021-08-10 21:38 UTC, yvonnetangsu requested changes
Left a few comments about the modal's opacity and responsive spacing, please revised. Thanks 🙏🏼

2021-08-10 21:55 UTC, yvonnetangsu commented
@mattanglin Tagging you to keep you in the loop :)

2021-08-11 16:05 UTC, Lyafel commented on src/components/search/searchModal.js
> +          <div className="su-mt-108 su-mb-70">
Removed them, looks like there's a field for spacings in storyblok

2021-08-12 16:26 UTC, yvonnetangsu commented on src/components/layout/modal.js
> +      <div className="su-absolute su-w-full su-h-full su-opacity-95 su-bg-saa-black su-pt-70 su-overflow-auto">
```suggestion
      <div className="su-absolute su-w-full su-h-full su-bg-opacity-95 su-bg-saa-black su-pt-70 su-overflow-auto">
```
I prefer that we use `su-bg-opacity-95` if we only need to change the opacity of the background colors. `su-opacity-95` changes opacity on the content also. It's not noticeable because it's 95%, but let's try to follow good practice :)
https://tailwindcss.com/docs/background-opacity

2021-08-12 16:29 UTC, yvonnetangsu commented
GTG after the bg-opacity change - thanks!

2021-08-12 17:58 UTC, Lyafel commented
Put it back where it was without noticing, good catch.

2021-08-12 18:13 UTC, yvonnetangsu approved these changes
Thanks for the change, @Lyafel - GTG!

2021-08-12 18:14 UTC, merged