ADAPT-3142: Search filters checkbox state styles
SU-SWS/saa_alumni pull request #132
Opened 2021-08-13 19:28 UTC by Lyafel

# Summary
- Checkboxes styling

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to /search
3. Verify filter checkbox styles

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-08-13 19:32 UTC, Lyafel commented
@yvonnetangsu ran into an issue, the hover on the label acts like hover on the input (even if I move the input outside of it) and I can't hover the text without hovering the input. It makes sense logically but doesn'tmatch figma

2021-08-16 16:40 UTC, yvonnetangsu commented
> @yvonnetangsu ran into an issue, the hover on the label acts like hover on the input (even if I move the input outside of it) and I can't hover the text without hovering the input. It makes sense logically but doesn'tmatch figma

@Lyafel I think that's ok since that's the nature of form labels.

If you could please add these two things, then it's GTG:

1. Label text needs underline on hover/focus (we always want the hover states to match the focus states, and focus state can have additional browser default outline on top of our hover/focus styles)
2. See if you could use the TW prefix `group-focus-within` to style the label text (`span`) for it to turn red with underline when the input is focused. You'll need to add a su-group class to the label element.

2021-08-16 16:42 UTC, yvonnetangsu commented on src/components/search/searchFacet.js
> +          className={`su-label su-flex su-items-center su-cursor-pointer su-text-19 hover:su-text-digital-red-xlight ${
You can use the `hocus:` prefix when the hover/focus states are the same

2021-08-16 16:43 UTC, yvonnetangsu commented on src/components/search/searchFacet.js
> +            className="su-checkbox su-mr-12 su-max-w-[1.7rem] su-cursor-pointer su-custom-checkbox su-max-h-[1.7rem] su-appearance-none su-border su-rounded-[0.3rem]"
```suggestion
            className="su-checkbox su-mr-12 su-max-w-[1.7rem] su-cursor-pointer su-custom-checkbox su-max-h-[1.7rem] su-appearance-none su-border su-rounded"
```
I believe you don't need the stuff in the square bracket because 0.3rem is the default, so just su-rounded should be fine, but please double check.

2021-08-16 16:46 UTC, yvonnetangsu requested changes
This is pretty close. Comments left - please revised. Thanks!

2021-08-16 20:50 UTC, yvonnetangsu commented
@Lyafel Actually please hold off on this. I'm going to open a PR to use the TW form plugin for the checkbox styles

2021-08-17 05:05 UTC, sherakama commented
https://github.com/SU-SWS/saa_alumni/pull/134 was merged so this can be closed now?

2021-08-17 05:21 UTC, yvonnetangsu commented
> #134 was merged so this can be closed now?

@Lyafel worked on some additional hover/focus state on the checkboxes and labels, I was thinking that she could merge the latest changes into this branch then make any adjustments needed.

2021-08-17 05:55 UTC, sherakama commented
@yvonnetangsu can you help with the merge conflict then, since we moved some cheese mid-flight on @Lyafel

2021-08-17 16:12 UTC, yvonnetangsu commented
> @yvonnetangsu can you help with the merge conflict then, since we moved some cheese mid-flight on @Lyafel

Of course - will do 😃

2021-08-17 17:29 UTC, yvonnetangsu commented
@sherakama @Lyafel  I tried out a new TW feature called "peer", which they use the checkbox as an example of a good use case:
https://blog.tailwindcss.com/tailwindcss-2-2#sibling-selector-variants

Was able to only use TW classes to get the styles, and tested on Safari/Firefox (doesn't like focus visible but looks like we don't need it for the checkboxes). Ready for review.

![Screen Shot 2021-08-17 at 10 28 44 AM](https://user-images.githubusercontent.com/42749717/129773082-ca7898de-44f7-4190-968d-322af3cc5e57.png)

2021-08-17 23:19 UTC, yvonnetangsu commented on src/components/search/searchFacet.js
> +              optionClasses || ""
I added the || since I saw an `undefined` at the end of className here - not sure if `optionClasses` are still needed? @nplowman

2021-08-20 19:36 UTC, Lyafel commented on src/components/search/searchFacet.js
> +              optionClasses || ""
I think it should be there :)

2021-08-20 19:45 UTC, yvonnetangsu commented on src/components/search/searchFacet.js
> +              optionClasses || ""
Thanks for confirming, @Lyafel . I'm out today. Will review things next Monday.

2021-08-21 00:03 UTC, yvonnetangsu approved these changes
GTG

2021-08-21 00:03 UTC, merged