ADAPT-3255 | trip page layout
SU-SWS/saa_alumni pull request #159
Opened 2021-09-08 22:22 UTC by mattanglin

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- Fixed bug with gatsby creating pages for global components
- Fixed bug with invalid classname property
- Basic trip page layout component.

## Notes
Just left this basic while I exploring existing components in sb and react. Assuming the additional tickets will fill it out.

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

2021-09-08 23:02 UTC, yvonnetangsu commented on src/components/search/openSearchModalButton.js
> +      })}
I've found that we don't actually need to write out dcnb here, since the `Button` component is pulled in from Decanter-React, and the Button `className` prop already has dcnb built in so passing the className as an object without the dcnb works ok.

2021-09-08 23:04 UTC, yvonnetangsu commented on src/components/page-types/TripPage.jsx
> +const TripPage = (props) => {
Any reason to use .jsx instead of .js for this flle?

2021-09-08 23:04 UTC, yvonnetangsu commented on gatsby-node.js
> +    const omittedComponentsArray = JSON.stringify(contentTypesToOmit);
Thanks for doing this!

2021-09-08 23:08 UTC, yvonnetangsu commented on package.json
> +    "cnbuilder": "^2.7.1",
We've been able to use dcnb since it's already a dependency of Decanter React, but probably adding it explicitly is a good idea.

2021-09-08 23:15 UTC, yvonnetangsu commented on src/components/page-types/TripPage.jsx
> +    </SbEditable>
Looks good to me! 👍🏼

2021-09-08 23:19 UTC, yvonnetangsu commented on src/components/components.js
> +  trip: TripPage,
We've been make these the same except for the first letter capitalized (ie, using the current convention this would be `trip: Trip`). Any reason to deviate from that? For the Story content type, we make the Story component (story.js) into a switcher between the card view or page view. Are we using a different convention for the Trip content type?

Merely a question 😄  Open to ideas and suggestions for improvements.

2021-09-08 23:19 UTC, yvonnetangsu commented
Thanks for the global components change! Left a few questions for you, @mattanglin 😄

2021-09-08 23:22 UTC, yvonnetangsu commented on gatsby-node.js
> +    const omittedComponentsArray = JSON.stringify(contentTypesToOmit);
We probably want this in production `main` also.

2021-09-08 23:58 UTC, sherakama commented on gatsby-node.js
> +            allStoryblokEntry (filter: { field_component: { nin: ${omittedComponentsArray} } }) {
This is a nice improvement. Thanks.

2021-09-08 23:59 UTC, sherakama commented on package.json
> +    "cnbuilder": "^2.7.1",
It doesn't seem to hurt but I usually leave out calling sub-dependencies in parent packages unless I need a specific version for something. I find it keeps the long-term maintenance down.

2021-09-09 00:03 UTC, yvonnetangsu commented on package.json
> +    "cnbuilder": "^2.7.1",
Good to know, @sherakama !

2021-09-09 16:39 UTC, yvonnetangsu commented on src/components/search/openSearchModalButton.js
> +      })}
Just did some testing - looks like this change would cause the dedupe function to not work. On live, it seems to work as intended. This is from this PR's Netlify preview, and it looks like the `hocus:su-bg-transparent` class is still there. 
![Screen Shot 2021-09-09 at 9 36 33 AM](https://user-images.githubusercontent.com/42749717/132726774-ccd6ba93-72df-4dd5-b018-73ef4eea1368.png)

2021-09-09 18:21 UTC, mattanglin commented on package.json
> +    "cnbuilder": "^2.7.1",
Using modules that aren't explicitly defined in your package.json and relying on them from your submodules can be a dangerous game...

2021-09-09 18:23 UTC, yvonnetangsu commented on package.json
> +    "cnbuilder": "^2.7.1",
That's a good point too, @mattanglin 😄  I like how we're having a discussion about this. More devs = goood

2021-09-09 18:24 UTC, mattanglin commented on src/components/page-types/TripPage.jsx
> +const TripPage = (props) => {
`.jsx` and `.tsx` are standard extensions for files containing React JSX markup. I prefer using the `x` extension variant to distinguish components from utility/service code.

2021-09-09 18:27 UTC, yvonnetangsu commented on src/components/page-types/TripPage.jsx
> +const TripPage = (props) => {
That sounds like a good idea to me. In that case, let's make that a standard for the whole repo and perhaps we can update all the file extensions in one go (could be another ticket).

2021-09-09 18:38 UTC, mattanglin commented on src/components/search/openSearchModalButton.js
> +      })}
This was throwing an error in the console as `className` is a reserved prop that's expected to be a string.
![image](https://user-images.githubusercontent.com/1952337/132743359-be2dec0a-65f4-4c5b-a246-6475214286bd.png)


I can now see that Button [accepts className as an object](https://github.com/SU-SWS/decanter-react/blob/main/src/Button/Button.js#L186-L189) and it's getting [passed to dcnb](https://github.com/SU-SWS/decanter-react/blob/main/src/Button/Button.js#L109-L115) in decanter-react.
_IMO,_ the `className` prop shouldn't altered from it's standard.

2021-09-09 19:01 UTC, mattanglin commented on src/components/components.js
> +  trip: TripPage,
I named the Storyblok component `trip` as that seemed semantically appropriate in the context of Storyblok (and for a content author). I named the React component `TripPage` as that seemed most appropriate in the context of the codebase (I had already ran into some confusion trying to discern `event`/`perk` cards and pages). Trip is an entity that has multiple views (page/card/filtering), but it seemed redundant to create a `tripPage` in Storyblok since every trip generates a page 🤷🏼.

Not sure I completely understand the logic behind having the parent Story switcher component and when, if ever, the [first layout conditional](https://github.com/SU-SWS/saa_alumni/blob/main/src/components/content-types/story/story.js#L6-L8) is hit.

2021-09-09 19:12 UTC, yvonnetangsu commented on src/components/components.js
> +  trip: TripPage,
We have a Story Card component, which allow the users to select a story that's added to the site, and display it as a card (similar to the masthead picker). That's where the layout="card" is set:
https://github.com/SU-SWS/saa_alumni/blob/main/src/components/cards/storyCard.js

If the layout prop isn't set, it defaults to use the story page layout.

2021-09-09 19:16 UTC, yvonnetangsu commented on src/components/search/openSearchModalButton.js
> +      })}
Yeah...about the className. @sherakama and I went back and forth on this when we first started working on Decanter React. We want to make it intuitive for developers to pass down extra classnames as props, in case they want to customized the components they import (which happens often) into their projects. Using "className" probably isn't ideal, but it is a bit more intuitive.
@sherakama tagging you in case you have thoughts on this.

2021-09-09 19:17 UTC, yvonnetangsu commented on src/components/components.js
> +  trip: TripPage,
Examples of the Story Cards - if you click on them, it brings you to the page layout
https://alumni-preview.stanford.edu/test/yvonne/test-story-cards/

2021-09-09 20:18 UTC, mattanglin commented on src/components/components.js
> +  trip: TripPage,
Right. I guess I'm making the argument that this is overcomplicating the rendering logic. The `storyCardView` and `storyPageView` components effectively handle the `story` and `storyCard` Storyblok components. Adding the `story` and `storyCard` react components are completely unnecessary.

2021-09-09 20:39 UTC, yvonnetangsu commented on src/components/components.js
> +  trip: TripPage,
Hmm..... let's try it your way then, @mattanglin! I'm up for simplifying things 😃

2021-09-09 22:11 UTC, yvonnetangsu requested changes
@mattanglin If you could please reverse the modal button dcnb change (for now at least, until we decide what to do with className prop), then this is GTG for me. Really nice improvement with omitting the page generation for global components. Thanks!

2021-09-09 22:19 UTC, yvonnetangsu approved these changes
GTG thank you!

2021-09-09 22:23 UTC, merged