ADAPT-3263 | @mattanglin | trip card
SU-SWS/saa_alumni pull request #163
Opened 2021-09-14 00:14 UTC by mattanglin

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-09-14 17:24 UTC, mattanglin commented on src/components/cards/TripCard/TripCard.jsx
> +    <FlexBox direction="col" element="article" className={styles.root}>
Ideally, this would've been extracted out into a more reusable component for cards, but I stopped here rather than try to refactor all the other cards in this PR.

2021-09-14 17:25 UTC, yvonnetangsu commented
Thank you for the work, @mattanglin! I'll review today.

2021-09-14 17:27 UTC, mattanglin commented on src/components/simple/Date/Date.jsx
> +export const Date = ({ startDate, endDate, isMinimal, className }) => {
I saw that we have the `DateBlock` component, but wanted to encapsulate the functionality and make it more developer friendly in terms of composition (and seeing that we were duplicating logic in multiple places).
Once again, there is some amount of duplication due to not wanting to do a complete refactor in this PR.

2021-09-14 18:05 UTC, mattanglin commented on src/components/cards/TripCard/TripCard.jsx
> +          size="vertical_3x2"
I know the design currently has 1x1 images, but also know that there are currently discussions for changing that around. We'll likely need to revisit this at some point in the future.

2021-09-14 18:13 UTC, mattanglin commented
> Thank you for the work, @mattanglin! I'll review today.

I coded some things in a slightly different way than what currently exists in the codebase, which I'm happy to discuss my reasoning for and/or revert if it's causing too much friction.

2021-09-14 18:35 UTC, yvonnetangsu commented on src/types/TripType.js
> +};
This is a good idea - PropTypes probably not as good as Typescript but it's the next best thing for now I guess 😂  I'm up for this.

2021-09-14 18:59 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.jsx
> +import * as styles from "./TripCard.styles";
I quite like this idea of separating the styles out. Make the jsx cleaner 🤔

2021-09-14 19:02 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-4 su-font-bold su-relative su-inline su-text-white";
I've found that for card headings I prefer to add the font size `su-type-4` in the link, and add `su-type-0` in the heading. This way it scales the arrow icon up perfectly also.

On a related note, I'm asking Bhavika on Figma if we can scale down the trip card heading to `su-type-3` (so it matches the event card with the "large" heading option, and also makes it a bit smaller since it's quite large now).

2021-09-14 19:33 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-4 su-font-bold su-relative su-inline su-text-white";
Got confirmation from Bhavika that we can step the title font size fo `su-type-3`. So if you add `su-type-3` to `link`, and `su-type-0` to `heading` here, it would make it look the same as other cards 😄

2021-09-14 22:38 UTC, mattanglin commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-4 su-font-bold su-relative su-inline su-text-white";
Cool 👍🏼 . I was using the typography variants listed in the figma file, but they did seem a little big. Will change these up.

2021-09-14 22:44 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-4 su-font-bold su-relative su-inline su-text-white";
We do these push and pull with our design team often 😄 . Since sometimes things need adjustment once they've been built. Please feel free to do the same if you feel like designs could be tweaked.

I'm actually asking Bhavika more questions about the date block since the font size and alignment (left margin) are different from the event cards, but this PR doesn't have to wait for that, since we will have plenty of time to do those finetuning later on. I'll come back to review this some more after finishing up my accessibility PR for SAA so I'm not blocking you.

2021-09-14 22:49 UTC, mattanglin commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-4 su-font-bold su-relative su-inline su-text-white";
Cool. Maybe we can pull them out the resulting card styles into a more generalized component that can be used for all event/perk/trip cards

2021-09-14 22:51 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +export const content = "su-px-26 su-pb-34 su-text-white";
For the padding and margins, we prefer to use the responsive spacing classes when we can, e.g., su-rs-px-1, su-rs-mb-0 etc. You could probably use the same values for the paddings as the Event cards for this one.

2021-09-14 22:55 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-4 su-font-bold su-relative su-inline su-text-white";
Yeah, I got the "GradientCard" one for Perk/Collection cards, and I can see another abstract style for the Event/Trip cards (we have so many cards 😂 ). I can see both of us doing some housecleaning this upcoming sprint too. For this PR, totally fine with how this is for now, so this can be merged sooner.

2021-09-14 22:58 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-4 su-font-bold su-relative su-inline su-text-white";
^^^ and of course the GradientCard could use some refactor - I like the new convention you set in this PR.

2021-09-14 23:01 UTC, mattanglin commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-4 su-font-bold su-relative su-inline su-text-white";
Yeah, I saw the `GradientCard` and started out trying to use it for trips then realized I was about to make a mess of the existing code and decided to do a new one instead 🤷🏼

2021-09-14 23:03 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-4 su-font-bold su-relative su-inline su-text-white";
The 2 styles are different enough so it's probably easier to have 2 separate ones anyway 😄  Reusing only make sense when it doesn't cause a lot of hair pulling.

2021-09-14 23:10 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-stretched-link su-z-20 su-rs-mt-0 su-mb-08em su-no-underline hocus:su-underline su-underline-offset !su-underline-thick !su-underline-digital-red-xlight";
```suggestion
  "su-stretched-link su-z-20 su-rs-mt-0 su-mb-08em su-type-3 su-no-underline hocus:su-underline su-underline-offset !su-underline-thick !su-underline-digital-red-xlight";
```
Give this a try, in combination with the below su-type-0 in heading

2021-09-14 23:10 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  "su-mt-32 su-type-3 su-font-bold su-relative su-inline su-text-white";
```suggestion
  "su-mt-32 su-type-0 su-font-bold su-relative su-inline su-text-white";
```

2021-09-14 23:12 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +export const icon = "su-relative su-inline-block";
```suggestion
export const icon = "su-relative su-inline-block group-hocus:su-text-white";
```
For headlines on dark bg, icon changes to white on hover/focus

2021-09-14 23:18 UTC, yvonnetangsu commented
@mattanglin If you could please add one schema called headingLevel (dataSource Heading Level available) for the trip card, that'd be great. We add that for all the cards (please see event cards for example), so for accessibility, content authors can pick which heading level depending on how deeply nested these cards are.

2021-09-14 23:44 UTC, mattanglin commented on src/components/cards/TripCard/TripCard.styles.js
> +  'su-mt-32 su-type-0 su-font-bold su-relative su-inline su-text-white';
hmmmm... I think these style classes are still off. This is resulting in a trip card heading computed `font-size` of `44.85px` while the event card heading computes to `28.75px`...

2021-09-14 23:47 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  'su-mt-32 su-type-0 su-font-bold su-relative su-inline su-text-white';
That's because event cards have 2 heading size options, the large one uses su-type-3 while the default one uses su-type-1 😄

2021-09-14 23:55 UTC, mattanglin commented on src/components/cards/TripCard/TripCard.styles.js
> +  'su-mt-32 su-type-0 su-font-bold su-relative su-inline su-text-white';
Ah. I see now.

2021-09-15 00:00 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +  'su-group su-relative su-overflow-hidden su-bg-black-true su-break-words su-border-su-border-black';
```suggestion
  'su-group su-relative su-overflow-hidden su-bg-black-true su-break-words su-border-black';
```
Looks like a typo perhaps?

2021-09-15 00:02 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +export const content = 'su-rs-px-1 su-rs-pb-3 su-text-white';
```suggestion
export const content = 'su-rs-px-2 su-rs-pb-3 su-text-white';
```
For now, let's use a padding-2 so the content padding matches the event. On the event cards, the dateblock is actually pulled more to the left compared to the content, so I'm asking Bhavika to confirm this. This is her most updated mockup
![Screen Shot 2021-09-14 at 4 45 22 PM](https://user-images.githubusercontent.com/42749717/133349378-c8357985-621c-43fb-ad73-212f19d5cf77.png)

It's still different from events, but for now let's just do a su-rs-px-2 on everything.

2021-09-15 00:03 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +export const content = 'su-rs-px-1 su-rs-pb-3 su-text-white';
Also, if you could please make the month and day left aligned in the dateblock, that'd be great (this part we're sure about)

2021-09-15 00:05 UTC, yvonnetangsu commented on src/components/cards/TripCard/TripCard.styles.js
> +export const description = 'su-mt-19 su-card-paragraph';
```suggestion
export const subheading = 'su-mt-4 su-mb-0 su-type-0 su-font-semibold';
export const description = 'su-rs-mt-0 su-mb-0 su-card-paragraph ';
```

2021-09-15 00:10 UTC, yvonnetangsu requested changes
Looking awesome, @mattanglin 👏🏼  Just those few final things in suggestions, and one more:

Looks like somehow the dateblock has a z index higher than the stretched link itself so when you hover over it, it's not clickable. I think you're working on it already, but it might need some small tweaks still. Let's make it work like the event cards:
https://alumni-preview.stanford.edu/test/yvonne/test-events/

If you could please fix those, then this is GTG! We can finetune as we get confirmation from designer.

2021-09-15 00:46 UTC, yvonnetangsu approved these changes
Thank you for the changes @mattanglin , GTG 🚀  - we'll come back to those dateblock changes later. I like the new conventions and will try to match what you have from now on 😄

2021-09-15 15:44 UTC, merged