ADAPT-3714: set focus to the number of results when the "View Results…
SU-SWS/saa_alumni pull request #168
Opened 2021-09-15 13:18 UTC by andrewbaraniuk

…" button is activated

# READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- Currently, in the mobile view of the search results page, when the "View Results" button is activated, focus does not move to the top of the results. This PR is to set focus to the number of results when the "View Results" button is activated.

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Navigate to /search page on mobile device and search by some keyword.
2. Select some filter and hit "View Results" button.
3. Verify that focus moves to the number of results on the top.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-09-15 22:12 UTC, yvonnetangsu requested changes
@andrewbaraniuk I think we might need a little bit more than scrolling to the results. If you could please also add a tabindex="0" to the number of results, then actually set the focus to that div for the onClick function (can keep the scrolling no problem) that'd be great.

2021-09-16 08:20 UTC, andrewbaraniuk commented
> @andrewbaraniuk I think we might need a little bit more than scrolling to the results. If you could please also add a tabindex="0" to the number of results, then actually set the focus to that div for the onClick function (can keep the scrolling no problem) that'd be great.

Hi @yvonnetangsu ! Done! Please let me know if that is what you've expected, thanks!

2021-09-16 16:37 UTC, yvonnetangsu commented on src/components/search/searchResults.js
> +        <span className="su-font-semibold" tabIndex={0}>{results.nbHits}</span> results:
Could we move this tabindex to the #search-results div, since in the onClick function, it's set to focus on the ID with #search-results, so that's the element that actually needs to become focusable by having the tabindex=0?

2021-09-16 16:49 UTC, yvonnetangsu commented on src/components/search/searchResults.js
> +        <span className="su-font-semibold" tabIndex={0}>{results.nbHits}</span> results:
Also, please do `npm run lint:fix` before pushing up final commit. Thanks!

2021-09-16 22:16 UTC, yvonnetangsu commented
@andrewbaraniuk Please also merge main into your branches before you revise 😄  There's some changes that just got merged in related to search.

2021-09-17 16:40 UTC, yvonnetangsu approved these changes
Tested GTG!

2021-09-17 16:40 UTC, merged