ADAPT-3287 | @mattanglin | trip filter pagination
SU-SWS/saa_alumni pull request #181
Opened 2021-09-21 22:42 UTC by mattanglin

# NOT READY FOR REVIEW
- This PR is based off of #173 which is based off of #179 and is waiting for them to be merged. It will be rebased once that PR is merged so please don't bother looking at this code until then.

# Summary
- Trip filters Pagination and general pagination component

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

2021-09-22 17:11 UTC, yvonnetangsu commented
Looking really great! 😄

2021-09-23 16:40 UTC, yvonnetangsu commented on src/components/page-types/TripFilterPage/TripFilterPage.jsx
> +                    />
I saw that you've already added the `aria-label` prop, might as well set it here. Are you holding off on doing accessibility/finetuning stuff for now?

2021-09-23 16:43 UTC, yvonnetangsu commented on src/components/composite/Pagination/Pagination.jsx
> +                  className={styles.pageLink({ active: page === currentPage })}
For the current page in the pagination, could we add these TW classes "`su-cursor-default su-pointer-events-none`"?

2021-09-23 16:49 UTC, yvonnetangsu requested changes
This is working great. Just a couple minor things in the comments and this:
After clicking on the pagination, could we have it go to an anchor/id at the top of the results so if I hit `tab`, I'll focus on the first trip card? Currently, if I click on the pagination, it scrolls to the top, but if I hit `tab`, my focus lands on the next page link in the pagination.

Good to go after this 👏🏼

2021-09-23 16:50 UTC, mattanglin commented on src/components/page-types/TripFilterPage/TripFilterPage.jsx
> +                    />
Nope! Just added the prop, then forgot to pass it a value 😛 .

2021-09-23 16:53 UTC, yvonnetangsu commented
FYI, we'll need to modify the pagination for mobile (Bhavika designed the one for SAA Homesite search, so I'm assuming we'll go with that here too). The desktop one doesn't fit on mobile.
This can go into another ticket/PR of course 😄

2021-09-23 16:54 UTC, yvonnetangsu commented on src/components/page-types/TripFilterPage/TripFilterPage.jsx
> +                    />
Haha I do that all the time 😄

2021-09-23 16:57 UTC, mattanglin commented
> FYI, we'll need to modify the pagination for mobile (Bhavika designed the one for SAA Homesite search, so I'm assuming we'll go with that here too). The desktop one doesn't fit on mobile.
> This can go into another ticket/PR of course 😄

Yeah, I saw the mobile pagination for the search. The pagination hook is setup to generate page numbers the same way for mobile, it just needs to be integrated. Another ticket/PR for sure 👍🏼

2021-09-23 17:36 UTC, yvonnetangsu commented on src/components/composite/Pagination/Pagination.jsx
> +                onClick={() => focusElement('.filtered-trips-list')}
Thanks for this change! Could we also add a scrollTo to the top of .filtered-trips-list for all the pagination links?

2021-09-23 17:52 UTC, mattanglin commented on src/components/composite/Pagination/Pagination.jsx
> +                onClick={() => focusElement('.filtered-trips-list')}
I removed the scrollTo since the the focus automatically adjusts the window scroll. Are you wanting to add it back for smoother scrolling behavior?

2021-09-23 17:59 UTC, yvonnetangsu commented on src/components/composite/Pagination/Pagination.jsx
> +                onClick={() => focusElement('.filtered-trips-list')}
Yeah, after the first `tab` when it's focused on the whole results container, it scrolls to the middle part of the results for me. Would be great if it scrolls to the top of the results 🙏🏼

2021-09-23 18:04 UTC, mattanglin commented on src/components/composite/Pagination/Pagination.jsx
> +                onClick={() => focusElement('.filtered-trips-list')}
Sounds good to me! 👍🏼

2021-09-23 18:09 UTC, yvonnetangsu approved these changes
Thanks for the change! GTG after resolving merge conflict, and sounds like you are going to remove fake data before merging also so please merge when ready 😄

2021-09-23 18:10 UTC, mattanglin commented
> Thanks for the change! GTG after resolving merge conflict, and sounds like you are going to remove fake data before merging also so please merge when ready 😄

Yes! Thanks for reminding me! I was planning on rolling with 16 trips per page as I believe that's what the search results page is currently using.

2021-09-23 21:16 UTC, merged