ADAPT-3779: More a11y fixes
SU-SWS/saa_alumni pull request #193
Opened 2021-09-28 18:19 UTC by yvonnetangsu

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-09-29 00:44 UTC, yvonnetangsu commented on src/components/cta/ctaButton.js
> +              {srText && <SrOnlyText srText={` ${srText}`} />}
Add a space between CTA button text and any screen reader text that comes after

2021-09-29 00:44 UTC, yvonnetangsu commented on src/components/cta/ctaLink.js
> +                {srText && <SrOnlyText srText={` ${srText}`} />}
Add a space between CTA link text and any screen reader text that comes after

2021-09-29 00:46 UTC, yvonnetangsu commented on src/components/layout/modal.js
>    });
Add more checks for the Escape button when search modal is open - 
1. Don't close search modal if the autocomplete dropdown is open - it should close the dropdown instead.
2. Return focus to the open search modal button after hitting Escape to close the modal

2021-09-29 00:47 UTC, yvonnetangsu commented on src/components/search/searchAutocomplete.js
> +  });
Hitting Escape should close the autocomplete dropdown in the search input if it's currently open

2021-09-29 00:48 UTC, yvonnetangsu commented on src/components/search/searchAutocomplete.js
> +          role="listbox"
Nothing is changed below - just indented because `useEffect` is added above the return

2021-09-29 00:49 UTC, yvonnetangsu commented on src/components/search/searchField.js
> +      setSelectedSuggestion(null);
When typing in the search input field, it should reset the selected search suggestion to null

2021-09-29 00:49 UTC, yvonnetangsu commented on src/components/search/searchFieldModal.js
> +  const inputClasses = `search-input-modal su-border-0 su-bg-transparent su-text-black-10 su-text-black-40::placeholder su-w-full su-flex-1
Add this class so I can reference the search input field inside the modal

2021-09-29 00:51 UTC, yvonnetangsu commented on src/components/search/searchFieldModal.js
> +        clearOnEscape
This isn't really part of the fixes - looks like this clearOnEscape function isn't working (implemented by FFW dev previously), or perhaps the inputRef doesn't get set properly 🤔  Maybe we could take a look later.

2021-09-29 00:51 UTC, yvonnetangsu commented on src/components/search/searchModal.js
> +      ariaLabel="Search Stanford Alumni websites"
Add aria label to search modal

2021-09-29 00:59 UTC, yvonnetangsu commented
Tagging @rebeccahongsf also since she's reviewing Algolia search that gets port over to Victoria subtheme.

2021-09-29 01:01 UTC, yvonnetangsu commented
Codeclimate warning can probably be ignored - it's just a couple 1-liner duplications from CTA button and link.

2021-09-29 16:01 UTC, sherakama commented on src/components/search/searchFieldModal.js
> +        clearOnEscape
I think at this point you can remove the clearOnEscape functions.

2021-09-29 16:02 UTC, sherakama requested changes
Before merging, please review the clearOnEscape prop and resulting functionality to ensure you can remove it. I feel the escape key has been taken care of and it could likely be removed.

2021-09-29 16:46 UTC, yvonnetangsu commented
> Before merging, please review the clearOnEscape prop and resulting functionality to ensure you can remove it. I feel the escape key has been taken care of and it could likely be removed.

I've removed the clearOnEscape function and prop. Things still behave the same on the search page and modal so I think we're good to merge.

2021-09-29 22:11 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +        "cta-card su-w-full su-relative su-transition-colors su-bg-digital-red su-text-white hover:su-bg-black focus-within:su-bg-black su-basefont-23 su-break-words su-rs-py-3 su-rs-px-2 su-flex su-
Actually changing hover color to black still doesn't pass contrast test. Asking Kerri if ok to update link color to white on hover in CTA card

2021-09-30 16:13 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +        "cta-card su-w-full su-relative su-transition-colors su-bg-digital-red su-text-white hover:su-bg-black focus-within:su-bg-black su-basefont-23 su-break-words su-rs-py-3 su-rs-px-2 su-flex su-
Kerri ok-ed changing link color to white on hover/focus. Just updated. I think that's all for real.

2021-10-04 23:35 UTC, sherakama approved these changes
GTG. Thanks.

2021-10-05 00:02 UTC, merged