ADAPT-4093: Add anchore to sbLink component
SU-SWS/saa_alumni pull request #257
Opened 2021-12-08 18:24 UTC by Lyafel

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to test/elena/misc/#test2
3. Check the first and third card links

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-12-08 23:05 UTC, sherakama commented on src/utilities/sbLink.js
> +  } else if (props.link?.linktype === 'email') {
I don't think this is quite right. 

This will force the anchor to be in-page only. Don't we want to keep the URL here?

2021-12-08 23:06 UTC, sherakama commented on src/utilities/sbLink.js
> +    if (!props.link?.anchor) {
I think we would want to support all of the below with the anchor and not make them exclusive.

2021-12-08 23:07 UTC, sherakama requested changes
Please see comments.

2021-12-08 23:07 UTC, yvonnetangsu commented on src/utilities/sbLink.js
> +  } else if (props.link?.linktype === 'email') {
Yeah what @sherakama said

2021-12-08 23:07 UTC, sherakama commented
@Lyafel please include a test scenario in the pull request template when you submit for review so it is easier for us to the work.

2021-12-08 23:21 UTC, yvonnetangsu commented
@sherakama This looks to be a small PR, so I'll wait for this to get merged to create that release.

2021-12-10 20:44 UTC, Lyafel commented
@sherakama I removed the condition. The anchors are added to /test/elena/misc

2021-12-10 23:28 UTC, yvonnetangsu commented on src/utilities/sbLink.js
> +    linkUrl += linkUrl.endsWith('/') || props.link?.anchor ? '' : '/';
@sherakama I added this to the conditional so it doesn't add a trailing / when there's an anchor.

2021-12-10 23:35 UTC, yvonnetangsu commented
Looks like it's GTG
https://deploy-preview-257--stanford-alumni.netlify.app/test/elena/misc/
hovering over the 1st link button and the last CTA link
![Screen Shot 2021-12-10 at 3 34 12 PM](https://user-images.githubusercontent.com/42749717/145653946-46859328-c531-4980-894c-fbbb9a084a4b.png)
![Screen Shot 2021-12-10 at 3 33 58 PM](https://user-images.githubusercontent.com/42749717/145653955-4adf22cd-6326-4325-a2eb-885a76aa5cc9.png)

2021-12-10 23:36 UTC, yvonnetangsu approved these changes
This looks GTG to me!

2021-12-10 23:51 UTC, sherakama commented on src/utilities/sbLink.js
> +    linkUrl += linkUrl.endsWith('/') || props.link?.anchor ? '' : '/';
Thanks for this.

2021-12-10 23:51 UTC, sherakama approved these changes
GTG

2021-12-10 23:51 UTC, merged