ADAPT-3993: Filter out the past trips
SU-SWS/saa_alumni pull request #264
Opened 2021-12-16 19:09 UTC by Lyafel

# Summary
- Filtered out the past trips to make sure none appear if the trip was not manually removed.

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. /travel-study/destinations/
3. Verify no past trips appear

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-12-16 19:09 UTC, Lyafel commented
For testing I unchecked the Hide on Trip Filter Pages from https://app.storyblok.com/#!/me/spaces/118608/stories/0/0/79657994 so it's supposed to appear in the list without the current pr.

2022-01-03 19:50 UTC, sherakama commented
@Lyafel Can you also add a condition to gatsby-node.js to filter out the past trips so that they don't get built at build time?

@yvonnetangsu to review.

2022-01-03 22:24 UTC, yvonnetangsu requested changes
@Lyafel This looks good to me - please see @sherakama's comment about the gatsby node change, after that should be GTG. Thanks.

2022-01-04 22:23 UTC, Lyafel commented
@sherakama ready for review, hope I understood you correctly.

2022-01-05 20:10 UTC, sherakama commented on gatsby-node.js
> +            const tripDate = Date.parse(content.startDate);
```suggestion
            const tripDate = Date.parse(content.endDate);
```

2022-01-05 20:19 UTC, sherakama commented on gatsby-node.js
> +            const start = new Date();
This might get a bit trixy. @yvonnetangsu the trip is assumed to start/stop on the PST timezone and I believe Netlify's servers run with UTC. With the timezone unset, it might unpublish the trip 8 hours too early. 

When creating the new date object you should set the timezone 

eg: `const start = new Date().toLocaleString("en-US", {timeZone: "America/Los_Angeles"})`

2022-01-05 20:21 UTC, sherakama commented on gatsby-node.js
> +            const tripDate = Date.parse(content.startDate);
Check to see if this needs to be adjusted for timezone as well.

2022-01-05 20:23 UTC, sherakama commented
@yvonnetangsu I'd like to confirm my assumption of unpublishing trips that have passed. You do not want to display trips that have gone past their end date correct?

2022-01-05 20:25 UTC, yvonnetangsu commented on gatsby-node.js
> +            const start = new Date();
@sherakama For T/S we actually use the date picker that has no time info (only date), so we're actually using UTC for everything.

2022-01-05 20:27 UTC, yvonnetangsu commented
> @yvonnetangsu I'd like to confirm my assumption of unpublishing trips that have passed. You do not want to display trips that have gone past their end date correct?

I believe that's what they want. They're still encouraged to unpublish manually, but automatically removing it was a nice to have. Tagging @mattanglin to confirm since he was in some of the earlier discussions.

2022-01-05 21:02 UTC, sherakama commented on gatsby-node.js
> +            const start = new Date();
Aye, but the customer and client expectations would be that the start/stop for the trip be in PST isn't it? I understand the data from storyblok is one thing but there might be confusion if the trip goes away at 4:00PM on the day it ends, no?

2022-01-05 21:10 UTC, mattanglin commented
> > @yvonnetangsu I'd like to confirm my assumption of unpublishing trips that have passed. You do not want to display trips that have gone past their end date correct?
> 
> I believe that's what they want. They're still encouraged to unpublish manually, but automatically removing it was a nice to have. Tagging @mattanglin to confirm since he was in some of the earlier discussions.

@yvonnetangsu @sherakama From my recollection the idea was simply to remove the trips from showing up in the filters since they would would sorted to the top in the filtered result set, so just the work that's been done in `useTrips.js`. I'd say the changes in `gatsby-node.js` to not publish the trips is nice-ish to have, but also kind of moot since it requires the site to be rebuilt to affect anything 🤷🏼 . The general idea is that content authors would manually go in and unpublish past trips

2022-01-05 22:28 UTC, yvonnetangsu commented on gatsby-node.js
> +            const start = new Date();
@sherakama I see what you're saying, and my intuition totally agrees with you. But I've been tricked by this time thing before so I'm going to test this out a bit more myself 😂

2022-01-05 22:33 UTC, sherakama commented on gatsby-node.js
> +            const start = new Date();
@Lyafel see previous comment.

2022-01-06 06:01 UTC, yvonnetangsu commented on gatsby-node.js
> +            const start = new Date();
@sherakama I thought about this a little bit more, and I'm wondering that perhaps we could leave this as is. Reason being that when I'm looking at the trips on the site, it looks like they trip start date is actually the flight arrival date in the destination country 🤔  Here's an example of a trip to Japan - looks like the start date actually corresponding to the arrival date in Japan in the Itinerary section:
https://staging.alumni.stanford.edu/travel-study/destinations/japan-2022#itinerary-section

Plus with the datepicker without the time field, the date doesn't change no matter what the client's time zone setting is since we manually set it to UTC. In a previous PR, I had to remove the LA timezone part since it caused a discrepancy between the date shown in the Storyblok datepicker and the date actually rendered on the Trip page. So maybe if we just keep everything in UTC then it will be ok?
https://github.com/SU-SWS/saa_alumni/pull/223#discussion_r733967183

2022-01-06 23:02 UTC, sherakama commented on gatsby-node.js
> +            const start = new Date();
Hmm. Well, it seems like my ask was not so simple after all. Without a clear timezone for the end date, I think we should just remove the gatsy-node.js code. I wouldn't want confusion between the build code and the runtime code. 

My apologies for overcomplicating this.

2022-01-07 00:04 UTC, yvonnetangsu commented on gatsby-node.js
> +            const start = new Date();
@sherakama Sounds good to me 😄  Time is complicated - you're totally not overcomplicating it. Thank you for the discussion as usual. I appreciate you sharing your thoughts always!

@Lyafel Please remove the gatsby-node.js code as Shea suggested above.

2022-01-11 23:40 UTC, sherakama approved these changes
GTG

2022-01-11 23:54 UTC, sherakama commented
@yvonnetangsu gets to push the green button when ready.

2022-01-12 17:26 UTC, yvonnetangsu commented
> @yvonnetangsu gets to push the green button when ready.

GTF. Green button will be pushed 😄

2022-01-12 17:27 UTC, yvonnetangsu approved these changes

2022-01-12 17:28 UTC, merged