ADAPT-4280: Theme localist widget
SU-SWS/saa_alumni pull request #276
Opened 2022-01-24 19:19 UTC by Lyafel

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2022-01-24 20:01 UTC, sherakama commented
What is the path to review the localist embed?

2022-01-25 18:54 UTC, Lyafel commented
@sherakama right, sorry. I added it on the home page on alumni dev but it's not visible on the build, is that something I could fix or how does it work?

2022-01-25 18:59 UTC, yvonnetangsu commented
> @sherakama right, sorry. I added it on the home page on alumni dev but it's not visible on the build, is that something I could fix or how does it work?

@Lyafel You're free to publish any pages on the **DEV - SAA Alumni** Storyblok space. Only published pages will be built in the Netlify preview deploys.

2022-01-26 21:53 UTC, Lyafel commented
@yvonnetangsu How do make it rebuild? I published the node but the build still doesn;t show the changes

2022-01-26 22:36 UTC, yvonnetangsu commented
> @yvonnetangsu How do make it rebuild? I published the node but the build still doesn;t show the changes

@Lyafel You could log into Netlify, click into your branch deploy preview and click "Deploy site" again :)
![Screen Shot 2022-01-26 at 2 36 16 PM](https://user-images.githubusercontent.com/42749717/151258707-a583c867-b2e0-4c40-a5ab-29d56e486916.png)

2022-01-27 18:07 UTC, Lyafel commented
@yvonnetangsu Now I know everything, thanks :D

2022-01-27 18:08 UTC, Lyafel commented
@sherakama The block is visible on the build now, front page at the bottom

2022-01-27 23:16 UTC, yvonnetangsu requested changes
@Lyafel This is looking really great! A few things:

- Could we change the card headline to serif?
- The month portion of the date in the circle should left align with the day number
- Could we get rid of that dotted line under the month in the circle? And add a bit more space underneath (so it matches the Event Cards)?
- If possible please add the external link icon after the card title

2022-01-27 23:18 UTC, yvonnetangsu commented on src/styles/localist.css
> +  background-image: url("../asseets/calendar.svg");
Would be great to fix up the folder name typo "asseets" to "assets". Hmm actually wouldn't that needs to be place inside the /static folder for Gatsby also?

2022-01-27 23:19 UTC, yvonnetangsu commented on src/styles/localist.css
> +  font-size: 2.1rem;
How come not using su-text-21 here? 🤔

2022-01-27 23:27 UTC, yvonnetangsu commented
@Lyafel Sorry miss a few 😂 
- Please add an object-fit:cover (TW equiv) to the image so it's not distorted
- Looks like when one hovers over the date circle portion of the card, it becomes not clickable - maybe a z-index issue?

2022-02-01 17:37 UTC, Lyafel commented on src/styles/localist.css
> +  background-image: url("../asseets/calendar.svg");
I looked a bit at it, looks like it's recommended to call assets from js not from static for simpler cases, but also I didn't manage to call the icons from static to css.

2022-02-01 17:52 UTC, Lyafel commented
Done thought couldn't align the dates correctly because of the structure available.

2022-02-02 20:22 UTC, yvonnetangsu requested changes
@Lyafel This looks fantastic! If you could please left align the day and month inside the circle, then this is GTG. Thanks!
![Screen Shot 2022-02-02 at 12 20 36 PM](https://user-images.githubusercontent.com/42749717/152231302-817c355e-ab98-479c-879b-73ff93b93e09.png)

2022-02-02 20:28 UTC, yvonnetangsu commented
> Done thought couldn't align the dates correctly because of the structure available.

Oh - sorry just saw this comment. Let me take a look

2022-02-03 09:05 UTC, yvonnetangsu commented
@sherakama I pushed up some final tweaks (responsive font sizes, icons, date circle) - final approval is yours 😄

2022-02-03 18:00 UTC, sherakama commented
@yvonnetangsu 
Is the word 'sponsors' supposed to be there?

https://share.getcloudapp.com/eDulrGk9

2022-02-03 18:04 UTC, yvonnetangsu commented
> @yvonnetangsu Is the word 'sponsors' supposed to be there?
> 
> https://share.getcloudapp.com/eDulrGk9

Yeah, the clients added it on the production sites under the ads. If we're doing this for real though, the whole localist section will need to be in its own section and not inside the same section as the other ads, so this should be ok

2022-02-04 17:26 UTC, sherakama approved these changes
GTG. Thank you.

2022-02-04 17:27 UTC, merged