ADAPT-4307: Added unsafe-eval to Netlify security policy to allow AdPlugg embeds.
SU-SWS/saa_alumni pull request #281
Opened 2022-02-07 21:33 UTC by nplowman

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2022-02-08 00:17 UTC, sherakama commented on netlify.toml
> +    Content-Security-Policy = "default-src https: 'unsafe-inline' 'unsafe-eval'; form-action https:; img-src https: data:"
We better be careful who we embed 😟 . This does seem necessary as we do allow are content authors to embed from anywhere.

2022-02-08 00:17 UTC, sherakama approved these changes
~GTG~

@nplowman the example URL is still not loading for me. Postscript is complaining about something... 

![Screen Shot 2022-02-07 at 4 19 30 PM](https://user-images.githubusercontent.com/550602/152894214-1ba0ef12-02f6-4a48-b559-e9b29e0e2e03.png)

2022-02-08 00:24 UTC, sherakama requested changes
Script errors are happening

2022-02-15 18:01 UTC, sherakama commented
@nplowman please review the feedback

2022-02-15 18:04 UTC, nplowman commented
@sherakama Hmm. That's odd - I'm not able to reproduce this on my end. Do you happen to have an ad blocker enabled, or any other chrome plugins that could be interfering? 

Could you see if you get the same issue in an incognito window?

2022-02-15 18:22 UTC, sherakama commented
Ah. That seems to be it. Sorry for the false alarm.

2022-02-15 19:52 UTC, sherakama approved these changes

2022-02-15 19:52 UTC, merged