ADAPT-4413 | @rebeccahongsf | add giveGabForm component, dynaScript, and giveGabVars
SU-SWS/saa_alumni pull request #286
Opened 2022-02-11 22:15 UTC by rebeccahongsf

# NOT READY FOR REVIEW

# Summary
- add giveGabForm component, dynaScript, and giveGabVars

# Review By (Date)
- when possible :D 

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Run `netlify dev` locally and navigate to `/test/rebecca/tsgg-givegab-component`
3. Confirm that the Pledge GiveGab form appears. Login as zguan and confirm that the first name, last name, and email address populated. 
4. Log onto Storyblok and review the giveGabForm component in `DEV - SAA Alumni TSGG`
5. Review code and see if anything smells

**Note:** 
- Pointing to Nathan's auth branch for now. Once his work is merged into `tsgg`, I'll rebase/cherry-pick these changes.
- The test GiveGab component has been placed on a basic page. 
- Additional adjustment to form field population within `giveGabVars` will be needed depending on how fields are named, especially for the registration form information. 
- Console.log() within the GiveGabForm component will need to be remove before merge.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- ADAPT-4413

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2022-02-11 22:39 UTC, rebeccahongsf commented on src/components/embed/giveGabForm.js
> +    extension_amount: extensionAmount,
I noticed that in Make a Gift, we name the GiveGabForm component fields machine name with underscores (i.e. `head_js`). 

Is it okay to map them to camelCase to match the other key values in the giveGabVars?

2022-02-11 22:42 UTC, rebeccahongsf commented on src/components/embed/giveGabForm.js
> +    setGiveGabVars(user, ggForm);
Since we have additional parameters (i.e. tripId, tripName, etc), would this be the correct way to pass them into the `setGiveGabVars` handler?

Should this information be passed in this way? This might be a question for GG or Bhavika — will the tripId be present in the HTML but visually hidden on the form? Or will it appear in the form but be uneditable? I assume we wouldn't want the user to be able to edit the trip id 🤔

2022-02-11 22:43 UTC, rebeccahongsf commented on src/utilities/giveGabVars.js
> +  // TODO: Determine is specification of spouse relationship is needed
I commented out the spouse related fields for now since I was not sure if specifying spouse from other relationships is necessary. I assume the the structure of how we pre-populate the relationships might differ from what we did with Make a Gift.

2022-02-11 22:51 UTC, rebeccahongsf commented
@sherakama I left some questions and comments but piecing together the form based on the previous Make a Gift work seemed pretty straight forward.

Will we have an additional ticket (or continue working off of this ticket) to handle and modify the pre-populated fields once the MegaProfile API and Test GG form is available? 

I also recall from one of our previous working sessions is needing to test for the pre-population for the unique address fields scenario — should I add that work to our JIRA import spreadsheet or should it also be a part of this ticket? 😃

2022-02-12 00:13 UTC, sherakama commented on .babelrc
> +    "@emotion"
I haven't gone through this PR fully yet but why are we adding emotion to this?

2022-02-12 00:13 UTC, sherakama commented on package.json
> +    "@emotion/babel-plugin": "^11.7.2",
?

2022-02-12 00:22 UTC, sherakama commented on src/components/embed/giveGabForm.js
> +    extension_amount: extensionAmount,
Sure.

2022-02-12 00:41 UTC, rebeccahongsf commented on package.json
> +    "@emotion/babel-plugin": "^11.7.2",
Part of Nathan's work (as I mentioned in more detail [above](https://github.com/SU-SWS/saa_alumni/pull/286#discussion_r805087872) 😃 )

2022-02-15 00:39 UTC, sherakama commented on .babelrc
> +    "@emotion"
Gotcha, that makes sense. We will be merging Nathans work down into your branch and out into the dev branch for the perks work so it is fine here. Thanks for your patience with clarification on this part.

2022-02-15 00:52 UTC, sherakama commented on src/components/embed/dynaScript.js
> +        'Sorry, we are experiencing technical difficulties. Please try refreshing your browser or return later to book your trip. Thank you!'
As we have different forms now we should make this a prop with a default. I think we will want different error messages for the different forms.

2022-02-15 01:04 UTC, sherakama commented on src/components/embed/giveGabForm.js
> +    setGiveGabVars(user, ggForm);
You won't need to wait until the user is logged in to put the variables from this specific form into the global javascript space. As these variables are available from storyblok at build time, you will want to ensure that they are put into `window.xyz` when the component mounts and remove them when the component unmounts. You can do this with your own useEffect that is not attached to the user logged in state.

2022-02-15 01:08 UTC, sherakama commented on src/utilities/giveGabVars.js
> +const findPreferredEmail = (emails) => {
Unfortunately, these are not going to be as useful to you anymore. We are going to be using the megaprofile microservices API instead of the givegab API and you will need to fetch from all different endpoints with different data structures. This file can be removed now. We can come back to this in a different PR.

2022-02-15 01:09 UTC, sherakama commented on src/utilities/giveGabVars.js
> +  // TODO: Determine is specification of spouse relationship is needed
Aye, and we can remove this stuff now. We will be required to build this out in a different way. The end result is still the same with putting items into the global window space but we can tackle that in a different PR.

2022-02-15 01:10 UTC, sherakama requested changes
Nice work so far. Please review feedback.

2022-02-16 21:30 UTC, sherakama approved these changes
GTG. More goodness to come. 😄

2022-02-16 21:55 UTC, merged