Adapt 4168 new
SU-SWS/saa_alumni pull request #292
Opened 2022-02-17 06:14 UTC by sherakama

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2022-02-21 19:01 UTC, Lyafel commented
@sherakama Looks like since you created this I can't add you as a reviewer

2022-02-22 21:36 UTC, sherakama commented
@yvonnetangsu This is ready for another review

@Lyafel There is a duplicate My Account link in the utility menu

![Screen Shot 2022-02-22 at 1 35 21 PM](https://user-images.githubusercontent.com/550602/155223595-ac6985c6-b38e-4cef-a0cf-3cbfebdbb31e.png)

2022-02-22 21:55 UTC, yvonnetangsu commented
Hmm @sherakama I guess this might be a question for design 🤔 
For example, for the non-authenticated case on XS, even if we remove the duplicate "My account" link in the utility nav, we still can't fit everything on one line
![Screen Shot 2022-02-22 at 1 37 38 PM](https://user-images.githubusercontent.com/42749717/155224405-7877cb2c-6b31-4c41-9e7d-fc2e0a4cbbb0.png)

As for the logged in state, assuming that we could completely remove all the "My account" links at the top (since Account Settings links is in the user menu dropdown)...

- @Lyafel Could we vertically center aligned the text links and the middle of the circle with initials + the chevron?
- For hover/focus state of the button to open/close the user menu, could we change the background color of the initial circle to cardinal red dark (like hover state of search button in masthead)?
- Have the font sizes of the user menu items on mobile matches the ones in my account (they're currently much smaller)?
- On desktop, could we have the chevron next to the initial circle the same size as the one in the main nav?

Thanks!

2022-02-23 18:26 UTC, Lyafel commented
@yvonnetangsu styles ready for another pass. About the duplicated link though, I removed the link from the menu on dev  storyblok (to add it manually) and can see the changes in storyblok and locally but not on the build. Is it building from the prod space?

2022-02-23 19:25 UTC, yvonnetangsu commented
> 

Thanks @Lyafel ! The changes will only show up if you save before you push up a new commit. Otherwise, saving on the DEV Storyblok space doesn't actually trigger a rebuild of the site :) You could also go into Netlify and manually trigger a rebuild of your branch any time though.

2022-02-23 19:41 UTC, sherakama commented
@Lyafel and @yvonnetangsu 

I switched the base branch on this to go into `tsgg` now, which has Nathan's updates to the auth. One thing to note, is that the `tsgg` branch has its own storyblok space.

2022-02-23 19:43 UTC, yvonnetangsu commented
> @Lyafel and @yvonnetangsu
> 
> I switched the base branch on this to go into `tsgg` now, which has Nathan's updates to the auth. One thing to note, is that the `tsgg` branch has its own storyblok space.

Oh good to know - thanks, @sherakama !

2022-02-24 18:30 UTC, Lyafel commented
@sherakama I removed the links on the tsgg space, updated this branch with the tsgg branch, rerun the deployment on netlify but the changes still don't apply. Just checked with the tsgg key locally and it works well, but not sure how to update the build

2022-02-24 22:15 UTC, sherakama commented
It looks like the changes were saved but not published in SB: https://app.storyblok.com/#!/me/spaces/145938/stories/0/0/106447298

I will rebuild the Netlify environment again.

2022-02-25 08:20 UTC, yvonnetangsu requested changes
@Lyafel This is looking great.
Only a few things left - thanks!

- [ ] The background color for the initial circle should be transparent (same as the background color of the region). The cardinal red dark background only applies for the parent button's hover/focus state. Same for the red chevron (only red for hover/focus state, on desktop). I believe the behavior in the preview is the reverse of what we want.

- [ ] Please add some top/bottom padding to the dropdown user menu (similar to My Account)

- [ ] Please have the user menu dropdown spacing/font weight match the My Account one more closely. Screenshot comparison

![Screen Shot 2022-02-25 at 12 16 54 AM](https://user-images.githubusercontent.com/42749717/155679938-f5076e2b-e749-47f1-a0d8-a6204de060d0.png)
![Screen Shot 2022-02-25 at 12 16 41 AM](https://user-images.githubusercontent.com/42749717/155679907-50a8fc12-0d15-48a3-8284-7b3005744a03.png)

- [ ] On mobile the dropdown user menu still overlaps the masthead
![Screen Shot 2022-02-25 at 12 15 43 AM](https://user-images.githubusercontent.com/42749717/155679734-ae0165d1-6ede-4a4a-bae8-8a43c131deb7.png)

2022-03-01 21:52 UTC, yvonnetangsu requested changes
Super close, @Lyafel ! A few more things:

- The "My account" link at the top should have regular font weight not semibold
![Screen Shot 2022-03-01 at 1 44 25 PM](https://user-images.githubusercontent.com/42749717/156254553-8b74519c-de1b-43f1-aabf-9ff14e51deb0.png)
- Could you please match the arrow color, and the hover/focus states for the user menu items on mobile to that of My Account? The colors and behavior should stay the same for all breakpoints
My Account:
 ![Screen Shot 2022-03-01 at 1 46 53 PM](https://user-images.githubusercontent.com/42749717/156254633-753cd8ec-2b0a-4f56-bf6b-d53be10f7627.png)
Current PR:
![Screen Shot 2022-03-01 at 1 47 06 PM](https://user-images.githubusercontent.com/42749717/156254623-a7d8bb28-97eb-4878-91c4-a36751a432bb.png)
- Could you please add animation for opening the dropdown to match My Account? (I think you could straight up copy the code from there with the transformation/origin classes)

This one I'll have to check with design, but I suspect that we might need to hide the greeting on LG breakpoint 🤔  Currently there is just enough space for a pretty short name. I'll get back to you on that.
![Screen Shot 2022-03-01 at 1 45 53 PM](https://user-images.githubusercontent.com/42749717/156255072-6d516ae2-ffef-4393-9f39-ae78a79a2e6c.png)

2022-03-02 01:54 UTC, yvonnetangsu commented
> This one I'll have to check with design, but I suspect that we might need to hide the greeting on LG breakpoint 🤔 Currently there is just enough space for a pretty short name. I'll get back to you on that. ![Screen Shot 2022-03-01 at 1 45 53 PM](https://user-images.githubusercontent.com/42749717/156255072-6d516ae2-ffef-4393-9f39-ae78a79a2e6c.png)

@Lyafel I heard back from our design team. For LG breakpoint, please hide the greeting with the full name in the user menu for the login state, and just display the initial circle in the user menu button like on mobile. Thanks!

2022-03-08 19:07 UTC, yvonnetangsu requested changes
Please see the comment about the animation, after that GTG - thanks, @Lyafel !

2022-03-08 22:01 UTC, Lyafel commented
@yvonnetangsu slipped my mind. Added the classes, hope it's right, I have no access to my account for some reason :(

2022-03-08 22:07 UTC, yvonnetangsu commented
> @yvonnetangsu slipped my mind. Added the classes, hope it's right, I have no access to my account for some reason :(

Oh I didn't realize you had no access to My Account? Is it the GitHub or just the netlify previews?

2022-03-08 22:26 UTC, Lyafel commented
@yvonnetangsu It can't log in for some reason. We tried to debug it with Shea but at some point after a lot of attempts it finally let me it, and now it's back again to not giving me access. 
So I can see the code and the site but couldn't check the animation in acction to make sure 100% my code is thee same for the latest fix

2022-03-08 22:28 UTC, sherakama commented
@Lyafel I'll slack you a different user.

2022-03-08 22:41 UTC, Lyafel commented
@yvonnetangsu I think it should work correctly though, judjung by the code on my account

2022-03-08 22:52 UTC, yvonnetangsu approved these changes
GTG - thank you!

2022-03-08 23:24 UTC, merged

2022-03-08 23:25 UTC, sherakama commented
Thank you both!