ADAPT-4519 | @rebeccahongsf | create form page-type component
SU-SWS/saa_alumni pull request #309
Opened 2022-03-11 04:20 UTC by rebeccahongsf

# NOT READY FOR REVIEW

# Summary
- create form page-type component

# Review By (Date)
- end of Mochi sprint

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Review the following pages 
  - `/travel-study/italy-additional-payment-form`
  - `/travel-study/italy-notify-me-form`
  - `/travel-study/custom-journey-form`
3. Review [StoryBlok form page-type](https://app.storyblok.com/#!/me/spaces/145938/stories/0/0/114756809)
4. Review code and confirm that the necessary fields for the form page is here.

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

# Associated Issues and/or People
- ADAPT-4519

2022-03-16 21:09 UTC, sherakama commented on src/components/page-types/formPage/formPage.js
> +// import AuthenticatedPage from '../../auth/AuthenticatedPage';
Is this commented out for testing? Can we not enable this?

2022-03-16 21:12 UTC, sherakama commented on src/tailwind/plugins/theme/colors.js
> +    'saa-black-new': {
Are you sure you want to name this `-new`?

2022-03-16 21:12 UTC, sherakama commented on src/tailwind/plugins/theme/colors.js
> +    'saa-black-new': {
New get old fast.

2022-03-16 21:15 UTC, sherakama commented on src/components/page-types/formPage/tripNotifyMe.js
> +      </SAACtaLink> */}
Remove commented-out code.

2022-03-16 21:17 UTC, sherakama commented on src/components/page-types/formPage/tripNotifyMe.js
> +  }, [startDate, endDate]);
Luxon is available and installed into this project and could make this easier: https://moment.github.io/luxon/#/math?id=diffs

2022-03-16 21:21 UTC, sherakama commented on src/components/page-types/formPage/tripNotifyMe.js
> +      <Helmet titleTemplate={title} title={title} />
This works well 👍

2022-03-16 21:21 UTC, sherakama requested changes
This is looking good. Just a couple of comments to address.

2022-03-16 21:24 UTC, sherakama commented on src/components/page-types/formPage/tripNotifyMe.js
> +  }, [startDate, endDate]);
Ah, getDuration is luxon and it doesn't automatically do the plural for you? Darn. Ok forget this comment.

2022-03-17 19:28 UTC, rebeccahongsf commented on src/components/page-types/formPage/formPage.js
> +// import AuthenticatedPage from '../../auth/AuthenticatedPage';
This has been commented out for testing. Would it be easier to leave it comment out for now until Elena has finished styling the GG forms or should we just provide `zguan`'s login credentials? 😃

2022-03-17 19:29 UTC, rebeccahongsf commented on src/tailwind/plugins/theme/colors.js
> +    'saa-black-new': {
Ack! Great question and point — I'll check in with Bhavika and rename the new black variant :)

2022-03-17 23:51 UTC, rebeccahongsf commented on src/tailwind/plugins/theme/colors.js
> +    'saa-black-new': {
Looks like the saa-black-new is the same as the saa-black. Reverted the colors file and added the opacity 40 option  👍

2022-03-18 00:07 UTC, sherakama commented on src/components/page-types/formPage/formPage.js
> +// import AuthenticatedPage from '../../auth/AuthenticatedPage';
Elena has test user credentials but sometimes has issues logging in. We've identified it is a problem with firefox and will ask that she try a different browser when it happens.

2022-03-18 00:08 UTC, sherakama commented on src/components/page-types/formPage/formPage.js
> +// import AuthenticatedPage from '../../auth/AuthenticatedPage';
Please enable so we get the 'full' experience.

2022-03-18 00:08 UTC, sherakama approved these changes
GTG when you enable the auth component.

2022-03-18 15:16 UTC, merged