ADAPT-2072 Main Nav - use TW Popover component instead of Menu; Masthead
SU-SWS/saa_alumni pull request #31
Opened 2021-05-24 18:17 UTC by yvonnetangsu

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-05-25 01:28 UTC, yvonnetangsu commented on src/components/identity/masthead.js
> +              <CreateBloks blokSection={utilityNav} hasExternalIcon />
@rebeccahongsf FYI for my masthead ticket, I also need to add external link icon to a nested navItem element. This works now but I'll likely clean it up a bit more and then you could probably reuse the code for the Online Giving local footer. Tagging you so we don't end up doing duplicate work 😺

2021-05-25 20:04 UTC, yvonnetangsu commented
@sherakama This is ready for you to take an initial look (note: only 2XL looks good now. Kerri and I are still working out other breakpoints....spacing is tight). Main thing I'd like your opinion on - I'm using the Headless UI "Popover" component which is what they use for menu dropdowns like this in their paid TailwindUI as well. What do you think - it works at least as well as the mega menu on the Giving site (keyboard controls, clicking outside to close etc). The Transition component they provide is pretty sweet too:
https://deploy-preview-31--stanford-alumni.netlify.app/test/yvonne/test-masthead-landing-page/

2021-05-25 21:54 UTC, yvonnetangsu commented on src/components/content-types/perk/perkCardView.js
> +            className="su-absolute su-block su-w-full su-h-full su-top-0 su-left-0 su-bg-gradient-to-b su-from-transparent su-to-saa-black su-backface-hidden"
I added the su-backface-hidden utility to prevent gradient flickering

2021-05-26 05:58 UTC, yvonnetangsu commented on src/components/navigation/mainMenuGroup.js
> +          aria-label={`${open ? "Show" : "Hide"} ${parentText} links`}
@sherakama I'm not pleased that the button doesn't come with `aria-expanded=false` when the dropdown is close, and it looks like I can't add to it, so instead, I added these attributes which do similar things.

2021-05-26 22:52 UTC, sherakama commented on package.json
> +    "@headlessui/react": "^1.2.0",
yay!

2021-05-26 23:11 UTC, sherakama commented on src/components/identity/logo.js
> +      src="/images/saa-logo-white.svg"
Images should be imported: https://www.gatsbyjs.com/docs/recipes/working-with-images/

2021-05-26 23:12 UTC, sherakama commented on src/components/identity/logo.js
> +  <Link to="/" className="su-block su-w-fit" {...props}>
```suggestion
  <Link to="/" className="logo su-block su-w-fit" {...props}>
```

You've been adding names to others, why not this one?

2021-05-26 23:13 UTC, sherakama commented on src/components/identity/masthead.js
> +import React from "react";
Nice work on this component. Nice to see more regions than specific components.

2021-05-26 23:16 UTC, yvonnetangsu commented on src/components/identity/logo.js
> +  <Link to="/" className="su-block su-w-fit" {...props}>
Good point - adding these classes might help with Algolia search too

2021-05-26 23:17 UTC, yvonnetangsu commented on src/components/identity/logo.js
> +      src="/images/saa-logo-white.svg"
Oh good to know!

2021-05-26 23:17 UTC, sherakama commented on src/components/navigation/mainMenuGroup.js
> +            open ? "!su-text-white !su-bg-cardinal-red" : ""
Our buttons are a pain to theme without the `!`. We should consider changing our approach to them.

2021-05-26 23:18 UTC, sherakama commented on src/components/navigation/mainMenuGroup.js
> +        <Transition
This is cool. It might be nice to have a few of these pre-build and around for us to use.

2021-05-26 23:28 UTC, sherakama commented on src/components/page-types/landingPage.js
> +          </div>
Why the two sections here? So you can tuck the hero under the nav?

2021-05-26 23:30 UTC, yvonnetangsu commented on src/components/page-types/landingPage.js
> +          </div>
Now that we know we'll go with one page type - let me play around with it a bit to see what's the best way to handle this. It's possible that I can have the "content" blok absorb the "hero" one.

2021-05-26 23:32 UTC, sherakama commented on src/tailwind/plugins/theme/colors.js
> +    "masthead-black": {
Can this be a bit more generic or is this really a one-time thing?

2021-05-26 23:33 UTC, sherakama commented on src/tailwind/plugins/theme/colors.js
> +    "cardinal-red-xdark": "#7A0000",
How many more shades of red do we need...

2021-05-26 23:35 UTC, sherakama commented on src/utilities/transformImage.js
> +  if (image.endsWith(".jpg") || image.endsWith(".jpeg")) {
what about `jpeg 2000`? Just kiddin.

2021-05-26 23:35 UTC, yvonnetangsu commented on src/tailwind/plugins/theme/colors.js
> +    "cardinal-red-xdark": "#7A0000",
Apparently we need one more still 😂

2021-05-26 23:35 UTC, yvonnetangsu commented on src/tailwind/plugins/theme/colors.js
> +    "masthead-black": {
I believe this specific one is just for the masthead 😂

2021-05-26 23:36 UTC, yvonnetangsu commented on src/tailwind/plugins/theme/colors.js
> +    "cardinal-red-xdark": "#7A0000",
One more on top of this one I just added lol. It's coming

2021-05-26 23:36 UTC, yvonnetangsu commented on src/utilities/transformImage.js
> +  if (image.endsWith(".jpg") || image.endsWith(".jpeg")) {
lol I remember that

2021-05-26 23:36 UTC, yvonnetangsu commented on src/utilities/transformImage.js
> +  if (image.endsWith(".jpg") || image.endsWith(".jpeg")) {
I found out that if you export a jpg from Figma, they have the .jpeg extension

2021-05-26 23:44 UTC, sherakama requested changes
Overall, this looks really good. I am very surprised to see you use the popover component as the choice here. The menu component seems to be the obvious choice. Can you point to an example where the headless UI uses the popover for a navigation component that is more than a single drop-down? I ask, because looking at the menu component there are a number of things I would expect from a menu component that are not in popover. 

eg: 

Active index https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L89

Keyboard controls:
https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L238

The Aria props you found missing in popover:
https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L219

ScrollTo Focusing:
https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L513


From the Headless UI documentation

> <Menu />. Popovers are more general-purpose than Menus. Menus only support very restricted content and have specific accessibility semantics. Arrow keys also navigate a Menu's items. Menus are best for UI elements that resemble things like the menus you'd find in the title bar of most operating systems. If your floating panel has images or more markup than simple links, use a Popover.

As this component is more of a traditional menu, it would seem that there would be more benefit from using the menu component vs popover even though popover is a completely valid choice.

2021-05-26 23:47 UTC, sherakama commented on src/components/page-types/landingPage.js
> +          </div>
If the logic gets too tricky or brittle in figuring out if the first component is a hero or not, abort the refactor and stick with the hero section for the under the banner look.

2021-05-26 23:50 UTC, yvonnetangsu commented
> Overall, this looks really good. I am very surprised to see you use the popover component as the choice here. The menu component seems to be the obvious choice. Can you point to an example where the headless UI uses the popover for a navigation component that is more than a single drop-down? I ask, because looking at the menu component there are a number of things I would expect from a menu component that are not in popover.
> 
> eg:
> 
> Active index:
> https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L89
> 
> Keyboard controls:
> https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L238
> 
> The Aria props you found missing in popover:
> https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L219
> 
> ScrollTo Focusing:
> https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-react/src/components/menu/menu.tsx#L513
> 
> From the Headless UI documentation
> 
> > . Popovers are more general-purpose than Menus. Menus only support very restricted content and have specific accessibility semantics. Arrow keys also navigate a Menu's items. Menus are best for UI elements that resemble things like the menus you'd find in the title bar of most operating systems. If your floating panel has images or more markup than simple links, use a Popover.
> 
> As this component is more of a traditional menu, it would seem that there would be more benefit from using the menu component vs popover even though popover is a completely valid choice.

@sherakama Yup, here's an example from TailwindUI with a nav component that looks like our main nav:
https://tailwindui.com/components/marketing/elements/headers

I have talked to Jiatyan before about this, she did mention that what's described in WCAG as "menu" is more like "application menu" eg, the tool bar with drop downs in Google docs. The Menu component in HeadlessUI doesn't even support tabbing from one link to the next, and it doesn't allow you to tab out of the dropdown once you open it, which is a pretty big issue.

2021-05-26 23:51 UTC, yvonnetangsu commented
@sherakama  I wish they made one component with all those things combined....

2021-05-26 23:55 UTC, sherakama commented
> The Menu component in HeadlessUI doesn't even support tabbing from one link to the next, and it doesn't allow you to tab out of the dropdown once you open it, which is a pretty big issue.

Ooooof yeah. 

> I wish they made one component with all those things combined...

Yeah, it looks like they split the middle and got the worst of both worlds for primary navigation.

I've been looking for something to replace our vertical nav (sidebar nav) like the one we have on the decanter.stanford.edu website and haven't found much out there that fits the bill. I was looking into possibly using the menu component from headless UI but this might be another rebuild after all. Gak.

2021-05-26 23:56 UTC, yvonnetangsu commented
> > The Menu component in HeadlessUI doesn't even support tabbing from one link to the next, and it doesn't allow you to tab out of the dropdown once you open it, which is a pretty big issue.
> 
> Ooooof yeah.
> 
> > I wish they made one component with all those things combined...
> 
> Yeah, it looks like they split the middle and got the worst of both worlds for primary navigation.
> 
> I've been looking for something to replace our vertical nav (sidebar nav) like the one we have on the decanter.stanford.edu website and haven't found much out there that fits the bill. I was looking into possibly using the menu component from headless UI but this might be another rebuild after all. Gak.

I know! It's a bummer. That's what I was hoping for also 😭

2021-05-27 01:30 UTC, yvonnetangsu commented on src/components/navigation/mainMenuGroup.js
> +            open ? "!su-text-white !su-bg-cardinal-red" : ""
Yeah after working with this for a while, I'm fine with getting rid of the base button styles in Tailwind base. It seems to create more issues rather than being a convenience. When added to the TW base, you can't use dcnb to remove some classes you don't want on the buttons.

2021-05-27 07:47 UTC, yvonnetangsu commented on src/components/identity/logo.js
> +      src="/images/saa-logo-white.svg"
This has been updated with an import from src/image

2021-05-27 07:48 UTC, yvonnetangsu commented on src/components/page-types/landingPage.js
> +          </div>
I think I got this working. Try going to http://app.storyblok.com/#!/me/spaces/103430/stories/0/0/51469208, and remove the hero banner, the fog-light section would not layer underneath the masthead.

2021-05-27 16:33 UTC, sherakama commented on src/components/page-types/landingPage.js
> +          </div>
Ah I see. You have the hero in the general section as a component and use that as your trigger. This seems to be outside of where I would have expected to place the banner. I would have expected to have placed the banner either in above content or main content. Have you talked with Bhavika or Kerri about the UX of having the banner in the general tab?

2021-05-27 16:36 UTC, yvonnetangsu commented on src/components/page-types/landingPage.js
> +          </div>
Sure, let me check with Kerri

2021-05-28 22:43 UTC, sherakama commented on src/components/identity/logo.js
> +import React from "react";
This is a good choice in making this component.

2021-05-28 23:08 UTC, sherakama commented on src/components/page-types/landingPage.js
> +  } = props;
Why is this being destructured outside of the props argument?

2021-05-28 23:13 UTC, sherakama commented on src/components/page-types/landingPage.js
> +          </div>
Let me know what you decide on this when you do and I'll have another pass at the code.

2021-05-29 18:29 UTC, yvonnetangsu commented on src/components/page-types/landingPage.js
> +  } = props;
Hehe..remember we ran into an issue with the interiorPage component when we started destructing props in this repo? I believe it was the Layout/SEO component that is used in all the page types that need the props destructured this way.

2021-05-29 18:31 UTC, yvonnetangsu commented on src/components/page-types/landingPage.js
> +          </div>
I'm going to ask Glynnis to give this to SODA for an a11y check since the HeadlessUI aria implementation is different from our usual approach. If they said it's a no-no, then I'll swap it out, which I can do so fairly easily since we already have all the hooks needed on Giving, and I'm styling the HeadlessUI using TW classes anyway.

2021-05-31 17:29 UTC, sherakama commented on src/components/page-types/landingPage.js
> +  } = props;
Ah right, we should probably revisit our approach to that at some point later.

2021-05-31 17:35 UTC, sherakama approved these changes
Pre-approving as you are going to go and follow up with SODA on this.

2021-06-14 07:44 UTC, yvonnetangsu commented
@sherakama Apologize in advance - I know you have pre-approved this PR for the initial Main Nav work, but I'm adding basic page styling to this branch to speed it up a bit, since I need the masthead to be able to get a realistic preview. Please take a look at the Basic Page styling in the 3 examples in the steps to test.

No need to worry about the Main nav/masthead desktop style finetuning for this - I'll work on those in another PR. Thanks!

2021-06-14 18:36 UTC, sherakama commented
Ok, reviewing.

2021-06-14 20:11 UTC, sherakama commented
@yvonnetangsu All in all this looks ok. I have some questions about the storyblok side primarily. I'll follow up with some comments in the Jira ticket/Slack thread.

2021-06-15 05:11 UTC, sherakama commented
@yvonnetangsu I am going to merge this work in as it is looking good and others will be unblocked by it. We can continue to iterate on the UX of storyblok and open new PRs for changes as they come.

2021-06-15 05:14 UTC, merged

2021-06-15 05:38 UTC, yvonnetangsu commented
> @yvonnetangsu I am going to merge this work in as it is looking good and others will be unblocked by it. We can continue to iterate on the UX of storyblok and open new PRs for changes as they come.

Yay - thank you for reviewing, @sherakama!