ADAPT-2568 Add alignment boolean to Sections component
SU-SWS/saa_alumni pull request #34
Opened 2021-06-03 16:27 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- Add alignment boolean to Sections component

# Review By (Date)
- tbd

# Review Tasks
## Setup tasks and/or behavior to test
1. Check out this branch
2. Review Storyblok config and schema for Section. Confirm that default is center alignment and enabled is left alignment.

# Associated Issues and/or People
- [ADAPT-2568](https://stanfordits.atlassian.net/browse/ADAPT-2568)

2021-06-03 17:02 UTC, sherakama approved these changes
Ok. @yvonnetangsu to review and merge when ready.

2021-06-03 17:48 UTC, yvonnetangsu requested changes
Just that one tiny request, after that GTG 👍🏼

2021-06-03 17:48 UTC, yvonnetangsu commented on src/components/layout/section.js
> +    align,
Working great. I have one tiny nit-picky request. Could we change this boolean prop name to `isLeftAlign`? That would make it clearer in the code, and we've been naming our boolean props this way 😄  After that, GTG! 👏🏼

2021-06-03 17:58 UTC, rebeccahongsf commented on src/components/layout/section.js
> +    align,
No worries! I'm on it! 🏃‍♀️

2021-06-03 18:09 UTC, yvonnetangsu approved these changes
GTG - thank you 🚀

2021-06-03 18:10 UTC, merged

2021-06-04 16:07 UTC, sherakama commented on src/components/layout/section.js
> +    align,
Good call. Thanks.