Search Page Components: ADAPT-2667, ADAPT-2670, ADAPT-2671, ADAPT-2660
SU-SWS/saa_alumni pull request #38
Opened 2021-06-14 16:39 UTC by nplowman

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-06-28 23:54 UTC, sherakama commented
I've begun to review but I cannot get a local build going. Running into a tailwind/postcss/autoprefixer issue

```
 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js):
RangeError: Maximum call stack size exceeded
    at candidatePermutations (/Users/admin/httpdocs/saa_alumni/node_modules/tailwindcss/lib/jit/lib/generateRules.js:37:32)
    at candidatePermutations.next (<anonymous>)
```

Still troubleshooting.

2021-07-05 23:18 UTC, sherakama commented on src/components/components.js
> +import searchResults from './search/searchResults';
```suggestion
import SearchFacet from './search/searchFacet';
import SearchField from './search/searchField';
import SearchPage from './page-types/searchPage';
import SearchPager from './search/searchPager';
import SearchResults from './search/searchResults';
```

2021-07-05 23:19 UTC, sherakama commented on src/components/components.js
> +  searchResults: searchResults,
```suggestion
  searchFacet: SearchFacet,
  searchField: SearchField,
  searchPage: SearchPage,
  searchPager: SearchPager,
  searchResults: SearchResults,
```

2021-07-05 23:21 UTC, sherakama commented on src/components/layout/grid.js
> +  let alignmentClasses = alignment == 'left' ? 'su-justify-items-left' : 'su-justify-items-center';
I think I'd like this to support left/center/right if this is going to be added as an attribute. @yvonnetangsu can you comment on this. Also, is there any reason why we wouldn't support className as a prop for this component?

2021-07-05 23:32 UTC, yvonnetangsu commented on src/components/layout/grid.js
> +  let alignmentClasses = alignment == 'left' ? 'su-justify-items-left' : 'su-justify-items-center';
@sherakama Yes, I agree having left/center/right options would be useful.

2021-07-06 04:21 UTC, sherakama commented on src/components/page-types/searchPage.js
> +  const updateAutocomplete = (query) => {
Please add a few code comments describing each of the functions in this file and what the parameter type is.

2021-07-06 04:55 UTC, sherakama commented on src/components/search/searchResults.js
> +                    __html: result._snippetResult.body.value,
For safety, please sanitize.

2021-07-06 04:57 UTC, sherakama commented on src/components/simple/heading.js
> +      level={headingLevel ?? 2}
```suggestion
      level={parseInt(headingLevel, 10) || 2}
```
Heading wants an integer.

2021-07-06 04:58 UTC, sherakama commented on src/components/simple/linkList.js
> +      <div className="su-font-bold su-text-21 su-mb-32">{blok.title}</div>
Shouldn't this actually be a heading element instead of a div for screen readers?

2021-07-06 05:00 UTC, sherakama commented on src/tailwind/plugins/components/checkbox/custom-checkbox.js
> +        backgroundImage: "url(/images/checked-icon.svg)",
Any way to make this a relative URL instead of assuming top of the domain without it getting exceptionally complicated?

2021-07-06 05:01 UTC, sherakama commented on src/tailwind/plugins/components/checkbox/custom-checkbox.js
> +      ".custom-checkbox[type='checkbox']": {
Does this need the attribute type selector?

2021-07-06 05:03 UTC, sherakama requested changes
@nplowman,

Thanks for this work. It is looking pretty good and functioning well. You've got a lot of other work going on this so I'd like to roll it into the main branch to help keep your other work organized. Please review and revise where the comments were left, address the codeclimate and linting errors, and update the lock file to lockfileVersion 2. For the lock file you should be able to use the version of npm declared in nvm. We can do further UI/UX and Accessibility review later.

2021-07-06 05:47 UTC, yvonnetangsu commented
@nplowman I'll take a more detailed look tomorrow. In the meantime, if you could please add an aria-label to the red search button in the search bar, and add a grid gap between the filter sidebar and the search results, that'd be awesome. Thanks!

2021-07-06 05:48 UTC, yvonnetangsu commented
Agree with what @sherakama said, please don't let my UX review block you - feel free to address those things in another PR and continue from there.

2021-07-06 17:35 UTC, nplowman commented on src/components/layout/grid.js
> +  let alignmentClasses = alignment == 'left' ? 'su-justify-items-left' : 'su-justify-items-center';
Right alignment option has been added to Grid component in Storyblok.
Code has been adjusted to support all three options.

2021-07-06 17:36 UTC, nplowman commented on src/components/search/searchResults.js
> +                    __html: result._snippetResult.body.value,
Completed.

2021-07-06 17:57 UTC, nplowman commented on src/tailwind/plugins/components/checkbox/custom-checkbox.js
> +      ".custom-checkbox[type='checkbox']": {
It looks like the class alone doesn't provide enough specificity to override the default styles, so something else has to be added. 

I could also do `input.custom-checkbox` if that's preferable.

2021-07-06 18:00 UTC, nplowman commented on src/tailwind/plugins/components/checkbox/custom-checkbox.js
> +        backgroundImage: "url(/images/checked-icon.svg)",
I tried a few approaches for this, but this placing the file in the static directory and using this url pattern was the only thing I was able to make work.

I know there are Webpack loaders that can check for url patterns (i.e. like url(~/images/checked-icon.svg) and translate this at build time, but I'm not sure they would work properly given this string is not in a CSS file. 

Using a data URL with a base64 string might work, but I'd need another hour or two work out how to do that in this context. 
e.g. https://css-tricks.com/data-uris/

2021-07-07 03:25 UTC, sherakama commented on src/tailwind/plugins/components/checkbox/custom-checkbox.js
> +        backgroundImage: "url(/images/checked-icon.svg)",
Ok, thanks for looking into it. Those solutions all sound a little less than ideal at this point for this project. Thanks for investigating but we can live with this.

2021-07-07 03:29 UTC, sherakama commented on src/tailwind/plugins/components/checkbox/custom-checkbox.js
> +      ".custom-checkbox[type='checkbox']": {
Yeah, 

We have a ticket for the specificity levels of the form elements and revising their approach here: https://stanfordits.atlassian.net/browse/ADAPT-2856

Ok, thanks for clarifying.

2021-07-07 03:35 UTC, sherakama requested changes
@nplowman,

Thanks for addressing those comments. Please resolve the merge conflicts and linting issues before we merge this.

2021-07-07 16:07 UTC, sherakama approved these changes
GTG

2021-07-07 16:08 UTC, merged