ADAPT-5006 | @rebeccahongsf | notify me r1 qa
SU-SWS/saa_alumni pull request #392
Opened 2022-07-07 21:36 UTC by rebeccahongsf

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2022-07-08 18:58 UTC, yvonnetangsu commented on src/components/page-types/formPage/tripNotifyMe.js
> +            <p className="su-intro-text children:su-leading-snug children:!su-mb-06em children:last:!su-mb-0">
```suggestion
            <p className="su-intro-text su-rs-mb-5">
```
Since this is not a WYSIWYG wrapper anymore, there's no children within the paragraph so removing the classes that we no longer need.

Also, tweaking spacing below the paragraph with spacer 5 😄 
![Screen Shot 2022-07-08 at 11 48 30 AM](https://user-images.githubusercontent.com/42749717/178054122-de37aa0a-669c-44fd-af46-2895698b7cbc.png)

2022-07-08 19:01 UTC, yvonnetangsu commented on src/components/page-types/formPage/tripNotifyMe.js
>              className="su-drop-shadow"
```suggestion
            className="su-text-shadow-lg su-rs-mb-2"
```

Using text shadow utility from decanter instead of the drop shadow filter (though color is still a bit light so we might want to darker this a bit further - but you can Bhavika can sort that out 😄 )
Also, tweaking spacer below H1
![Screen Shot 2022-07-08 at 11 48 45 AM](https://user-images.githubusercontent.com/42749717/178054483-6559ed91-be32-4922-9b8e-fcf5fac8a342.png)

2022-07-08 19:02 UTC, yvonnetangsu commented on src/components/page-types/formPage/tripCustomJourneys.js
> +        <p className="su-intro-text children:su-leading-snug children:!su-mb-06em children:last:!su-mb-0">
```suggestion
        <p className="su-intro-text su-rs-mb-5">
```
Same treatment as the other one

2022-07-08 19:05 UTC, yvonnetangsu commented
This looks great! Just a few minor suggestions, and on the Storyblok side, let's make these into textarea fields so the UX is a little nicer (there will be no need to change anything in code which is nice when you switch a field from text to text area 😄 )
![Screen Shot 2022-07-08 at 11 45 59 AM](https://user-images.githubusercontent.com/42749717/178054802-4b6de873-f387-4ec1-8525-62d186064c5b.png)

Also, this might be something to talk about with Bhavika. On mobile, these white text might not meet a11y so perhaps we need to darken the gradient a bit on mobile?
![Screen Shot 2022-07-08 at 11 25 51 AM](https://user-images.githubusercontent.com/42749717/178055010-f0a29fcb-ace9-4e66-a868-d68bba5c0acd.png)

2022-07-08 19:06 UTC, yvonnetangsu requested changes
Looking awesome 🔥  - left a few comments about minor things

2022-07-12 21:42 UTC, yvonnetangsu commented
@rebeccahongsf Want me to go ahead and approve this, or wait till you push up the small changes we discussed yesterday (remove stacking spacing on mobile) 😄 Happy to approve this first if that's easier.

2022-07-12 22:31 UTC, rebeccahongsf commented
Aw thanks for checking in @yvonnetangsu 😄 I would like to wait until I push up the spacing and mobile gradient fix then have you re-review 😎  I should have this all ready for review by tomorrow morning since Bhavika and I are going to go over the mobile gradient in a bit!

2022-07-12 22:32 UTC, yvonnetangsu commented
> Aw thanks for checking in @yvonnetangsu 😄 I would like to wait until I push up the spacing and mobile gradient fix then have you re-review 😎 I should have this all ready for review by tomorrow morning since Bhavika and I are going to go over the mobile gradient in a bit!

Oh awesome. Thanks, @rebeccahongsf. There is no rush at all 😎

2022-07-15 17:18 UTC, yvonnetangsu approved these changes
Thank you for the updates - looks awesome and GTG, @rebeccahongsf 🚀 🌟 😄 !

I took a quick look at the Custom Journey form page. Looks like it pretty much uses the same layout so please make the same adjustments you have here on that as well 😄

2022-07-15 17:51 UTC, rebeccahongsf commented
Duly noted! Thank you so much @yvonnetangsu 😄  I'm going to merge this PR in and implement the custom journey + GG form grid span fixes in a new PR for ADAPT-5108

2022-07-15 17:51 UTC, merged

2022-07-15 18:00 UTC, yvonnetangsu commented
> Duly noted! Thank you so much @yvonnetangsu 😄 I'm going to merge this PR in and implement the custom journey + GG form grid span fixes in a new PR for [ADAPT-5108](https://stanfordits.atlassian.net/browse/ADAPT-5108)

That sounds great @rebeccahongsf ! Are you going to open another PR for the Hero refactor as well? LMK if you have any other questions about that 😸