ADAPT-5192: Utility nav rework
SU-SWS/saa_alumni pull request #422
Opened 2022-08-05 16:24 UTC by Lyafel

# Summary
- Reworked the utility menu

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2022-08-16 23:17 UTC, sherakama commented
![Screen Shot 2022-08-16 at 4 16 49 PM](https://user-images.githubusercontent.com/550602/185001240-e3a545e8-f0a9-4fa8-b8f7-85b3bc50b441.png)

@Lyafel I updated this branch with the latest from dev and it looks like that has caused some weirdness. Can you have a look please?

2022-08-16 23:57 UTC, sherakama commented
![Screen Shot 2022-08-16 at 4 56 21 PM](https://user-images.githubusercontent.com/550602/185005018-4649fdc5-058e-4d04-8978-81eb57ab9e69.png)

Loading spinner is a bit odd on mobile.

2022-08-20 00:08 UTC, sherakama commented
@Lyafel this is looking great. @yvonnetangsu please have a review when you get a chance next week.

2022-08-22 17:14 UTC, yvonnetangsu commented
@Lyafel It seems like the menu items are still a bit strange on LG break point when logged out. If you could please tweak this, that'd be great. Thanks!
![Screen Shot 2022-08-22 at 10 08 47 AM](https://user-images.githubusercontent.com/42749717/185979480-9e854c33-0e5f-4d9f-9b4a-dae02f42ab14.png)

This is what it looks like on production
![Screen Shot 2022-08-22 at 10 11 39 AM](https://user-images.githubusercontent.com/42749717/185980126-eb88403a-c83b-42a3-8f69-5a77bc032b95.png)

2022-08-22 17:21 UTC, yvonnetangsu commented
@Lyafel Also, after logged in, on mobile/MD, the user menu items currently look like this on the preview (underline is visible no matter hovered/focused or not). 
![Screen Shot 2022-08-22 at 10 19 39 AM](https://user-images.githubusercontent.com/42749717/185981494-a5802d6e-03bd-47e9-80f5-54b0d6156bf6.png)

2022-08-23 22:00 UTC, Lyafel commented
> @Lyafel Also, after logged in, on mobile/MD, the user menu items currently look like this on the preview (underline is visible no matter hovered/focused or not). ![Screen Shot 2022-08-22 at 10 19 39 AM](https://user-images.githubusercontent.com/42749717/185981494-a5802d6e-03bd-47e9-80f5-54b0d6156bf6.png)

@yvonnetangsu Fixed  :)

2022-08-31 16:01 UTC, sherakama commented
@Lyafel The last build failed. Please revise.

2022-08-31 21:44 UTC, Lyafel commented
@sherakama fixed

2022-09-02 16:37 UTC, sherakama approved these changes
Looking good to me.

2022-09-02 22:08 UTC, jdwjdwjdw commented
I caught an extra `li` list-style while signed in during my review, everything looked great other than that. I also resolved the merge conflict.

<img width="911" alt="Screen Shot 2022-09-02 at 2 37 02 PM" src="https://user-images.githubusercontent.com/49299083/188241065-e9122eb5-b20b-4127-a2d0-07d62867ef04.png">

2022-09-02 22:45 UTC, jdwjdwjdw commented
Also added a border-top to the user menu to match figma, and corrected the border-top on the hamburger menu to match the color of the other menu items. Should be good now as far as I can tell!

User menu Before:
![Screen Shot 2022-09-02 at 3 33 38 PM](https://user-images.githubusercontent.com/49299083/188243580-c9bc3f68-7032-4e2b-9bb2-c318947eef69.png)

User menu After:
![Screen Shot 2022-09-02 at 3 33 59 PM](https://user-images.githubusercontent.com/49299083/188243599-c6fd37d9-ab44-4fb8-9a36-1bd68468bbab.png)

Hamburger Menu Before:
![Screen Shot 2022-09-02 at 3 31 54 PM](https://user-images.githubusercontent.com/49299083/188243479-db9f8960-bc26-4f92-a82b-3e6ca1f7b154.png)

Hamburger Menu After:
![Screen Shot 2022-09-02 at 3 34 18 PM](https://user-images.githubusercontent.com/49299083/188243501-83e899fe-9a25-4e42-8b5e-f92501c6e187.png)

2022-09-03 23:54 UTC, sherakama commented
Nice, thanks @jdwjdwjdw. @yvonnetangsu for final 👍

2022-09-04 05:04 UTC, yvonnetangsu commented
> @yvonnetangsu can you confirm this is working as expected?

Sorry I totally missed this ping @sherakama. Thank you for the updates, @jdwjdwjdw - those look great. I'm going to push up a few tweaks - after that this should be GTG 😄

2022-09-04 05:50 UTC, yvonnetangsu commented
It looks like we don't have a mock for this new menu for the TS site. This PR introduces some red to the menu - I think it's probably not a huge issue, but don't know if we need to let the TS clients know about this change before we cut a release 😬 

FYI, this is the most updated mock for the TS nav that we decided to use I believe, and that's what it looks like on production (there seems to be some minor positioning issue with the drop down menu on mobile at the moment though)
![Screen Shot 2022-09-03 at 10 44 59 PM](https://user-images.githubusercontent.com/42749717/188299464-c1825041-2630-4672-a588-2e9442f54c2c.png)

And this is what it looks like in this PR - which I think is not a big deal but it does add the red colors
![Screen Shot 2022-09-03 at 10 45 49 PM](https://user-images.githubusercontent.com/42749717/188299491-cc0936e3-0fbe-45c4-96a7-828887ce8674.png)

![Screen Shot 2022-09-03 at 10 45 37 PM](https://user-images.githubusercontent.com/42749717/188299494-151d2265-c940-4e63-bf09-ade71e95044e.png)

2022-09-06 17:21 UTC, yvonnetangsu commented
@jdwjdwjdw I pushed up a few styling/a11y tweaks, and found another a11y issue that perhaps you could help us investigate 😄 Thanks in advance!

On mobile, after one opens up the user menu (authenticated or not) modal, the keyboard focus is not trapped within the modal, ie, if I hit the tab key while the user menu modal is open, I can tab to the content outside of the modal even if the modal is still open.

The Modal component should already have a useFocusTrap hook to trap focus, and this works for the search, main nav, trip filter modals. It's just not working in the user menu modal currently. One possibility is that the conditional rendering of the content inside the user menu is causing this to not work.

2022-09-06 20:29 UTC, jdwjdwjdw commented
@yvonnetangsu I'll look into it more! It does appear to work for me while logged out though, which may help with our troubleshooting

2022-09-06 22:24 UTC, yvonnetangsu commented
> @yvonnetangsu I'll look into it more! It does appear to work for me while logged out though, which may help with our troubleshooting

Thank you so much @jdwjdwjdw !! ⭐ 😄

2022-09-07 20:46 UTC, jdwjdwjdw commented
@yvonnetangsu per our in-person discussion, I removed the conditional which was breaking the user menu useFocusTrap. This doesn't appear to negatively anything else, as far as I can tell.

2022-09-07 20:49 UTC, yvonnetangsu commented
> @yvonnetangsu per our in-person discussion, I removed the conditional which was breaking the user menu useFocusTrap. This doesn't appear to negatively affect anything else, as far as I can tell.

Thank you for investigating @jdwjdwjdw! 😄  Nice job. I'm going to do a deeper review later today, and do a final sweep. If nothing goes wrong, then we might be good to go.

2022-09-07 21:54 UTC, yvonnetangsu commented on src/components/navigation/MainNav/mainNav.jsx
> +      </nav>
I was inspecting the code and wondering why we have a `<nav className="main-nav-mobile lg:su-hidden" aria-label="Main Menu">` nested inside another one with same attributes here 😄 @jdwjdwjdw If you could please help us check whether we can get rid of one layer of the nav nesting, that'd be awesome.

2022-09-07 22:26 UTC, jdwjdwjdw commented on src/components/navigation/MainNav/mainNav.jsx
> +      </nav>
Strange! I removed that and fixed the console warning we were seeing as well.

2022-09-07 22:31 UTC, yvonnetangsu commented on src/components/navigation/MainNav/mainNav.jsx
> +      </nav>
Even better 😄

2022-09-13 23:47 UTC, yvonnetangsu commented on src/components/navigation/MainNav/mainNav.jsx
> +      </nav>
@jdwjdwjdw I hide the greeting completely (changed from su-sr-only to su-hidden) on mobile so now the focus outline for the circle with initial isn't jagged anymore 😄 No reason to make the greeting available to screen readers because it's not visible, and we have an aria label already

2022-09-13 23:49 UTC, yvonnetangsu commented
@sherakama If you could please take a final look tomorrow that'd be awesome. Both @jdwjdwjdw and I have made a bunch of changes so having a 3rd person look at it would make me feel better. Please check the nav on both homesite and T/S 🙇🏼‍♀️

2022-09-14 16:15 UTC, yvonnetangsu commented
@jdwjdwjdw found another bug on the mobile main menu 😬 , so merging will need to wait @sherakama

2022-09-14 16:17 UTC, sherakama approved these changes
+1 to the bug Yvonne found but otherwise this is GTG.

2022-09-14 16:21 UTC, yvonnetangsu commented
> +1 to the bug Yvonne found but otherwise this is GTG.

@jdwjdwjdw found it! <-- Thank you Jacob 😄

2022-09-19 17:22 UTC, yvonnetangsu commented
@jdwjdwjdw Got a couple tiny style tweak request from Bhavika 😄 

1. For mobile user menu (both homesite and T/S), in the logged out state, when the modal is open, could we add the thin red line between the menu header and the "log in" link so it matches the logged in state?

2. Could we nudge the "x" button a tiny bit to the right so it lines up with the arrow icon in the menu links?

Thank you @jdwjdwjdw !

2022-09-20 00:40 UTC, jdwjdwjdw commented
Thanks @yvonnetangsu! I added that line, and (per our zoom discussion) adjusted the arrow instead of the "x"button.

Still troubleshooting the issue with tabbing over to the last parent item in the mobile main menu, appears to be related to that useFocusTrap hook.

2022-10-27 22:17 UTC, sherakama commented
@jdwjdwjdw did you resolve the tabbing issues?

2022-10-31 16:19 UTC, jdwjdwjdw commented
> @jdwjdwjdw did you resolve the tabbing issues?

Not yet - but it appears the problem area is related to the focus trap and getLastTabbableItem on line 19 of https://github.com/SU-SWS/saa_alumni/blob/dev/src/components/layout/Modal/Modal.jsx. While troubleshooting I noticed it's actually a lot worse on firefox than Chrome (see https://deploy-preview-422--stanford-alumni.netlify.app/ to compare) - on Chrome only the last dropdown can't be tabbed through, but on Firefox I'm seeing that strangeness for all the dropdowns.

2022-10-31 16:22 UTC, sherakama commented
> Not yet - but it appears the problem area is related to the focus trap and getLastTabbableItem

@jdwjdwjdw, aye, and when we troubleshooted it together we found out that getLastTabbableItem doesn't recursively look for the last item and that you would need to change that out for something else. Please have a look into it this week if you can.

2023-02-03 20:43 UTC, Lyafel commented
@jdwjdwjdw @sherakama @yvonnetangsu Please check my latest changes fixing the tabbing issue

2023-02-08 17:43 UTC, Lyafel commented
@sherakama Forgot that TS has a separate menu, tabbing should be fixed now

2023-02-08 21:38 UTC, sherakama requested changes
This needs to be re-worked into the `Phase 2` version of the utility nav.

2023-02-14 18:22 UTC, Lyafel commented
@sherakama Pulled the phase2 changers into this pr

2023-02-14 20:37 UTC, yvonnetangsu commented
@Lyafel I'm updating this in a different repo. If you could hold off for a little bit, I'll share the style code with you later today 😄

2023-02-14 21:34 UTC, yvonnetangsu commented
@Lyafel Here's the link to my PR for the user menu update from another repo. You could probably reuse a lot of the Tailwind styles for things inside the user menu 🤞🏼 
https://github.com/SU-SWS/adapt-my-account/pull/679

2023-02-15 20:32 UTC, Lyafel commented
@yvonnetangsu Ready for review. I changed the styling to hopefully match, also had to shuffle the structure a bit because there were cases of stray li not being part of any uls on mobile

2023-02-16 20:52 UTC, yvonnetangsu commented
> @yvonnetangsu Ready for review. I changed the styling to hopefully match, also had to shuffle the structure a bit because there were cases of stray li not being part of any uls on mobile

@Lyafel This is looking great - thanks 😄 ! A couple more small changes, for the rest, I have a 1 on 1 with Kerri tomorrow so I'll do a visual QA with her. I'm a bit out of the loop with the changes in this repo so want to double check with her, but these are the ones I'm certain about:

- Please change the hocus color of these links to white inside the user menu
![Screen Shot 2023-02-16 at 12 49 00 PM](https://user-images.githubusercontent.com/42749717/219483795-88a5fb87-2209-497a-ac0b-a1cbb58d0b23.png)

- Kerri would like to get rid of the down chevrons on all breakpoints next to the avatar circle
![Screen Shot 2023-02-16 at 12 47 14 PM](https://user-images.githubusercontent.com/42749717/219483909-70af2013-c454-4966-9a18-9474feb57f77.png)

![Screen Shot 2023-02-16 at 12 51 02 PM](https://user-images.githubusercontent.com/42749717/219483950-6d1756fb-ac4c-4068-9dba-7e459e49a8e2.png)

Thanks!!

2023-02-17 22:34 UTC, yvonnetangsu requested changes
Hi @Lyafel I had a 1:1 with Kerri so was able to confirm with her a few things. I might have some smaller detail request for later, but for now, if you could please do these 3 first, that'd be great 🙏🏼 Thanks!

- [ ] Make the user menu on the Travel/Study site exactly the same as the one on the homesite (should have dark red background). Currently (below screenshot) it looks like it has the black color theme inherited from the main menu (which looks nice 😄  but apparently for the user menu, we need them to have the same color and style across all the sites in the ecosystem)
![Screen Shot 2023-02-17 at 2 26 17 PM](https://user-images.githubusercontent.com/42749717/219806351-e614fe21-48c9-4e15-b25c-588f074313da.png)

- [ ] Please change the "View profile | Edit" link to hover/focus to white
- [x] Kerri likes the horizontal padding on the mobile user menu items (below), and we agree that for mobile main nav on the Alumni and Travel Study site, they should have the same mobile padding as the user menu items. No change for desktop needed. 

Below horizontal padding is what Kerri wants 😄 (for main menu on mobile)
![Screen Shot 2023-02-17 at 2 32 20 PM](https://user-images.githubusercontent.com/42749717/219808073-11a18441-79c6-4432-bfa9-478990b29038.png)

2023-02-21 17:58 UTC, yvonnetangsu commented on src/components/navigation/MainNav/SAAMainMenuGroup.jsx
> +  );
This useEffect looks a little bit strange to me. Does it need both of the `() =>`? 😄

2023-02-22 20:57 UTC, Lyafel commented
@yvonnetangsu All items taken care of, please check :)

2023-02-23 01:02 UTC, yvonnetangsu commented
@Lyafel We're getting closer and closer! 😄 Thank you for this last round of updates.

- [ ] For the horizontal padding on the menu item, I meant to say that Kerri likes the `su-px-26` like on the original mobile user menu items (My Account link, My Giving link etc), and would like to apply that for the mobile main menu items (XS to MD breakpoint). I believe the way you have it currently is the other way around.
- [ ] It looks like the focus traps on the user menu (both on the homepage and the travel study site) aren't working at the moment. Main menu ok however 👍🏼 

Thank you!

2023-02-23 01:03 UTC, yvonnetangsu commented on src/components/navigation/MainNav/mainMenuGroup.jsx
> +  );
I think this one needs a tweak as well (remove one set of () =>) 😄

2023-02-24 19:31 UTC, Lyafel commented
@yvonnetangsu Fixed. Looks like the focus trap code doesn't work well if the links are added conditionally, seems to be something to do with the compared instances being different even if they seem to be the same. Had to shuffle some things around to take the utility menu out of the breakpoint conditionals.

2023-02-28 19:10 UTC, yvonnetangsu commented
> @yvonnetangsu Fixed. Looks like the focus trap code doesn't work well if the links are added conditionally, seems to be something to do with the compared instances being different even if they seem to be the same. Had to shuffle some things around to take the utility menu out of the breakpoint conditionals.

@Lyafel Thank you so much. This is so close. We're going to have meeting to talk about what exactly goes into the user menu tomorrow (looks like we're not getting the conditionals for "donor" affiliation before launch). Will update you once we have a decision.

2023-03-02 21:22 UTC, Lyafel commented on src/components/navigation/MainNav/userNavItems.jsx
> +          </li>
> Thanks for the affiliation update, @Lyafel ! We heard back about this "My Giving" link - we're hiding it for now because we won't be getting the "donor" affiliation and logic before launch. If you could please remove or comment this link out, that'd be great 👍🏼

Done

2023-03-13 20:03 UTC, yvonnetangsu commented on src/components/navigation/userHeaderIcon.js
> +              />
@Lyafel I believe we also need to support displaying the user image (as the button that opens up the user menu and inside the user menu) when there is one 🤔 

@sherakama Are we pulling the `profilePhotoURL` from the `contact` endpoint like on MyAccount/Directory?
![Screen Shot 2023-03-13 at 1 01 05 PM](https://user-images.githubusercontent.com/42749717/224819003-76755770-5374-4b5c-9c93-1fa5bc63a2b5.png)

2023-03-13 20:14 UTC, sherakama commented on src/components/navigation/userHeaderIcon.js
> +              />
Yes, we should support the profile image from this URL. The asset on the end of that URL is a protected URL so you will need to handle the secure fetching. You should be able to port over the work here: https://github.com/SU-SWS/adapt-directory/tree/dev/src/components/PrivateImage

2023-03-13 20:15 UTC, sherakama commented on src/components/navigation/userHeaderIcon.js
> +              />
https://github.com/SU-SWS/adapt-directory/tree/dev/src/services/asset

2023-03-13 20:15 UTC, sherakama commented on src/components/navigation/userHeaderIcon.js
> +              />
https://github.com/SU-SWS/adapt-directory/blob/dev/src/pages/api/assets/index.ts

2023-03-13 20:16 UTC, sherakama commented on src/components/navigation/userHeaderIcon.js
> +              />
You can/should use the same keys from vault as the directory. Copy them over to the alumni project.

2023-03-13 21:29 UTC, yvonnetangsu commented
@Lyafel Just noticed something with our modals. Could you please check if this is a visual regression introduced by any modal changes in this PR? These non-fullscreen modals appear to be sticking to the top of the browser 😅 

![Screen Shot 2023-03-13 at 2 28 21 PM](https://user-images.githubusercontent.com/42749717/224836576-fcad8893-f643-46b6-a7b5-6823b6374c70.png)

2023-03-13 22:10 UTC, yvonnetangsu commented
@Lyafel Just noticed there are 2 navs with the same aria label for mobile - I believe the "user menu" somehow isn't taking on the correct aria-label here
![Screen Shot 2023-03-13 at 12 49 28 PM](https://user-images.githubusercontent.com/42749717/224843247-66fb866e-cdc9-4d68-b6a0-72fed3168919.png)

2023-03-13 22:14 UTC, yvonnetangsu commented on src/components/navigation/MainNav/mainNav.jsx
> +      <nav className="main-nav-mobile lg:su-hidden" aria-label="Main Menu">
```suggestion
      <nav className="main-nav-mobile lg:su-hidden" aria-label="User Menu">
```

2023-03-13 22:19 UTC, yvonnetangsu commented on src/components/navigation/MainNav/mainNav.jsx
> +      </nav>
@Lyafel I'm looking at this structure some more, actually, for mobile, I'd prefer for the `nav` element to wrap around the menu content itself rather than the buttons that open them (for both Main and User menus). Thanks!

2023-03-13 22:20 UTC, yvonnetangsu commented on src/components/navigation/MainNav/mainNav.jsx
> +      <nav className="main-nav-mobile lg:su-hidden" aria-label="Main Menu">
Please move these nav wrappers inside the Modals so that they're wrapping around the menu content instead 😄 @Lyafel

2023-03-13 23:39 UTC, yvonnetangsu commented on src/components/navigation/userHeaderIcon.js
> +              )}
@Lyafel Do we need this block here? I commented it out and it doesn't seem to change anything as the greeting is already in `accountLinks`? 🤔

2023-03-14 05:47 UTC, yvonnetangsu commented on src/components/navigation/userHeaderIcon.js
> +              )}
I went ahead and remove this block. Please let me know if we need it for anything.

2023-03-14 06:57 UTC, yvonnetangsu commented on src/components/navigation/MainNav/mainNav.jsx
> +      </nav>
I've pushed up a few commits and this has been fixed. Resolving this comment.

2023-03-14 07:02 UTC, yvonnetangsu commented on src/components/simple/heroIcon.js
> +      baseStyle: 'su-w-08em su-ml-03em su--mt-02em',
@jdwjdwjdw I had to revert this change, because it makes the positioning of this right arrow strange in a few places - Travel Study trip cards, CTAs etc. For example, 
![Screen Shot 2023-03-13 at 11 27 31 PM](https://user-images.githubusercontent.com/42749717/224920993-f1a56d1a-8b81-4227-8828-4d3b19c0f7a3.png)

Is there a reason that you changed from `su--mt-02em` to `su-mt-02em` earlier? I want to makes sure I didn't break anything you did? 😄

2023-03-14 07:30 UTC, yvonnetangsu commented
@Lyafel I pushed up a bunch of commits. Please pull down the latest changes before you start working on the avatar image - thanks! 😄

2023-03-16 05:36 UTC, sherakama commented
@Lyafel & @yvonnetangsu 

Private image service and component has been pushed up to this branch. I've sort of just patched in the new `<PrivateImage />` component to where the initial was before. Please pick it up from here and make it look wonderful.

2023-03-16 05:42 UTC, sherakama commented
Oh, one thing @yvonnetangsu and @Lyafel,

I am going to have to request access to the contact endpoint for the dev megaprofile client id as it doesn't seem to have it. I'm pretty sure production does/will. You can use the POSTMAN keys for your local test.

2023-03-20 20:15 UTC, Lyafel commented
> @Lyafel Happy Monday! How's this going? Is it ready for another review? 😄

Happy Monday :) it's ready thought I can't figure out why does the user have no image coming from the user
It looks like zguan has no image, though there was one when I'd log in on my account. Are they not the same user?

<img width="493" alt="Screen Shot 2023-03-20 at 2 12 07 PM" src="https://user-images.githubusercontent.com/2143944/226455209-87cfda7c-5e18-43b7-b239-03eda9775f02.png">

2023-03-20 21:46 UTC, Lyafel commented
@yvonnetangsu Can see the image now, yay! give me a few, I'll fix one small issue

2023-03-20 21:47 UTC, yvonnetangsu commented
@sherakama Tagging you to double check. Looks like @Lyafel was able to pull in other pieces of data from the contact endpoint probably just the missing profile image due it not uploaded when she looked?

2023-03-20 22:04 UTC, yvonnetangsu commented on src/components/navigation/MainNav/userNavItems.jsx
> +          <Initial />
@Lyafel Is this temporary? Just wondering why the change bak to `<Initial />` only here 😄

2023-03-20 22:09 UTC, Lyafel commented on src/components/navigation/MainNav/userNavItems.jsx
> +          <Initial />
Not that you're asking realized the component name doesn't make sense :) I renamed it, there check happens inside that component so it doesn't need to be checked in 2 places

2023-03-20 22:12 UTC, yvonnetangsu commented on src/components/navigation/MainNav/userNavItems.jsx
> +          <Initial />
Ahh I see - thank you @Lyafel 💯 !

2023-03-21 01:52 UTC, yvonnetangsu commented
@sherakama I pushed a few more tweaks after @Lyafel did the work to add the image. I believe I've tested thoroughly, but I would like to ask you to help me double check this 🙏🏼 😄 

1. Check log out state (desktop/mobile)
![Screen Shot 2023-03-20 at 6 46 34 PM](https://user-images.githubusercontent.com/42749717/226501025-3ac832e5-bf31-42c4-a8c7-fda7b3656d07.png)
![Screen Shot 2023-03-20 at 6 46 18 PM](https://user-images.githubusercontent.com/42749717/226501038-cccd1a5c-935b-4a0a-a740-1df08d2085ce.png)
![Screen Shot 2023-03-20 at 6 46 23 PM](https://user-images.githubusercontent.com/42749717/226501047-f912a783-311c-47ac-9fb1-dc93657279e8.png)

2. Check logged in state (no image uploaded to UAT)
![Screen Shot 2023-03-20 at 6 44 51 PM](https://user-images.githubusercontent.com/42749717/226501082-165d24e7-cf87-49f2-86be-f51b715347ba.png)
![Screen Shot 2023-03-20 at 6 45 05 PM](https://user-images.githubusercontent.com/42749717/226501096-4ba97aa8-3e1d-4df6-8412-6790362c356b.png)
![Screen Shot 2023-03-20 at 6 45 11 PM](https://user-images.githubusercontent.com/42749717/226501103-8911b6e0-f6c8-451d-aff2-59b004d25b12.png)

3. Check logged in state (has image uploaded to UAT)
![Screen Shot 2023-03-20 at 6 37 15 PM](https://user-images.githubusercontent.com/42749717/226501146-1e09a958-2a29-4177-923b-ef3d3b0728d9.png)
![Screen Shot 2023-03-20 at 6 36 56 PM](https://user-images.githubusercontent.com/42749717/226501153-eb0acd94-1b1f-483a-9ecc-9de662d8bc95.png)
![Screen Shot 2023-03-20 at 6 39 19 PM](https://user-images.githubusercontent.com/42749717/226501167-317abd12-73d5-4c39-afdf-5c1debc89f2d.png)

4. Test all the things in the masthead (menus, modals etc) - resize slowly

5. Please repeat for Travel/Study

Thank you!

2023-03-25 22:03 UTC, sherakama approved these changes
GTG

2023-03-25 22:03 UTC, merged