ADAPT-5355 and ADAPT-5360s series | @rebeccahongsf |  bulk tsgg updates
SU-SWS/saa_alumni pull request #458
Opened 2022-09-07 00:40 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
[Batches requested fixes from TSGG](https://docs.google.com/spreadsheets/d/1pCukzFMRrFqoeMzej08lKv_FKgbcu-umrTOK8ss7mxI/edit#gid=1871597942)
- Open Reserve form link in new tab (no additional changes to SB needed)
- Update Added Travelers empty state text on interstitial page
- Remove `Trip: Registration` header from registration form
- Increase "Add Traveler" link on GG registration form payment page
- Resolve cancellation policy anchor link over-scroll
- Update "Explore More Destinations" from title casing to sentence casing ("Explore more destinations") on Notify me confirmation page

# Review By (Date)
- Sooner the better please! Thank you 🙏 

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to `travel-study/destinations/italy-test`
3. Verify that upon clicking "Reserve", the registration form opens in a new window/tab
4. On the interstitial page, confirm that the text for Added Travelers has been updated to "You haven't yet added any existing connections"
5. Continue onward to the registration form
- Confirm that the additional header "Trip: Registration" no longer appears between the hero and form
6. On the payment summary, 
- Confirm that the font of "Add traveler" is using `su-big-paragraph`
- Open the Cancellation policy link and confirm that it directs user to the deposit section of trip.
7. Navigate to `travel-study/destinations/italy-test/notify`
8. Submit the form.
9. Confirm that the onscreen confirmation displays the proper casing for "Explore more destinations" button
10. Review code to see if anything looks questionable

# Associated Issues and/or People
- ADAPT-5355
- ADAPT-5360
- ADAPT-5361
- ADAPT-5362
- ADAPT-5363
- ADAPT-5364
- ADAPT-5365

2022-09-07 15:23 UTC, rebeccahongsf commented on src/components/page-types/TripPage/TripPageOverviewSection.jsx
> +                  }}
Currently investigating why `location.origin` returns undefined when deployed on Netlify 🤔

2022-09-07 21:12 UTC, yvonnetangsu commented
@rebeccahongsf I have reviewed all the things except the issue you're investigating - those all checked out! 👍🏼 ⭐

2022-09-07 21:16 UTC, yvonnetangsu commented on src/components/page-types/TripPage/TripPageSectionNav.jsx
> +            rel="noopener nofollower"
Is there a reason to add "noopener nofollow" to an internal link? 👀 Btw, looks like there's a typo - no "er" 😄

2022-09-07 21:17 UTC, yvonnetangsu commented on src/components/page-types/TripPage/TripPageOverviewSection.jsx
> +                  rel="noopener nofollower"
Same for this one 😄

2022-09-07 21:45 UTC, sherakama commented on src/components/page-types/TripPage/TripPageOverviewSection.jsx
> +                  }}
Why do you need `location.origin` here?

2022-09-07 21:52 UTC, sherakama requested changes
Ideally, we would keep the internal link and open a new window. Please also look at the typo that @yvonnetangsu found.

2022-09-07 23:10 UTC, rebeccahongsf commented on src/components/page-types/TripPage/TripPageOverviewSection.jsx
> +                  }}
If I pass in `link = {{ url: reservationURL?.cached_url}}` the a tag href is set to 
https://deploy-preview-458--stanford-alumni.netlify.app/travel-study/destinations/italy-test/travel-study/destinations/italy-test/register

If I pass in `link = {reservationURL}`, the link opens in the same window ([see current deploy preview](https://deploy-preview-458--stanford-alumni.netlify.app/travel-study/destinations/italy-test/register))

I figured if we are able to construct the absolute URL path, it would open correctly in a new window but I'm open to other approaches as well!

2022-09-08 19:24 UTC, sherakama commented
This thread suggests that you should be able to use target blank but in the preview build it definitely is being overridden https://github.com/gatsbyjs/gatsby/issues/13825

Perhaps swap out the component for a custom one and just use the <a> tag instead of the link as you are not getting any benefit from using the gatsby-link component with _blank. In fact, you're using up extra bandwidth and prefetching a page that you'll be asking the user to render in a new window anyhow.

2022-09-14 16:10 UTC, sherakama approved these changes
Looking good!

2022-09-14 21:34 UTC, yvonnetangsu commented
😺 😸 😸 
![Screen Shot 2022-09-14 at 2 34 20 PM](https://user-images.githubusercontent.com/42749717/190266816-170d7c54-8911-4631-ad34-6d3bf21e1e3f.png)

2022-09-14 21:40 UTC, yvonnetangsu commented
FYI @rebeccahongsf there's a 3rd reserve link (but it's manually added by the user) in the poster near the bottom as well. The client requested that be part of the preset so it will likely be a common thing (unless things have changed). Just want to give you a heads up in case anything needs to be done with that as well 😄 
![Screen Shot 2022-09-14 at 2 36 51 PM](https://user-images.githubusercontent.com/42749717/190267465-163cf2cb-0413-4341-bd32-6166736afcfa.png)

Another heads up - I see the test form pages are using the Homesite masthead, I think it just need to be swapped out with the T/S masthead?

2022-09-14 21:40 UTC, sherakama commented
> 😺 😸 😸 ![Screen Shot 2022-09-14 at 2 34 20 PM](https://user-images.githubusercontent.com/42749717/190266816-170d7c54-8911-4631-ad34-6d3bf21e1e3f.png)

LOL!

2022-09-14 21:49 UTC, yvonnetangsu commented
Reserve button in section nav seems to have changed from live 👀 😄 
This PR
![Screen Shot 2022-09-14 at 2 48 18 PM](https://user-images.githubusercontent.com/42749717/190269112-3ef0d136-df5e-40d3-b82d-42937e1f9c97.png)

Live
![Screen Shot 2022-09-14 at 2 48 52 PM](https://user-images.githubusercontent.com/42749717/190269130-3a219dea-76de-4385-bfb4-13a5710148b1.png)

2022-09-15 17:39 UTC, rebeccahongsf commented
@yvonnetangsu thank you for the speedy review! I updated the mobile button style 😃 

Would you also be able to confirm that in the event that an external link is provided, the user is properly direct to the external link (since we still want to support the existing trip registration on PGnet).

[You can test it with this copy I made of the Italy test (/travel-study/destinations/italy-test/italy-ext-test)](https://deploy-preview-458--stanford-alumni.netlify.app/travel-study/destinations/italy-test/italy-ext-test/)

2022-09-15 17:46 UTC, yvonnetangsu commented
> @yvonnetangsu thank you for the speedy review! I updated the mobile button style 😃
> 
> Would you also be able to confirm that in the event that an external link is provided, the user is properly direct to the external link (since we still want to support the existing trip registration on PGnet).
> 
> [You can test it with this copy I made of the Italy test (/travel-study/destinations/italy-test/italy-ext-test)](https://deploy-preview-458--stanford-alumni.netlify.app/travel-study/destinations/italy-test/italy-ext-test/)

Yup that work!! 💯 😄

2022-09-15 17:55 UTC, yvonnetangsu approved these changes
Thank you for all the changes, @rebeccahongsf ! All working/looking great 😄 👍🏼

2022-09-19 16:18 UTC, merged