ADAPT-2735 Build Simple Image component
SU-SWS/saa_alumni pull request #46
Opened 2021-06-21 16:48 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- Build Simple Image component

# Review By (Date)
- tbd

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Run local dev and review the Simple Image component at `/rebecca/simple-image-test` or Netlify preview 

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- [ADAPT-2735](https://stanfordits.atlassian.net/browse/ADAPT-2735)

2021-06-22 16:56 UTC, sherakama commented on src/components/media/simpleImage.js
> +    <WidthBox width={imageWidth}>
This looks and functions well, I just wonder about the HTML element and changing it to figure so we can use figcaption with the caption. @yvonnetangsu thoughts, and perhaps a quick SODA request?

2021-06-22 17:21 UTC, yvonnetangsu commented on src/components/media/simpleImage.js
> +    <WidthBox width={imageWidth}>
Yeah, I think it would be nice to use the figure element. The WidthBox uses the Grid component from Decanter React, but I'm totally fine with adding a `<figure>` wrapper around the image and `figcaption` and nest the `figure` within the WidthBox (so WidthBox can stay as is).

2021-06-22 17:24 UTC, yvonnetangsu commented on src/components/media/simpleImage.js
> +          }`}
You might not need all of these classnames here - can probably remove the su-media__caption (that's the BEM naming we use for Giving only) and the imageWidth class is probably not needed as well since the WidthBox should take care of the bounding box (but please double check because I could be wrong 😄 )

2021-06-22 17:25 UTC, yvonnetangsu commented on src/components/media/simpleImage.js
> +          }`}
Please wrap this whole RichTextRenderer wtihin a `<figcaption>`. Thanks!

2021-06-22 17:27 UTC, yvonnetangsu commented on src/components/media/simpleImage.js
> +          }`}
Please also add the `su-caption` classname to the figcaption - I think that would take care of the caption styling (it's from Decanter v7 under TW `components/typography/styles`)

2021-06-22 17:29 UTC, yvonnetangsu commented
@rebeccahongsf Looking great! A few comments added, and we'll probably groom this ticket a bit more after (eg, we might want to add the spacing top/bottom option in the component as well. Thanks! 😄

2021-06-24 06:46 UTC, yvonnetangsu commented on src/components/media/simpleImage.js
> +        <img src={filename} alt="" />
I think we're going to need to pass an option alt as prop here. If the alt is provided, then it should show up, if not, if should render the alt="" tag 😄

2021-06-24 06:49 UTC, yvonnetangsu requested changes
Thank you for the changes - works great 😄 . We'll likely groom this ticket some more tomorrow, but in the meantime, I left the comment about adding an alt as prop, and if you could please add some image resizing that'd be great. 

Please see the Giving example (first get the image width of the uploaded original image, then resize according to the width option they choose, and only resize if the original size is wider than the width option)
https://github.com/SU-SWS/ood_giving_site/blob/main/src/components/media/storyImage.js

We have the utilities here in SAA (`getImageWidth.js` and `transformImage.js`)
https://github.com/SU-SWS/saa_alumni/tree/main/src/utilities
Note: you'll only see the downsized image in the Netlify preview, but not in the development build.

2021-06-24 19:44 UTC, yvonnetangsu commented on src/components/media/simpleImage.js
> +              className={`su-caption su-text-${captionAlign}`}
```suggestion
              className={`su-caption su-mt-08em su-text-${captionAlign}`}
```
Adding some top margin to the caption (editing free hand so let's see how that looks - might need adjustment) 😃

2021-06-24 23:26 UTC, sherakama approved these changes
This is looking good. You are good to merge when you get @yvonnetangsu's blessing.

2021-06-24 23:47 UTC, yvonnetangsu commented
@rebeccahongsf For next week when you come back, if you could just add that optional alt text support, then let's call that done for now. The rest (image processing and adding spacing top/bottom) can wait till next sprint, since you have a lot on your plate and we likely want to ask for some design input from Kerri (eg, caption max width etc) 😄

2021-06-29 02:18 UTC, yvonnetangsu approved these changes
GTG - thanks @rebeccahongsf! The build error went away after a merge main - it needed some graphQL work that Shea added last night 😄

2021-06-29 02:18 UTC, merged