ADAPT-2734 Add Rich Media Component
SU-SWS/saa_alumni pull request #53
Opened 2021-06-29 19:04 UTC by rebeccahongsf

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-06-30 04:36 UTC, sherakama commented on src/components/media/embedVideo.js
> +  const startSec = startSecond ? parseInt(startSecond) : 0;
Missing radix param. `parseInt(startMinute, 10)`

2021-06-30 04:37 UTC, sherakama commented on src/components/media/embedVideo.js
> +      <VideoWrapper {...blok}>
Doesn't blok have a number of properties on it like `_uid` and such that shouldn't be HTML props?

2021-06-30 04:40 UTC, sherakama requested changes
Looks good. Thanks for porting this over. Just a couple of comments and please clean up the linting noise.

2021-06-30 18:05 UTC, rebeccahongsf commented on src/components/media/embedVideo.js
> +      <VideoWrapper {...blok}>
Ack! Great catch @sherakama 😅  I restructured the destructuring of props to the Video Wrapper components. Please do not hesitate to let me know if there's a better way to go about this. Thanks!

2021-06-30 22:06 UTC, yvonnetangsu commented on src/components/media/embedVideo.js
> +            className={`su-media__wrapper ${aspectRatio}`}
I totally owe you a review of this one. Looking great - i like how you were using the TW classes. Let's keep that but also adding the aspect ratios to the `dataSource.js`, e.g., in Storyblok, we could add the key-value pair like this instead of having the TW classnames in the value:
key: 16 x 9 (Default)
value: 16x9

And then in dataSource.js
we can add an object with 
`{"16x9": "su-aspect-w-16 su-aspect-h-9"}` 
etc

We're keeping all the classes names inside our code and not on Storyblok, so the JIT mode knows what classes to generate always 😄

2021-06-30 23:52 UTC, sherakama approved these changes
GTG by me.

2021-07-01 00:06 UTC, yvonnetangsu commented on src/components/media/embedVideo.js
> +  }
I think we can simplify this by using the `WIdthBox` component like you did for Simple Image here 😄  
https://github.com/SU-SWS/saa_alumni/blob/main/src/components/media/simpleImage.js

Let's give them these options, plus 6 of 12 columns:
![Screen Shot 2021-06-30 at 5 05 48 PM](https://user-images.githubusercontent.com/42749717/124045877-7e8ebb00-d9c5-11eb-9c73-250b6d62231a.png)

2021-07-01 00:11 UTC, yvonnetangsu commented on src/components/media/embedVideo.js
> +        ${spacingBottom !== "none" ? smallPaddingBottom[spacingBottom] : ""}`;
This works, but since we'll be reusing a lot of code on this site. Let's make components more consistent. We were figuring things out on Giving so things were slightly messier there, but since we've figured out what we liked now, let's stick to it 😺 

Could we structure it so that we use separate variables, and our good friend `dcnb` to chain them?
  const paddingTop = smallPaddingTop[spacingTop] ?? ""
  const paddingBottom = smallPaddingBottom[spacingBottom] ?? ""

Here's an example where we use this approach:
https://github.com/SU-SWS/saa_alumni/blob/main/src/components/layout/section.js

2021-07-01 00:13 UTC, yvonnetangsu commented on src/components/media/embedVideo.js
> +              mediaAspectRatio !== "none" ? mediaAspectRatio[aspectRatio] : ""
Similarly please use suggested approach above when pulling from dataSource 🙏🏼 😄 
Also, let's default to "16x9" for this one rather than no aspect ratio.

2021-07-01 00:15 UTC, yvonnetangsu commented on src/components/media/embedVideo.js
> +                className={`su-caption su-mt-06em children:su-leading-snug su-text-${captionAlign}`}
`dcnb` please - and remember JIT mode doesn't like class names concat this way (`su-text-${captionAlign}`) , Check if dataSource.js has a text-align option (you might need to add the right align), then you could use the similar approach as above also 🙏🏼

2021-07-01 00:15 UTC, yvonnetangsu commented on src/utilities/dataSource.js
> +};
Perfect 💯  😄

2021-07-01 00:18 UTC, yvonnetangsu requested changes
Just a few comments to use existing component for width, add more width options, and use consistent format with `dcnb` and pulling from `dataSource.js`. Thank you for the great work so far!

2021-07-01 00:20 UTC, yvonnetangsu commented on src/components/media/embedVideo.js
> +  }
Let's rename "Edge-to-edge" (only the key part) with "Fit parent container" here. Thanks!

2021-07-01 17:48 UTC, yvonnetangsu approved these changes
Thank you for the changes - looks great. GTG 🚀

2021-07-01 17:50 UTC, yvonnetangsu commented on src/components/media/embedVideo.js
> +  const captionAlignment = textAlign[captionAlign ?? "left"];
I like your formatting here 😄  ❤️

2021-07-01 17:50 UTC, merged