ADAPTSM-58 | @rebeccahongsf | update related contact prefill adc values
SU-SWS/saa_alumni pull request #553
Opened 2023-01-11 21:29 UTC by rebeccahongsf

# NOT READY FOR REVIEW

# Summary
- update related contact prefill adc values

# Review By (Date)
- when possible

# Review Tasks

## Setup tasks and/or behavior to test

1. Navigate to `/membership/register/related-contacts/`
2. Select a related contact and click Next to navigate to the form page
3. Verify that the first and last name prefills in the recipient information section and Gift section is displayed.
4. Navigate back to `/membership/register/related-contacts/`
5. Select a new contact
6. Verify that the recipient information section and Gift section is displayed.
7. Review code 👾 

# Associated Issues and/or People
- ADAPTSM-58

2023-01-11 23:17 UTC, jdwjdwjdw requested changes
Everything looking good outside of the relationship subheading not being displayed.

2023-01-11 23:17 UTC, jdwjdwjdw commented on src/components/page-types/membershipFormPage/relatedContactSelection.js
>                                    subheading={relatedContact.su_relation}
Need to update this MembershipCard subheading to account for new relationship name.

2023-01-11 23:17 UTC, jdwjdwjdw commented on src/components/page-types/membershipFormPage/relatedContactSelection.js
>          su_email: undefined,
Is `su_email` needed? Just wondering because you didn't included it in our other conversation.

2023-01-12 17:28 UTC, rebeccahongsf commented on src/components/page-types/membershipFormPage/relatedContactSelection.js
>          su_email: undefined,
I'm leaving `su_email` for now since I anticipate GG adding this ADC value. If they determine that this is not needed, we can remove this later on.

2023-01-12 17:29 UTC, rebeccahongsf commented on src/components/page-types/membershipFormPage/relatedContactSelection.js
>                                    subheading={relatedContact.su_relation}
Great catch! Thanks @jdwjdwjdw

2023-01-12 17:33 UTC, rebeccahongsf commented on src/components/page-types/membershipFormPage/relatedContactSelection.js
>          su_email: undefined,
Just confirmed that `su_email` has been added 👍

2023-01-12 18:06 UTC, jdwjdwjdw approved these changes
Thanks for the update - LGTM!

2023-01-12 18:48 UTC, merged

2023-01-12 22:11 UTC, rebeccahongsf commented on src/components/page-types/membershipFormPage/relatedContactSelection.js
> +        su_recipient_email: '',
@jdwjdwjdw IOU a follow up fix-it PR that cleans up the `''` and `undefined` along with removing L37 `registrant.su_did` in membership form 👍