ADAPTSM-118 | @rebeccahongsf | update select ux and add digitalName
SU-SWS/saa_alumni pull request #568
Opened 2023-01-24 23:43 UTC by rebeccahongsf

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2023-01-26 00:28 UTC, jdwjdwjdw requested changes
Overall looking great! A couple of things I noticed:

- The select/unselect functionality works as expected almost everywhere, but I did notice that if you click `Myself`, then `Pay in installments`, then go back and select `Someone else` (while keeping `Pay in installments` selected), the `Select membership type` button routs to https://deploy-preview-568--stanford-alumni.netlify.app/membership/register/installments/form instead of https://deploy-preview-568--stanford-alumni.netlify.app/membership/register/related-contacts. Would it be possible to have `Pay in installments` automatically be unselected if you switch to the Someone else card option?
- I'm seeing some issues/differences with the card styling on select:
  - For all of the cards, `su-bg-saa-black` should only be applied while selected
  - For the newContact card, `su-border-dashed` should only be applied while the card is not selected

2023-01-27 18:46 UTC, rebeccahongsf commented on src/components/page-types/membershipFormPage/membershipCard.js
> +          isSelected && newContact ? 'su-bg-saa-black' : ''
I encountered an issue with `dcnb` not applying the border styles within the `membershipCard.styles.js` file 🤔 (I'm guessing you encountered this as well in your membership card styles iteration.) I've reworked it into a conditional ternary operator 👍

2023-01-27 18:46 UTC, rebeccahongsf commented
@jdwjdwjdw ready for another round of feedback 🖖

2023-01-27 22:49 UTC, jdwjdwjdw commented on src/components/page-types/membershipFormPage/membershipCard.js
> +          isSelected && newContact ? 'su-bg-saa-black' : ''
yeah I definitely encountered some strange issues with that, but just attributed it to user error at the time 🤔

Thanks for the rework! Can you adjust the `newContact` card so the dashed border is removed/border solid added on select? I'm also only seeing `su-bg-saa-black` being applied to the `newContact` selected card, so that will need to be updated for the default membership cards as well.

2023-01-27 22:52 UTC, jdwjdwjdw requested changes
Updated select functionality works great 👏 just some minor styling changes, then we should be good to go.

2023-01-30 17:49 UTC, rebeccahongsf commented
And we're ready for another round of feedback @jdwjdwjdw 🤞😄

2023-01-30 20:08 UTC, merged