ADAPTSM-39 | @rebeccahongsf | specify form options
SU-SWS/saa_alumni pull request #576
Opened 2023-02-01 22:14 UTC by rebeccahongsf

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2023-02-02 20:54 UTC, jdwjdwjdw requested changes
Thanks @rebeccahongsf! Everything you mentioned in the review tasks regarding the number of options are working as you specified 👍 I'm seeing some issues with the urlData when there is no promo / appeal code, though.

2023-02-02 20:54 UTC, jdwjdwjdw commented on src/components/page-types/membershipFormPage/typeOfRegistrant.js
> +  }
I'm not seeing this code added as UrlData currently:
![image](https://user-images.githubusercontent.com/49299083/216446035-5952c6e2-1dd9-448f-93f5-f12a81d06d48.png)

Also, based on the spreadsheet - should this be `alum_myself_myself`?

2023-02-02 20:54 UTC, jdwjdwjdw commented on src/components/page-types/membershipFormPage/typeOfRegistrant.js
> +                    }
I'm not seeing this code added as UrlData currently:
![Screen Shot 2023-02-02 at 12 49 56 PM](https://user-images.githubusercontent.com/49299083/216446609-15718d82-04a5-4634-a125-f1a65db6d342.png)

2023-02-07 17:42 UTC, rebeccahongsf commented
Thanks for the speedy review and feedback @jdwjdwjdw! This is ready for another around of review 🤞

2023-02-07 21:09 UTC, jdwjdwjdw requested changes

2023-02-07 21:09 UTC, jdwjdwjdw commented on src/components/page-types/membershipFormPage/typeOfRegistrant.js
> +                      }
Someone adjustments needed here I think. When I select `Someone else` with no promo code, and create a new contact (or select existing), I'm seeing `urlData=alum_myself_full` instead of `urlData=buy_someone` currently.

2023-02-07 23:27 UTC, jdwjdwjdw approved these changes
Looking good to me, thanks @rebeccahongsf 😎

2023-02-07 23:58 UTC, merged