ADAPT-2921: Story Page
SU-SWS/saa_alumni pull request #65
Opened 2021-07-06 07:34 UTC by yvonnetangsu

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-07-07 23:25 UTC, sherakama commented
> Tweak story cards - tab label text field is moved to the story card picker in Storyblok. Media icon should display depending on the story type selected (displayed for podcast or video)

With this schema change did you have to migrate any content or clean up any existing content schemas?

2021-07-07 23:36 UTC, sherakama commented on src/components/content-types/story/storyCardView.js
> +        {!hideImage && (cardFilename || filename) && (
Isn't this hide image a little redundant now? How about removing it and just allowing the content author to add an image or not in the storyblok UI?

2021-07-07 23:41 UTC, sherakama commented on src/components/content-types/story/storyCardView.js
> +              {typeSrText && <SrOnlyText srText={`${typeSrText}: `} />}
So you could potentially have two sets of screenreader text here?

2021-07-07 23:42 UTC, yvonnetangsu commented on src/components/content-types/story/storyCardView.js
> +        {!hideImage && (cardFilename || filename) && (
The option is in the picker, but the image field is in the story content type under the "card view" tab. I talked to Kerri and Dena, and it looks like they want the option to display different versions of the card for the same story. So for the same story, depending on what page the card is in, they might or might not want to show the image.

2021-07-07 23:42 UTC, yvonnetangsu commented on src/components/content-types/story/storyCardView.js
> +              {typeSrText && <SrOnlyText srText={`${typeSrText}: `} />}
Yup, since the tab text is a text field that's curated, so they can have eg, "featured", in that case, it can be "featured podcast"

2021-07-07 23:44 UTC, yvonnetangsu commented
> > Tweak story cards - tab label text field is moved to the story card picker in Storyblok. Media icon should display depending on the story type selected (displayed for podcast or video)
> 
> With this schema change did you have to migrate any content or clean up any existing content schemas?

I deleted the old Storyblok field in the story content type. I don't seem to need to do anything for them to update, but I'll need to go in and update the presets later.

2021-07-07 23:46 UTC, sherakama commented on src/components/content-types/story/storyPageView.js
> +  }
You have this same pattern in the storycardview. Perhaps abstract it into a separate include or component.

2021-07-07 23:48 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +  }
Sure, I can do that

2021-07-07 23:52 UTC, sherakama commented on src/components/content-types/story/storyPageView.js
> +  }
Each of these options has enough markup to be their own component. How about creating a component for them and passing through the parameters?

2021-07-07 23:57 UTC, sherakama commented on src/components/content-types/story/storyPageView.js
> +                <Heading
missing page-title id for hero anchor.

2021-07-07 23:58 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +  }
Actually that's a good idea. In that case, could I put this on hold till Rebecca's simple image PR get merged (waiting for one change), since I think we can use these soon to be created image components for the simple image options also.

2021-07-07 23:58 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +                <Heading
Good catch!

2021-07-08 00:00 UTC, sherakama commented on src/components/content-types/story/storyPageView.js
> +                )}
```suggestion
                {(nicePublishedDate || manualDate) && (
                  <p className="su-card-paragraph su-leading-display su-mb-02em su-text-black-70">
                    {nicePublishedDate || manualDate}
                  </p>
                )}
```

pedantics

2021-07-08 00:02 UTC, sherakama commented on src/components/content-types/story/storyPageView.js
> +            <div className="story-content su-rs-mt-4 su-rs-mb-9">
why add a class name here?

2021-07-08 00:05 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +                )}
My initial thought would be that they can manually override the datepicker date if they want something different, but I guess they just delete the datepicker date if they don't want that to display 🤔

2021-07-08 00:05 UTC, sherakama commented on src/tailwind/plugins/theme/colors.js
> +          30: "rgba(192, 192, 191, 30%)", // For card borders
did you replace all occurrences of 20 with 30?

2021-07-08 00:05 UTC, sherakama requested changes
Feedback left. Looking slick!

2021-07-08 00:06 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +            <div className="story-content su-rs-mt-4 su-rs-mb-9">
I've been doing that for card-content etc so just staying consistent, and make browser inspection a little easier.

2021-07-08 00:06 UTC, yvonnetangsu commented on src/tailwind/plugins/theme/colors.js
> +          30: "rgba(192, 192, 191, 30%)", // For card borders
I believe so - used it in event card, story card and basic card, but I'll double check

2021-07-08 00:07 UTC, sherakama commented on src/components/content-types/story/storyPageView.js
> +                )}
Or switch it around the other way for the if statement. Just want the ||'s to align.

2021-07-08 00:12 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +                )}
Oh lol 😂  Ok, let me think about this - but I'll make sure the 2 pairs align 😹

2021-07-08 00:25 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +                <Heading
Actually we don't need the page-title id since story pages will not have the Hero banner with the scroll to button. I added the main-content id for skiplink for stories, so I think we're good.

2021-07-08 06:05 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +  }
Added HeroIcon component

2021-07-08 06:06 UTC, yvonnetangsu commented on src/tailwind/plugins/theme/colors.js
> +          30: "rgba(192, 192, 191, 30%)", // For card borders
I think I got them all so resolving this

2021-07-08 07:07 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +  }
Added CaptionMedia component - when I have more time we could use that to refactor Rebecca's simple image and embed video component also.

2021-07-08 07:10 UTC, yvonnetangsu commented on src/components/simple/heroIcon.js
> +      {!hideSrText && <SrOnlyText srText={srText || ` ${iconType} `} />}
Added hideSrText option since sometimes the SR text is added elsewhere already, eg., SbLink automatically add SR text "(external link)" after each external link, and we don't need to add SR text for internal links.

2021-07-08 07:12 UTC, yvonnetangsu commented on src/components/media/captionMedia.js
> +    </WidthBox>
New CaptionMedia component that allows some props to get passed in, but have the media element itself as a children since sometimes the media element can need a gradient overlay or an extra wrapper for aspect ratio. Also, this should support videos and some other embeds as well.

2021-07-08 07:15 UTC, yvonnetangsu commented on src/components/content-types/story/storyCardView.js
> +              )}
Using the new HeroIcon component for the media icons

2021-07-08 07:15 UTC, yvonnetangsu commented on src/components/content-types/story/storyCardView.js
>              />
Using the new HeroIcon component for the card internal/external link icon. I can refactor other cards later.

2021-07-08 21:00 UTC, yvonnetangsu commented
@sherakama Made the changes you requested. Please take another look. Thanks 😄

2021-07-09 20:32 UTC, sherakama commented on src/components/content-types/story/storyCardView.js
> +        {!hideImage && (cardFilename || filename) && (
Ok, thanks.

2021-07-09 20:33 UTC, sherakama commented on src/components/simple/heroIcon.js
> +      {!hideSrText && <SrOnlyText srText={srText || ` ${iconType} `} />}
Who controls the hiding? Is it the content author? I don't trust the content author to know when to make a good choice here.

2021-07-09 20:49 UTC, sherakama approved these changes
GTG

2021-07-09 21:17 UTC, yvonnetangsu commented on src/components/simple/heroIcon.js
> +      {!hideSrText && <SrOnlyText srText={srText || ` ${iconType} `} />}
Only control by us - it's not an option in Storyblok 😄

2021-07-09 21:17 UTC, merged