ADAPT-2705 Create CtaCard
SU-SWS/saa_alumni pull request #67
Opened 2021-07-06 21:16 UTC by rebeccahongsf

# NOT READY FOR REVIEW

# Summary
- Create CtaCard

# Review By (Date)
- July 13

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- [ADAPT-2705](https://stanfordits.atlassian.net/browse/ADAPT-2705)

2021-07-07 18:40 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +      <Heading level="4" font="sans" weight="bold" className={dcnb("su-mb-0")}>
Ahh that reminds me, please add a "Heading level" option in storyblok as well. We have that for all the other cards so might as well add it here :D (please see the basic card for example - there's a datasource for heading level that you could pull from). Thanks!!

2021-07-07 18:42 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +      )}
Instead of having this be a nested CTA link. Let's just add a Storyblok Link component (so they can pick internal/external links), and use the `.stretched-link` class to make the whole card a link 😄  (see event card for example)

2021-07-07 20:05 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +      )}
In the event card, we wrap the SbLink around the headline, but for this CTA card, it probably makes more sense to wrap the link around the CTA text instead, and render the clickable area to cover the whole card 😸

2021-07-08 22:27 UTC, rebeccahongsf commented on src/components/cards/ctaCard.js
> +            "cta-card su-w-full su-relative su-bg-digital-red su-text-white hocus:su-bg-cardinal-red-xdark su-basefont-23 su-break-words su-p-50 su-min-h-[50rem] su-h-full su-flex su-flex-col su-just
@yvonnetangsu @sherakama [the ticket ](https://stanfordits.atlassian.net/browse/ADAPT-2705)specified "no max height" so I've set the min height to 500px and height to 100%. With the height set to 100%, if there are multiple cards in a grid row, they will all take on the height of the tallest card. 

Was that the preferred display or did we want them to be staggered?

2021-07-08 22:30 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +            "cta-card su-w-full su-relative su-bg-digital-red su-text-white hocus:su-bg-cardinal-red-xdark su-basefont-23 su-break-words su-p-50 su-min-h-[50rem] su-h-full su-flex su-flex-col su-just
I'm going to pull this down and test it out in the grid component. We have an option in the grid to make them the same height, so I'm thinking ideally they can be staggered unless that option is checked 😄  Go take your long weekend. I'll review later.

2021-07-08 22:39 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +          >
We need to change the level string input from storyblok to a number due to the Decanter-React refactor, so, `level={parseInt(headingLevel, 10) ?? 3}`

Also, even though we allow for different heading levels, we should set a fixed heading font size, e.g., see event.js (under components/content-type/event/). The heading level choices is for accessibility not for font size change 😄

2021-07-08 22:49 UTC, yvonnetangsu commented
To test this out properly, I'd suggest adding some CTA cards to the /test/yvonne/test-perks (?) page, since that's the primary page that will use this type of card 😄

2021-07-12 06:52 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +            "cta-card su-w-full su-relative su-bg-digital-red su-text-white hocus:su-bg-cardinal-red-xdark su-basefont-23 su-break-words su-p-50 su-min-h-[50rem] su-h-full su-flex su-flex-col su-just
I think we could take out the min-height on the card. For the padding, let's use responsive-spacing, I believe for cards, we've using su-rs-p-2 (responsive-spacing step 2). Please check with Kerri if she wants a larger top padding compared to the other 3 sides 😄

2021-07-12 06:56 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +            classes="su-block su-stretched-link su-group su-transition-colors su-no-underline su-underline-offset su-text-white hocus:su-underline hocus:su-text-digital-red-xlight children:hocus:su-t
Let's also use responsive spacing for the top margin here as well - just eyeballing, it looks like a su-rs-mt-3 or 2 👀

2021-07-12 16:58 UTC, rebeccahongsf commented on src/components/cards/ctaCard.js
> +            "cta-card su-w-full su-relative su-bg-digital-red su-text-white hocus:su-bg-cardinal-red-xdark su-basefont-23 su-break-words su-p-50 su-min-h-[50rem] su-h-full su-flex su-flex-col su-just
Thanks Yvonne! 😄  I'll check in with Kerri about the top padding this morning and update the PR accordingly!

2021-07-12 18:29 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +          >
Please also add the fixed heading font size 😄  - I think a `su-text-m2` looks about right in this case. The headings should all end up having the same font size no matter what level you select.

2021-07-12 18:45 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +          >
There's also a `size` prop in the Heading component 😄

2021-07-12 22:28 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +    const linkIcon = heroicon[icon] ?? heroicon["arrow-right"];
Instead of letting them pick the icon, please have it display the appropriate icon depending on the `link.linktype` prop :) In the CTA link, we let the content author pick because we offer them choices of additional icons, e.g., video, download etc, but for card headings (and in this case the link text), since we're only giving them 2 choices, let's add it for them automatically. You could see storyCardView.js as an example.

2021-07-12 22:31 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +            "cta-card su-w-full su-relative su-bg-digital-red su-text-white hocus:su-bg-cardinal-red-xdark su-basefont-23 su-break-words su-p-50 su-flex su-flex-col su-justify-end"
```suggestion
            "cta-card su-w-full su-relative su-bg-digital-red su-text-white hocus:su-bg-cardinal-red-xdark su-basefont-23 su-break-words su-rs-py-3 su-rs-px-2 su-flex su-flex-col su-justify-end"
```
Let's use responsive-spacing for card padding 😄

2021-07-13 06:15 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +  ) => {
I don't see a rel field in Storyblok for CTA cards so let's remove it 😄

2021-07-13 06:15 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +              attributes={rel ? { rel } : {}}
I think this can be removed also

2021-07-13 06:16 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +    }
Thanks! 🙏🏼

2021-07-13 06:18 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +  ) => {
We probably don't need the forwardRef and the ref, but it doesn't hurt so no need to remove 😄 

We added the ref in CtaLink because we needed it for creating a focus trap in the search modal, but who knows, there is always a chance a CTA card will be put inside a modal 🤷🏼

2021-07-13 06:19 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +  ) => {
Also, the icon prop can now be removed too.

2021-07-13 06:22 UTC, yvonnetangsu requested changes
Final batch of feedback left - if you could please remove the `rel` and `icon` prop (and the logic around the `Icon` element since there isn't an `icon` prop anymore, then we're good to go. Thank you - looks great 🙏🏼 😄

2021-07-13 06:34 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +            "cta-card su-w-full su-relative su-bg-digital-red su-text-white hocus:su-bg-cardinal-red-xdark su-basefont-23 su-break-words su-rs-py-3 su-rs-px-2 su-flex su-flex-col su-justify-end"
```suggestion
            "cta-card su-w-full su-relative su-transition-colors su-bg-digital-red su-text-white hocus:su-bg-cardinal-red-xdark su-basefont-23 su-break-words su-rs-py-3 su-rs-px-2 su-flex su-flex-col su-justify-end"
```
One more - for more gradual transition of background colors on hover

2021-07-13 17:32 UTC, sherakama commented on src/components/cards/ctaCard.js
> +const CtaCard = React.forwardRef(
Why the forward ref here?

2021-07-13 17:34 UTC, sherakama approved these changes
GTG with Yvonne's approval.

2021-07-13 17:39 UTC, yvonnetangsu commented on src/components/cards/ctaCard.js
> +const CtaCard = React.forwardRef(
I think Rebecca might have modeled this after our CtaLink component which has the forwardRef (Yanik added the ref for focus trapping within the search modal since there were CTA links in the modal).

2021-07-13 17:44 UTC, sherakama commented on src/components/cards/ctaCard.js
> +const CtaCard = React.forwardRef(
Let's remove it until we need it

2021-07-13 21:33 UTC, yvonnetangsu approved these changes
Thank you for all the revisions - nice job, @rebeccahongsf ! I just ran a final eslint - GTG 🥳

2021-07-13 21:34 UTC, merged