ADAPT-5659 | @rebeccahongsf | add a check for unpublished trip to prevent breaking build
SU-SWS/saa_alumni pull request #678
Opened 2023-06-05 18:48 UTC by rebeccahongsf

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2023-06-05 19:42 UTC, rebeccahongsf commented
Hmm. Looks like the notify form page still generates. Please hold on reviewing while I put together another check 😄

2023-06-06 02:08 UTC, rebeccahongsf commented
@sherakama the registration form build conditional has been updated to check for the actual trip content. The notify form pages (e.g. [poland notify form](https://deploy-preview-678--stanford-alumni.netlify.app/travel-study/destinations/poland-2024/notify)) still builds but displays the white page of death due to missing information from the unpublished trip. 

I imagine that a user shouldn't be able to access the notify me page without going through the trip page but thought I'd check in — did we want to account for this use case? 

I started testing a few things (e.g. adding build conditionals for the `formPage` content type) but decided to pause since the right conditional statement taking me longer than expected to figure out 🤔

2023-06-07 00:09 UTC, sherakama commented on gatsby-node.js
> +          if (content.trip && content.trip.content?.title) {
So, when a trip is selected but unpublished, `content.trip` is the string id of the story in storyblok. When the trip is selected and published, `content.trip` is an object with stuff like `content.trip.content`. When no trip is selected, content.trip is undefined. 

So, you could check that `content.trip` exists, is an object, and has content.

2023-06-07 00:10 UTC, sherakama requested changes
Please revise the validation.

2023-06-07 00:15 UTC, sherakama commented
> I imagine that a user shouldn't be able to access the notify me page without going through the trip page but thought I'd check in — did we want to account for this use case?

It breaks because of missing information in the destructure statement on line 24. That should be a quick fix to handle and produce an error notice vs white screen. Please handle this case as well.

2023-06-12 22:36 UTC, sherakama commented
FYI: I published the China trip to get another build to work. If you start working on this again you will need to unpublish https://app.storyblok.com/#/me/spaces/118608/stories/0/0/272989885

2023-06-13 15:03 UTC, sherakama approved these changes
Thanks for sticking with this @rebeccahongsf 

This is GTG for me now.

2023-06-13 15:06 UTC, merged