Adapt 2726 smart focus
SU-SWS/saa_alumni pull request #68
Opened 2021-07-07 19:23 UTC by Lyafel

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-07-07 19:23 UTC, Lyafel commented
Added the manual focus to be available to any image but the filter will only apply if the focus was set. Added /smart only to the small round image.

2021-07-13 16:10 UTC, sherakama commented on src/utilities/transformImage.js
> +    image.toLowerCase().endsWith(".jpeg")
Ty for making this change.

2021-07-16 20:05 UTC, sherakama commented
![Screen Shot 2021-07-16 at 1 04 25 PM](https://user-images.githubusercontent.com/550602/126002867-7d2d376b-5602-43fb-ad3d-f485b75cd0de.png)
![Screen Shot 2021-07-16 at 1 04 08 PM](https://user-images.githubusercontent.com/550602/126002881-e66da5ea-d438-4a90-a2ba-87107bf769d6.png)

This is looking like it works. @yvonnetangsu please review.

2021-07-23 07:28 UTC, yvonnetangsu commented
I'll pull this down to review today - sorry about the delay!

2021-07-27 07:55 UTC, yvonnetangsu commented
@Lyafel I'm check with @sherakama to see if we can remove that isNetlify check so we can see the results of adding image focus during development mode in the editor. I tried removing it in
https://github.com/SU-SWS/saa_alumni/pull/98
and it seems like the images are showing up fine in the editor for me.

2021-07-27 08:04 UTC, yvonnetangsu commented
@Lyafel @sherakama I'm testing the circular image - I like how this works. Looks like we can remove the imageFocus prop and the storyblok option for the image focus inputted by content authors now, since the image will always be cropped to a square, changing the image focus option isn't going to do anything (we're object fitting a square image into a square container now)

2021-07-29 00:52 UTC, yvonnetangsu commented
@Lyafel Shea merged my PR to remove the isNetlify check on transformImage. Please merge main branch into this if you end up coming back to this work (I suspect you're busy with search - just want to keep you in the loop of things since I'm out Thursday and Friday 😄 ) Thank you!

2021-08-16 05:16 UTC, Lyafel commented
@yvonnetangsu 

> @Lyafel @sherakama I'm testing the circular image - I like how this works. Looks like we can remove the imageFocus prop and the storyblok option for the image focus inputted by content authors now, since the image will always be cropped to a square, changing the image focus option isn't going to do anything (we're object fitting a square image into a square container now)

Do you want to remove the imageFocus only on the circular/square image right?

2021-08-17 05:26 UTC, sherakama approved these changes
GTG. @yvonnetangsu for final review.

2021-08-18 04:20 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +          smartFocus={focus}
@Lyafel I think this PR looks good to be, except we can remove image focus here, since for Story page layout, image focus is only used for the fullwidth image option. For non-fullwidth hero image, we let the whole image show.

2021-08-18 04:22 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +          smartFocus={focus}
It will likely need some eslint fix after removing these 2 lines

2021-08-18 04:30 UTC, yvonnetangsu requested changes
Please remove those 2 lines from the story page view and run eslint, then it's GTG. Thanks!

2021-08-18 06:09 UTC, yvonnetangsu approved these changes
GTG - thanks!

2021-08-18 06:10 UTC, merged