ADAPT-5902 | @rebeccahongsf | theme mega menu
SU-SWS/saa_alumni pull request #695
Opened 2023-08-28 20:07 UTC by rebeccahongsf

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2023-08-29 03:49 UTC, rebeccahongsf commented on src/components/navigation/MegaMenu/megaMenuLinkItem.js
> +      <SbLink
Question for Tuesday @yvonnetangsu 😃 — Does Storyblok link field auto-magically define the external links differently from the internal links? I know we have a conditional to check within the  `SbLink` component but I was wondering if any additional code work is needed to make it work 🤔

2023-08-29 16:57 UTC, yvonnetangsu commented on src/components/navigation/MegaMenu/megaMenuLinkItem.js
> +      <SbLink
@rebeccahongsf I don't believe you need to do anything to the link prop, but I'm looking at the current navItem component, and there is a hasExternalLinkIcon prop that you can set (whether to display an external link icon) 😄 
https://github.com/SU-SWS/saa_alumni/blob/dev/src/components/navigation/navItem.js

2023-08-29 16:59 UTC, yvonnetangsu commented on src/components/navigation/MegaMenu/megaMenuLinkItem.js
> +      <SbLink
It's more for whether you want all external links to display an icon - I don't think you need to do the external link check yourself.

2023-08-29 19:28 UTC, yvonnetangsu commented
@rebeccahongsf One thing I noticed is that you might be able to reuse more of the responsive styles for the top level parent buttons for smaller breakpoints. You're probably still working on it though? 😄 

PR preview:
![Screenshot 2023-08-29 at 12 27 19 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/ca5a39e0-4047-4e04-842b-924eeb8d3325)

On live site:
![Screenshot 2023-08-29 at 12 19 00 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/90cd966b-abeb-4809-abb4-85c9d945f510)

2023-08-29 22:32 UTC, rebeccahongsf commented
> @rebeccahongsf One thing I noticed is that you might be able to reuse more of the responsive styles for the top level parent buttons for smaller breakpoints. You're probably still working on it though? 😄
> 
> PR preview: ![Screenshot 2023-08-29 at 12 27 19 PM](https://user-images.githubusercontent.com/42749717/264132284-ca5a39e0-4047-4e04-842b-924eeb8d3325.png)
> 
> On live site: ![Screenshot 2023-08-29 at 12 19 00 PM](https://user-images.githubusercontent.com/42749717/264131795-90cd966b-abeb-4809-abb4-85c9d945f510.png)

Ooo! This is a great call out, @yvonnetangsu! 😅 I totally overlooked the parent text second line field

2023-08-29 22:51 UTC, yvonnetangsu commented
> Ooo! This is a great call out, @yvonnetangsu! 😅 I totally overlooked the parent text second line field

I figured you were probably still working on it too - there is no rush! 😄

2023-08-30 17:15 UTC, yvonnetangsu commented
@rebeccahongsf Very nice work - this is 95% there 😄 ! Here comes just a few comments then should be GTG

- [ ] On LG and +, when a mega menu panel is open, please add functionality to close with the escape key
- [ ] Please ask designer for a hocus state for this close button 😄 

![Screenshot 2023-08-30 at 10 05 40 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/b5a3b61e-0ff4-40a9-b903-3449f01f79ad)

- [ ] For Travel Study, there seems to be a visual regression which cause the normal state of the close button to become black, and the hocus state is taking on the one for homesite as well

![Screenshot 2023-08-30 at 10 05 58 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/47fe4967-37c0-4ee4-b768-e285077f39f1)

![Screenshot 2023-08-30 at 10 08 01 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/b83ed424-9260-4626-b3ba-79d82064d509)

- [ ] This is a designer thing - I would push back hard on this layout especially for the XL breakpoint. It really seems like esp for the panels with the card, it would take on the full width of the container here

![Screenshot 2023-08-30 at 9 55 22 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/619b7078-f4cd-40fc-a41c-d2d9b8401c18)

- [ ] Also, another thing to check with designer - since the masthead of the SAA homesite doesn't quite follow the normal center container (ie, the screen margins are a bit different to accommodate the logo treatment, I'd ask the designer whether to align the content container to this modified container, eg, on the left edge, have the first column in the panel left aligned with the left side of the logo.

- [ ] I would suggest finetuning the width/flex treatment of the individual column a bit (maybe best to use a CSS grid here), eg, currently if I have a long item in a column it would cause the other column to shrink

![Screenshot 2023-08-30 at 10 14 29 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/a762f207-a92d-4046-bba9-55069e0b52ca)

There are different ways to update this, using a CSS grid might be the most straightforward, but you can also add su-shrink-0 to each column and give them each a max width etc. Up to you and the designer 😄

2023-08-30 17:16 UTC, yvonnetangsu requested changes
Just added some comments for final finetuning - looking really great! Nice job 👏🏼 😄

2023-09-01 16:48 UTC, rebeccahongsf commented
@yvonnetangsu I updated this PR with some of your requested changes.

I'm going to follow up with a designer and implement the following changes in my next PR. Please let me know if any additional adjustments are needed. Thank you thank you! 😃 

> * [ ]  Please ask designer for a hocus state for this close button 😄
> 
> ![Screenshot 2023-08-30 at 10 05 40 AM](https://user-images.githubusercontent.com/42749717/264419361-b5a3b61e-0ff4-40a9-b903-3449f01f79ad.png)
> 
> * [ ]  For Travel Study, there seems to be a visual regression which cause the normal state of the close button to become black, and the hocus state is taking on the one for homesite as well
> 
> ![Screenshot 2023-08-30 at 10 05 58 AM](https://user-images.githubusercontent.com/42749717/264419328-47fe4967-37c0-4ee4-b768-e285077f39f1.png)
> 
> ![Screenshot 2023-08-30 at 10 08 01 AM](https://user-images.githubusercontent.com/42749717/264419538-b83ed424-9260-4626-b3ba-79d82064d509.png)
> 
> * [ ]  Also, another thing to check with designer - since the masthead of the SAA homesite doesn't quite follow the normal center container (ie, the screen margins are a bit different to accommodate the logo treatment, I'd ask the designer whether to align the content container to this modified container, eg, on the left edge, have the first column in the panel left aligned with the left side of the logo.

2023-09-01 17:07 UTC, merged

2023-09-01 20:20 UTC, yvonnetangsu commented
Looks great - @rebeccahongsf !!

Adding that comment for grid gap as you requested - here's a screenshot - need gaps on both of the grids 👍🏼 😄 
![Screenshot 2023-09-01 at 1 19 17 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/998b5ec5-bf32-49a9-9a90-0639aae246ed)

2023-09-01 20:25 UTC, yvonnetangsu commented
A few more that I just noticed - related to the modal visual regression 😂 Definitely related to the earlier comments, so you might fix these when you fix those ones.

- [ ] Looks like the mobile user menu has some visual regression with the links/buttons
![Screenshot 2023-09-01 at 1 22 24 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/e406652b-b200-4769-bb99-ca2b54d4632d)

- [ ] Looks like the search modal Close X button is black so blending in (mobile and desktop)
![Screenshot 2023-09-01 at 1 22 35 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/7383d2ce-171a-4ded-a200-a4b2b8df330d)

2023-09-01 20:26 UTC, yvonnetangsu commented
I'm not able to logged in as zguan on the preview, if you could - please do a check for the user menu for me too 😄

2023-09-05 19:12 UTC, rebeccahongsf commented
> I'm not able to log in as zguan on the preview, if you could - please do a check for the user menu for me too 😄

Looks like I was missing the MEGAPROFILE_URL in vault! Mind retrying here?
https://megamenu--stanford-alumni.netlify.app/ 

I'll definitely take a look over the user menu as well 😃

2023-09-05 19:28 UTC, yvonnetangsu commented
> > I'm not able to log in as zguan on the preview, if you could - please do a check for the user menu for me too 😄
> 
> Looks like I was missing the MEGAPROFILE_URL in vault! Mind retrying here? https://megamenu--stanford-alumni.netlify.app/
> 
> I'll definitely take a look over the user menu as well 😃

Thank you @rebeccahongsf ! Yes, I can log in now 👏🏼 

Yup, looks like some visual regression in the user menu on the homesite after logging in as well
![Screenshot 2023-09-05 at 12 24 12 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/7b3d7013-2fdc-42d2-8af6-72b2991cdbae)

On the T/S side, it looks good except for the close modal button 😄 (for user menu, search - as mentioned before, and for the Destination page filter modal on mobile)
![Screenshot 2023-09-05 at 12 25 15 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/eae8b938-7fc7-40ab-819f-b5c42f4cc76a)

![Screenshot 2023-09-05 at 12 27 54 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/eaefaf32-a217-4ae4-9422-6fa6a3d4e5b6)

2023-09-05 21:03 UTC, rebeccahongsf commented
Thank you thank you @yvonnetangsu for looking it over again! Looks like my changes to the Modal.styles.ts is causing those issues so I'll fix that up in my mobile pr 🫡

2023-09-05 21:04 UTC, yvonnetangsu commented
Thank you @rebeccahongsf !! 😄 👍🏼