DS-173 | @rebeccahongsf | theme mobile mega menu
SU-SWS/saa_alumni pull request #696
Opened 2023-09-05 22:59 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- theme mobile mega menu to use the same colors as the Giving site

# Review By (Date)
- When possible

# Review Tasks

## Setup tasks and/or behavior to test

1. Navigate to preview
2. Verify that the mobile menu uses the same colors and spacing as Giving
3. Review code

# Associated Issues and/or People
- [DS-173](https://stanford.atlassian.net/browse/DS-173)

2023-09-06 17:06 UTC, yvonnetangsu requested changes
Thank you for the changes, @rebeccahongsf ! We're 98% there 😄 Just a couple things

- [x] This one is a really small one. On mobile only, if you could please make the "drop down" relative positioned, so that when a dropdown is expanded, it doesn't cover the item below

Before:
![Screenshot 2023-09-06 at 9 52 09 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/12d37c05-b158-45a2-8cf1-cef20195b1f5)

After:
![Screenshot 2023-09-06 at 9 52 25 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/bc60af83-1a8b-4b2e-aa7f-f8a9579187de)

- [ ]  This one might need some designer input. On Giving, the card occupies a larger width than the text link columns. On the LG breakpoint, this makes a difference. Currently, in the mega menu preview, it looks like the card expands when there's a longer word in the card and causes overflow. It seems that it could use a larger width on LG.

For example, for the same browser width, the 1st card is skinnier because there are longer words in the 2nd card causing it to overflow 😄 
![Screenshot 2023-09-06 at 9 39 04 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/2af0f8e7-1d36-446c-8a7d-47a41245ffa0)
![Screenshot 2023-09-06 at 9 39 25 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/ebc5ba02-1a31-4d5c-afe8-06fdd786a78e)

I see a few ways we can deal with this - one is for the card to take up a larger width. We could also reduce the padding, and font sizes for the card on LG (and add `su-break-words`). Perhaps a quick check with Bhavika 😄 I would test with the long word "Opportunities".

Let me know if you have any questions - almost there!! Nice job 👏🏼

2023-09-06 23:03 UTC, rebeccahongsf commented
Sounds good and thanks Yvonne! 😃 I went ahead to make the change for the mobile menu positioning and the word break for lg. I'll follow up with Bhavika tomorrow about the card width and word break to see what she recommend.

2023-09-06 23:05 UTC, yvonnetangsu commented
Thank you @rebeccahongsf I'll check back tomorrow 👍🏼 😄

2023-09-11 18:02 UTC, rebeccahongsf commented on src/components/navigation/MegaMenu/megaMenuPanel.js
> +              {fourthCol.length > 0 && (
@yvonnetangsu I've confirmed with Bhavika about making the card span the same widths as Online Giving. 

As part of this update, I changed the card specific columns to be a general fourth columns where the user can either add a card or group of links. 

I figured this would be easiest to just have the start of the fourth column hardcoded (versus trying to calculate the sub-grid's width when there's 4 column of links versus a 3 column of links and card combo).

I'll most likely roll this in today and start some accessibility review but please continue to let me know your thoughts and if any additional adjustments should be made. I can always open up another PR for any other tweaks! Thank you 😄

2023-09-11 19:27 UTC, rebeccahongsf commented on src/components/navigation/MegaMenu/megaMenuLinkGroup.js
> +    <GridCell lg={4} className={styles.menuGroup}>
I removed the link for the group header since it doesn't look like they will be using that functionalty (based on their link(s) spreadsheet) 😃

2023-09-11 19:43 UTC, merged