DS-40 | @rebeccahongsf | Alumni Homesite Mega Menu
SU-SWS/saa_alumni pull request #708
Opened 2023-09-11 21:09 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- Build out Alumni Homesite Mega Menu

# Review By (Date)
- When possible

# Review Tasks

## Setup tasks and/or behavior to test

1. Navigate to https://megamenu--stanford-alumni.netlify.app/
2. Verify that the mega menu matches the [Figma mocks](https://www.figma.com/file/nPKfSbRk5lXIzpDYGpS93G/Mega-Menu?type=design&node-id=12%3A476&mode=design&t=MlK6Ut7WqTPwubU7-1)
3. Review code

# Associated Issues and/or People
- DS-40

2023-09-11 21:10 UTC, rebeccahongsf commented on README.md
> +# [ADAPT SAA Alumni: Mega Menu](https://github.com/SU-SWS/saa_alumni)
@rebeccahongsf revert before merge

2023-09-11 21:10 UTC, rebeccahongsf commented on netlify.toml
> +    secrets = ['secret/data/projects/adapt/saml', 'secret/data/projects/adapt/megamenu']
@rebeccahongsf revert before merge

2023-09-11 22:51 UTC, sherakama commented
Tagging in @ericbakenhus for review and exposure.

2023-09-12 16:58 UTC, yvonnetangsu commented
I like the new adjustment of the card width etc @rebeccahongsf ! Could we replace the su-w-fit class with the su-w-full class so the card always take up the full width of the slot that it's in, eg, before and after.

![Screenshot 2023-09-12 at 9 56 26 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/bdb9ade8-f0d4-4687-81bf-5658f65fb1bc)
![Screenshot 2023-09-12 at 9 57 22 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/51c1212c-4804-4b03-b3fb-c36e59c6d1c4)

2023-09-12 16:59 UTC, yvonnetangsu commented
I'll take another look after a couple meetings this morning 😄 Thank you for the updates!

2023-09-12 20:01 UTC, yvonnetangsu requested changes
@rebeccahongsf Let me know if I'm looking at the latest. I logged in and seeing this in the mobile user menu 😄 The logged out state looks ok though 👍🏼 

![Screenshot 2023-09-12 at 12 59 38 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/de4cae59-1b13-407d-8e03-a1213a523dba)

2023-09-12 20:16 UTC, yvonnetangsu commented
@rebeccahongsf Did another round of visual QA and all looks good to me! 🎉 😄 I really like the new decision to go with the wider width of the 4th column. I have 3 very minor things - please feel free to do later and no need to block this from merging since I know you're also trying to get a SODA review. I'll post them below:

- Could we change the `display` of the links to `inline-block`, and use a line-height of 1.2 to tighter up the space a bit when they're multilined? Before and after:
![Screenshot 2023-09-12 at 12 51 08 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/a052d4a9-7c2d-4bd8-bc9d-cc86d4757772)
![Screenshot 2023-09-12 at 12 50 58 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/7876b8a9-fd67-4d62-b566-9d3821955c70)

- I'm seeing a 1px gap for the cards sometimes (it's a browser glitch thing that I've dealt with previously). One quick fix is to just shift the red part 1px up.
![Screenshot 2023-09-12 at 12 57 34 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/bad41ce6-2cac-487c-8052-ea443b10d0ab)

- Is it possible to change the background color of the main menu modal to all white? When it's black like how it currently is, I found myself trying to click on the black portion to click out of the menu (it gave me the illusion that the black portion is not part of the menu) - before and after:
![Screenshot 2023-09-12 at 12 58 56 PM ](https://github.com/SU-SWS/saa_alumni/assets/42749717/14ce4d27-72fa-49aa-a6d8-445c6ac3f81b)

![Screenshot 2023-09-12 at 12 59 14 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/b2310611-0518-43e0-a29a-b5bad247934f)


I noticed that the search modal "x" button is missing a hocus state - but that was visual regression from before so not related to this PR. I'll take care of that in my Decanter update ticket 👍🏼 😄

2023-09-13 18:12 UTC, rebeccahongsf commented
Thanks @yvonnetangsu! 😃 I added the requested fixes and an accessibility fix (the rest were content authoring related). I think we might let the client review the mega menu preview site. It depends if they want access to review the SB authoring side of things. We'll see during sprint planning today 🤔

2023-09-13 19:37 UTC, ericbakenhus approved these changes
Looks really awesome! 🦖

![ralph-wiggum-simpsons](https://github.com/SU-SWS/saa_alumni/assets/1059679/436b3f54-45c3-4c89-9629-c63eaa63dced)

2023-09-13 19:48 UTC, rebeccahongsf commented
> Looks really awesome! 🦖
> 

Thanks @ericbakenhus!! 😆 Your help is greatly appreciated!

2023-09-13 20:12 UTC, yvonnetangsu commented
> Looks really awesome! 🦖
> 
> ![ralph-wiggum-simpsons](https://user-images.githubusercontent.com/1059679/267758428-436b3f54-45c3-4c89-9629-c63eaa63dced.gif)

Just seeing your presence helps @ericbakenhus 😆 👋🏼

2023-09-13 20:48 UTC, sherakama commented on src/components/components.js
> +  megaMenuLinkGroup: MegaMenuLinkGroup,
@rebeccahongsf Are any of these new storyblok page or component types? Do you need to remove them from the GraphQL query and/or search?

2023-09-13 20:54 UTC, sherakama commented
Ditto to the other comments. The rest of this looks great. Keyboard nav and focus looks good too.

2023-09-13 23:00 UTC, rebeccahongsf commented on src/components/components.js
> +  megaMenuLinkGroup: MegaMenuLinkGroup,
Ooo! Great questions @sherakama 🤔 These are indeed new nestable blok types that are used within the masthead component. Since they are not universal bloks, I don't think we need to exclude them from graphQL query, search, and/or XML sitemap. 

I believe we should be covered with omitting the `masthead` from the GraphQL query here: 
https://github.com/SU-SWS/saa_alumni/blob/dev/gatsby-node.js#L16

Any thoughts or concerns? 👀

2023-09-13 23:08 UTC, sherakama commented on src/components/components.js
> +  megaMenuLinkGroup: MegaMenuLinkGroup,
Ok, that sounds good. As long as they don't show up I am happy.

The last thing is that the build still builds if all of the items are unpublished/deleted

See: https://github.com/SU-SWS/saa_alumni/blob/dev/gatsby-node.js#L362

2023-09-13 23:09 UTC, sherakama approved these changes

2023-09-14 00:02 UTC, rebeccahongsf commented on src/components/components.js
> +  megaMenuLinkGroup: MegaMenuLinkGroup,
Ah yes, another good thing to triple check! 😉 

The build will still build even if the menu link/page is unpublished/deleted. The link will still appear in the menu and users accessing the link will be redirect to the 404 err page in the event that the menu link/page is unpublished/deleted.

2023-09-14 16:25 UTC, sherakama commented on src/components/components.js
> +  megaMenuLinkGroup: MegaMenuLinkGroup,
I wasn't so worried about the destination of the link but that is a good check.

I was more worried about the situation the `createSchemaCustomization` fixes. This is for the situation where we are pulling content using GraphQL but it is unable to infer the field types because all of the content is unpublished or deleted so there is nothing to infer from. This would be for the new blocks `MegaMenu***` and their fields. I understand it will be unlikely for these to be completely unpublished in the long term but what is the go-live strategy with this content? Are you planning to let them build out an unpublished version first? If so, you might want to check what happens when all of the MegaMenu*** blocks are unpublished and you're not using the Storyblok preview token.

2023-09-14 18:04 UTC, rebeccahongsf commented on src/components/components.js
> +  megaMenuLinkGroup: MegaMenuLinkGroup,
> I understand it will be unlikely for these to be completely unpublished in the long term but what is the go-live strategy with this content? Are you planning to let them build out an unpublished version first? 

Yes! As part of our enhancement, SAA has requested that we assemble the mega menu on prod. I will be creating a new masthead (with the `MegaMenu***` blocks) for them to review. Once confirmed, I'll duplicated the swap out the live `MainMenu***` block with the approved `MegaMenu***` block. 

That way we do not need to go into each page to update the Masthead.

> If so, you might want to check what happens when all of the `MegaMenu***` blocks are unpublished and you're not using the Storyblok preview token.

Is the concern around an unpublished Masthead containing the `MegaMenu***` blocks? 

When a Masthead is unpublished, it doesn't display the entire masthead block on the page.
Example: https://megamenu--stanford-alumni.netlify.app/test/rebecca/rehong-masthead/

Is there a way to unpublish specific nested blocks? 🤔

2023-09-14 21:47 UTC, sherakama commented on src/components/components.js
> +  megaMenuLinkGroup: MegaMenuLinkGroup,
I just tested and I think you're all good here.

What I did is 
1. pull your latest code from this branch
2. Change the STORYBLOK_ACCESS_TOKEN to point to the production space
3. Run `npm run build`

The build was successful so you are GTG.

2023-09-15 17:16 UTC, yvonnetangsu commented on src/components/components.js
> +  megaMenuLinkGroup: MegaMenuLinkGroup,
Is this ready to merge into `dev` @rebeccahongsf and @sherakama ? I didn't touch the menu/modal components in my Decanter update PR to avoid ugly merge conflicts, so after this get merged, I can get this into my PR and work on cleaning those up next week 😄

2023-09-18 17:34 UTC, rebeccahongsf commented on src/components/components.js
> +  megaMenuLinkGroup: MegaMenuLinkGroup,
@yvonnetangsu oh yes, this PR is essentially ready! Business is QAing the megamenu preview site but I can always revert the files back after merge and open a new PR if they have any additional requests 😃

I'll get this PR fixed up and merged in this morning

2023-09-18 18:01 UTC, merged