ADAPT-2851 Add canonical url to SEO
SU-SWS/saa_alumni pull request #71
Opened 2021-07-08 22:06 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- Add canonical url to SEO

# Review By (Date)
- July 13

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- [ADAPT-2851](https://stanfordits.atlassian.net/browse/ADAPT-2851)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-07-13 18:03 UTC, sherakama commented on src/components/partials/seo.js
> +  const canonicalUrl = getCanonicalUrl(blok, siteUrl, location);
This is rendering: https://alumni-preview.stanford.eduundefined for pages without the URL set. 

* https://deploy-preview-71--stanford-alumni.netlify.app/test/yvonne/test-basic-page/

2021-07-13 18:04 UTC, sherakama requested changes
Not working as expected yet. Please revise.

2021-07-13 18:43 UTC, yvonnetangsu commented
@rebeccahongsf Thanks for adding the schema to the basic page and dark background page. Please add it to the Story content type too 🙏🏼 😄

2021-07-14 05:34 UTC, sherakama requested changes
This is working well

* https://deploy-preview-71--stanford-alumni.netlify.app/test-with-canonical/
* https://deploy-preview-71--stanford-alumni.netlify.app/test/rebecca/url-test/
* https://deploy-preview-71--stanford-alumni.netlify.app/about/people/departments 
* https://deploy-preview-71--stanford-alumni.netlify.app/sitemap/sitemap-0.xml

Please revise the linting errors and then this is GTG.

2021-07-14 17:55 UTC, yvonnetangsu approved these changes
Approving since @sherakama said this is GTG pending eslint warnings which you have now fixed - thank you!

2021-07-14 23:09 UTC, sherakama approved these changes
GTG

2021-07-14 23:09 UTC, merged