Adapt 2679
SU-SWS/saa_alumni pull request #77
Opened 2021-07-14 13:29 UTC by andrewbaraniuk

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-07-14 16:42 UTC, nplowman requested changes
Overall this is looking good. Just had a couple of suggestions.

2021-07-14 16:42 UTC, nplowman commented on src/components/composite/searchKeywordBanner.js
> +        switch (banner.content[0].component) {
I'd recommending using the `<CreateBloks>` component which handles this dynamically based on the mapping in components.js. That way if they add additional components to the whitelist, we don't need to adjust the code to support them.

2021-07-14 16:42 UTC, nplowman commented on src/components/composite/searchKeywordBanner.js
> +  <StaticQuery
I'd recommend moving the preprocess logic here where you're checking for the keyword matching into a separate function - just a little tidier than having it all in the JSX template. (Probably fine to keep in the same file).

Also wanted to make sure you were aware that there is also a hook for static query that you can use if you prefer that syntax over the component-based version:
https://www.gatsbyjs.com/docs/how-to/querying-data/use-static-query/

(Mostly just a personal preference, but I like it a little better)

2021-07-16 06:58 UTC, sherakama commented on src/components/page-types/searchPage.js
> +import SearchKeywordBanner from "../composite/searchKeywordBanner";
Please move this template into the `search` directory.

2021-07-16 06:58 UTC, sherakama commented on src/components/page-types/searchPage.js
> +import SearchKeywordBanner from "../composite/searchKeywordBanner";
```suggestion
import SearchKeywordBanner from "../search/searchKeywordBanner";
```

2021-07-16 07:16 UTC, sherakama commented on src/components/composite/searchKeywordBanner.js
> +  return created ? created[Math.max(...Object.keys(created))].content : "";
I updated the branch with the code from main and published the two banners in storyblok and now this line is throwing an error in the build. Looks like it isn't finding any content. Can you refactor this please.

2021-07-16 07:16 UTC, sherakama requested changes
When the build was working the placement of the banners and functionality joined with the search was good.

2021-07-16 17:28 UTC, sherakama approved these changes
OK.

2021-07-16 17:28 UTC, merged