Task/HOM-1 update white hero banner gradient
SU-SWS/saa_alumni pull request #815
Opened 2024-03-07 20:01 UTC by shc314

# READY FOR REVIEW

# Summary
- Changes text styles for the white hero banner gradient, to improve readability.

# Review By
- When possible

# Review Tasks

1. Check out this branch
2. Navigate to shirley-test page. Or create a page with a hero banner image with a White gradient, and enter text in the  Superheadline 2, Headline, and Subheadline fields. (Skip Superheadline 1 as the designer said they aren't using that now.)
3. Verify that:

- the font color for text on the white gradient is: #2E2D29
- Superheadline 2 and Subheadline both have text-shadow: rgba(255, 255, 255, .4) 0 0 10px, rgba(255, 255, 255, .6) 0 0 10px;
- Headline has text-shadow: rgba(255, 255, 255, .5) 0 0 12px;

# Associated Issues and/or People
@William-Misiaszek 
https://internal-saa.atlassian.net/browse/HOM-1

2024-03-07 20:06 UTC, shc314 commented on src/utilities/dataSource.js
This file is straight from dev. I made some changes locally but reverted them, and then Prettier wreaked havoc on that file, so I removed it and replaced it with the one on dev.

2024-03-08 17:42 UTC, sherakama commented
@yvonnetangsu would you mind giving this an eyeball? Thanks.

2024-03-08 17:44 UTC, yvonnetangsu commented
> @yvonnetangsu would you mind giving this an eyeball? Thanks.

Sure I'll take a look 😄

2024-03-08 17:47 UTC, yvonnetangsu commented on src/components/composite/hero.styles.js
> +      'su-text-shadow-white': textColor === 'su-black',
@shc314 Wouldn't text color be `su-text-black` instead of `su-black` here? Or is that the value passed in from storyblok? Haven't pulled it down locally - just scanning the code at the moment 😄 When do you need this reviewed by? Ok if I want till later in the afternoon today?

2024-03-08 19:25 UTC, shc314 commented on src/components/composite/hero.styles.js
> +      'su-text-shadow-white': textColor === 'su-black',
Thank you for pointing that out. I wasn't aware of su-text-black, so I used su-black because it's also #2E2D29. I've just pushed the changes. Reviewing it this afternoon is fine.

2024-03-08 19:28 UTC, yvonnetangsu commented on src/components/composite/hero.styles.js
> +      'su-text-shadow-white': textColor === 'su-black',
Hi @shc314 I believe `su-black` isn't a valid TW classname. It could still be rendering black text because it's inherited from the base TW styles (black text). Thanks for the update 😄 
https://tailwindcss.com/docs/text-color

2024-03-12 00:06 UTC, yvonnetangsu requested changes
@shc314 I believe the "Scroll to explore" text would need to be black on the white gradient as well
https://deploy-preview-815--stanford-alumni.netlify.app/shirley-test/
![Screenshot 2024-03-11 at 5 05 38 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/2a5e2f91-dbe5-49a8-9d7b-750b8cedc554)

2024-03-12 00:08 UTC, yvonnetangsu commented
Curious if this is ok for color contrast on mobile 🤔 Seems a bit hard to read even with the shadow. Might be something to ask SODA (office hour for a quick question perhaps?)
![Screenshot 2024-03-11 at 5 07 44 PM](https://github.com/SU-SWS/saa_alumni/assets/42749717/6050f786-f71b-4829-9cd9-84009958df9f)

2024-03-12 00:11 UTC, yvonnetangsu commented
One option is to use su-text-black-true (#000) to push the contrast up a bit further, but even that might not be enough, so I'd suggest talking to SODA, and perhaps test with a few images. It is possible that you might need a more opaque white gradient on mobile since the font size is smaller.

2024-03-12 00:17 UTC, yvonnetangsu commented on src/tailwind/plugins/utilities/text-shadow/text-shadow.js
> +};
Thanks for adding custom TW utilities 👍🏼 😄

2024-03-13 16:29 UTC, shc314 commented on src/tailwind/plugins/utilities/text-shadow/text-shadow.js
> +};
Thank you for your feedback @yvonnetangsu ! Your point about the text color contrast not being high enough on smaller screens is valid. I did try su-text-black-true but depending on the background image, it doesn't always have a contrast ratio of at least 4.5:1. I will bring this up with the designer.

I also realized that I forgot that the white gradient is different when the screen is smaller than xs, so I reinstated the white text for that size and made it black for larger sizes.

I'll let you know when my code is ready for review.

2024-03-15 17:48 UTC, yvonnetangsu commented on src/tailwind/plugins/utilities/text-shadow/text-shadow.js
> +};
Thank you for the updating and thinking about a11y @shc314! Now that we're on it, I suspect we need color contrast adjustments to the other variants also especially on mobile 🤔  You're right that a convo with the design team seems necessary 😄 

![Screenshot 2024-03-15 at 10 46 53 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/87006d24-012a-4490-972f-9ce29dc18ce6)

2024-03-22 19:21 UTC, shc314 commented on src/tailwind/plugins/utilities/text-shadow/text-shadow.js
> +};
@yvonnetangsu My code is ready for review.
I tested the contrast for different background images at different breakpoints using TPGi Colour Contrast Analyser (CCA) and found some where it passes the minimum contrast ratio requirements. The SAA art director has agreed to check the contrast using CCA before using a background image and will only use those that pass.

2024-04-03 17:35 UTC, William-Misiaszek commented on src/tailwind/plugins/utilities/text-shadow/text-shadow.js
> +};
Hello @yvonnetangsu and @shc314 

Is this feature ready for production? We did get confirmation our design team will check contrast ratios with a CCA for the White Gradient. This color option is worth having for them!

When will the white gradient be available in production?

2024-04-03 17:45 UTC, yvonnetangsu commented on src/tailwind/plugins/utilities/text-shadow/text-shadow.js
> +};
@shc314 @William-Misiaszek I'll approve this, but please make sure the design team do pick a photo that will meet contrast ratio - especially on mobile breakpoints. For example, this image on the test page would not work for mobile:
![Screenshot 2024-04-03 at 10 43 39 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/ef3d24df-2a96-4859-8fd8-dd0418f84e4e)

2024-04-03 17:47 UTC, yvonnetangsu commented on src/tailwind/plugins/utilities/text-shadow/text-shadow.js
> +};
@shc314 I understand that you'd like to get this into production as soon as you can, but it is still worth using `su-text-black-true` when you're using the white gradient option - perhaps in another PR. Every little bit helps 😄

2024-04-03 17:50 UTC, yvonnetangsu commented on src/components/composite/hero.js
> +                className={dcnb(
@shc314 This is for future also - it would be nice to keep all the style code in hero.styles.js. We have a mix here, some in the hero.js and some in hero.styles.js. Would be nice to keep everything consistent.

2024-04-03 17:53 UTC, yvonnetangsu approved these changes
Approving but as discussed, please make sure design team selects images that meet contrast requirement for accessibility 😄 Please also consider keeping convention consistent.

2024-04-03 17:59 UTC, yvonnetangsu commented
It looks like @shc314 published the test page with new images. These do look better, but I believe only the one at the bottom  is actually fully compliant 🤔 . Leaving out the superheading also helps a bit since the higher part of the image doesn't have as much of the white gradient color. cc @William-Misiaszek 

![Screenshot 2024-04-03 at 10 56 36 AM](https://github.com/SU-SWS/saa_alumni/assets/42749717/d5903b84-6b4d-4c97-8b46-028a3b1b971a)

2024-04-03 18:02 UTC, yvonnetangsu commented
I don't believe the cypress test has anything to do with this PR so I'm going to merge this into `dev` @sherakama

2024-04-03 18:03 UTC, merged

2024-04-03 18:28 UTC, shc314 commented on src/tailwind/plugins/utilities/text-shadow/text-shadow.js
> +};
Will do.

2024-04-03 18:33 UTC, shc314 commented on src/components/composite/hero.js
> +                className={dcnb(
I didn't move it because it didn't have conditional CSS, but I can put it in hero.styles.js. Should I also put both hero.js and hero.styles.js in their own Hero directory?

2024-04-03 19:01 UTC, yvonnetangsu commented on src/components/composite/hero.js
> +                className={dcnb(
No worries @shc314 ! 😄  in our newer repos, we do put almost every component and their style js file in a separate directory to keep things a bit cleaner. If we have a style js file, we usually put all the TW classes and things into that file whether there is a conditional or not (_usually_ - since there were times when we missed things or when there were other vendors working on things as well).

2024-04-05 21:31 UTC, sherakama commented
> I don't believe the cypress test has anything to do with this PR so I'm going to merge this into `dev` @sherakama

Eric noticed it as well and there is [WIP](https://github.com/SU-SWS/saa_alumni/pull/824).