QR Code 0.1
SU-SWS/saa_alumni pull request #833
Opened 2024-04-10 18:20 UTC by William-Misiaszek

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2024-04-21 17:03 UTC, moisesnarvaez commented
Next ENV variables needs to be defined:
```
ANDROID_PASS_ISSUER_ID=
ANDROID_PASS_PROJECT_ID=
ANDROID_PASS_PRIVATE_KEY_ID=
ANDROID_PASS_PRIVATE_KEY=
ANDROID_PASS_CLIENT_ID=
ANDROID_PASS_CLIENT_EMAIL=
```

VAlues will be provided by @William-Misiaszek

2024-06-18 23:57 UTC, sherakama commented on src/api/stanfordcard/testPass.pkpass
Is this empty file required?

2024-06-19 05:03 UTC, sherakama commented on src/components/wallet/walletPass.js
> +  const deviceParam = new URLSearchParams(window.location.search).get('device');
Unfortunately, the window object here produces a build time error as it is not available. 

Check out this document for more information: https://www.gatsbyjs.com/docs/debugging-html-builds/

Steps to reproduce: 
1. Set your STORYBLOK_ACCESS_TOKEN environment variable to one from [Wills test space](https://app.storyblok.com/#/me/spaces/248824) 
2. Run `npm run build`

2024-06-19 05:05 UTC, sherakama commented on src/components/wallet/walletPass.js
> +  );
If the `iosButtonUrl` const is never being set anywhere else, why is it being put into a state?

2024-06-19 05:07 UTC, sherakama commented on src/components/wallet/walletPass.js
> +    console.log(url.toString());
Please remove console.log debugging statements.

2024-06-19 05:17 UTC, sherakama commented on src/components/wallet/walletPass.js
> +  );
Instead of window.location you can get the URL from [Netlify Environment Variables](https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata) or through the `@reach/router` lib that is built into Gatsby.

2024-06-19 05:21 UTC, sherakama commented on src/components/wallet/walletPass.js
> +      )}
It is possible to be logged in and not have a membership number is it not? Perhaps when there is no membership number there should be an additional check to see if there is a user and then prompt them to join before defaulting to a log in message.

2024-06-19 05:31 UTC, sherakama commented on src/utilities/saacard.pass/background.png
Where are these image resources being used?

2024-06-19 05:37 UTC, sherakama commented on src/utilities/walletPass.js
> +          signerKeyPassphrase: 'test', // This is valid, process.env.PASS_CERTIFICATE_PASSWORD has an invalid value
Let's make sure we change this as we cannot have hardcoded passphrase values in a public repository. Can you make sure to set this to the value in `PASS_CERTIFICATE_PASSWORD`

2024-06-19 05:39 UTC, sherakama commented on src/utilities/walletPass.js
> +    const issuerId = process.env.ANDROID_PASS_ISSUER_ID;
Please send me all of the `ANDROID_` environment variables so I can add them to the vault.

2024-06-19 05:44 UTC, sherakama commented on src/utilities/walletPass.js
> +        'https://www.googleapis.com/robot/v1/metadata/x509/stanford-pass-dev%40oceanic-spider-420801.iam.gserviceaccount.com',
Who manages this service account and all of the other environment variables for this? Say we need to rotate the values quickly because they were publically exposed, who would we contact and how do we get ahold of them? What is the google project that this service account is connected to and what can it do? Is it separated from other SAA accounts?

2024-06-19 05:45 UTC, sherakama commented on src/utilities/walletPass.js
> +          uri: 'https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/logo.png',
Can we move this out of the S3 bucket and into this codebase or into Storyblok?

2024-06-19 05:45 UTC, sherakama commented on src/utilities/walletPass.js
> +          uri: 'https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/background.png',
Can we move this out of the S3 bucket and into this codebase or into Storyblok for this image as well?

2024-06-19 05:47 UTC, sherakama commented on src/utilities/saacard.pass/pass.json
What is this file used for?

2024-06-19 05:53 UTC, sherakama requested changes
Hey @William-Misiaszek and @moisesnarvaez 

I have taken a first pass through on the code and testing for this. I have left a number of questions and comments for you but I'd like to make sure that we can get this working on the development build. Please send me all of the environment variables that are required to get this to work and fix the window reference build error first so that we can get to testing the URLs. 

Could you also provide me with a few test user account names (and logins if we don't have them) so that we can test users that have and don't have membership IDs in order to test all of the different component states?

Thank you.

2024-07-02 14:02 UTC, moisesnarvaez commented on src/utilities/walletPass.js
> +          uri: 'https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/logo.png',
The image should be in a public folder, where can we put it for each environment and how can we specify the URL? (is it better to use an ENV variable?)

2024-07-02 14:02 UTC, moisesnarvaez commented on src/utilities/walletPass.js
> +          uri: 'https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/background.png',
The image should be in a public folder, where can we put it for each environment and how can we specify the URL? (is it better to use an ENV variable?)

2024-07-02 14:02 UTC, moisesnarvaez commented on src/components/wallet/walletPass.js
> +      )}
@willyumfrancis what messages should we use here?

2024-07-03 02:38 UTC, moisesnarvaez commented on src/api/stanfordcard/testPass.pkpass
no, I just removed it

2024-07-03 02:39 UTC, moisesnarvaez commented on src/components/wallet/walletPass.js
> +  const deviceParam = new URLSearchParams(window.location.search).get('device');
Replaced by `getSiteUrl`

2024-07-03 02:40 UTC, moisesnarvaez commented on src/components/wallet/walletPass.js
> +  );
Converted to a simple const, and using `getSiteUrl`

2024-07-03 02:40 UTC, moisesnarvaez commented on src/components/wallet/walletPass.js
> +    console.log(url.toString());
Removed!

2024-07-03 02:41 UTC, moisesnarvaez commented on src/utilities/saacard.pass/background.png
The files in this folder are used for the apple pass generation

2024-07-04 14:31 UTC, moisesnarvaez commented on src/components/wallet/walletPass.js
> +      )}
Cse covered:
![image](https://github.com/SU-SWS/saa_alumni/assets/1587535/93939c96-9c44-4da0-9eb5-ad6f40bc361e)

2024-07-05 00:06 UTC, sherakama commented on src/api/stanfordcard/testPass.pkpass
Ty

2024-07-05 00:07 UTC, sherakama commented on src/components/wallet/walletPass.js
> +  const deviceParam = new URLSearchParams(window.location.search).get('device');
Ty

2024-07-05 00:08 UTC, sherakama commented on src/utilities/walletPass.js
> +          signerKeyPassphrase: 'test', // This is valid, process.env.PASS_CERTIFICATE_PASSWORD has an invalid value
Ty

2024-07-05 00:10 UTC, sherakama commented on src/utilities/walletPass.js
> +    const issuerId = process.env.ANDROID_PASS_ISSUER_ID;
I have them now.

2024-07-05 00:30 UTC, sherakama commented on src/utilities/walletPass.js
> +          uri: 'https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/logo.png',
You can use an env var if you want or create two files(dev/prod versions) and reference the correct file based on the context of the build.

2024-07-05 00:30 UTC, sherakama commented on src/utilities/saacard.pass/pass.json
Thanks.

2024-07-05 23:47 UTC, sherakama commented on src/utilities/walletPass.js
> +        'https://www.googleapis.com/robot/v1/metadata/x509/stanford-pass-dev%40oceanic-spider-420801.iam.gserviceaccount.com',
Thanks @moisesnarvaez 

@willyumfrancis, as these accounts are owned by you I would like you to share the following best practices and helpful information to ensure we protect and best serve Stanford.

**1. Redundancy**
Please add more than just yourself to the accounts/groups/teams that are required so that in the case of you getting picked up to play for the SF Giants there is someone at Stanford who can still access the account. I would recommend a colleague or manager as your backup.

**2. Security**
Ideally, the accounts you have set up are isolated from other projects and the keys that have been created are only scoped with the required permissions and access controls.

**3. Compliance**
Please review any policies or usage documents to ensure that no PII data is saved anywhere on the 3rd party systems and that no additional tracking or monitoring of the users without their consent is happening.

**4. Usage and Cost**
Please review the usage and costs of these services if they have any, including fair use, and ensure that this feature will stay within the expected and acceptable boundaries. Please also account for any rate limits and necessary throttling. 

**5. Renewals**
Please set up renewal reminders for things like certificate expiration and/or key rotation so that we don't get caught by them in the future. 

**6. Service monitoring**
Please subscribe to any newsletters or announcements for changes or updates to the 3rd party systems so that you are informed if something changes that you will need to account for. 

Have a read and review of the above. No need to report back to me on any of this however, reporting and documenting these things with your manager would be welcomed. 

Have a wonderful weekend.

2024-07-12 14:16 UTC, moisesnarvaez commented on src/utilities/walletPass.js
> +          uri: 'https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/logo.png',
@sherakama thanks! Code Updated, URL moved to these ENV variables

```
ANDROID_PASS_LOGO_URL="https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/logo.png"
ANDROID_PASS_IMAGE_URL="https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/background.png"
``

2024-07-14 18:02 UTC, willyumfrancis commented on src/utilities/walletPass.js
> +        'https://www.googleapis.com/robot/v1/metadata/x509/stanford-pass-dev%40oceanic-spider-420801.iam.gserviceaccount.com',
@sherakama,

Thank you for these best practices. We will make sure to have ample documentation so knowledge+access redundancy is present for our Google Pay & Wallet Console. 🙏

2024-07-16 11:24 UTC, moisesnarvaez commented
@sherakama added 2 more ENV variables to show/hide the QR code on each platform:
```
PASS_INCLUDE_QR_CODE="true"
ANDROID_PASS_INCLUDE_QR_CODE="true"
```

2024-07-16 15:23 UTC, sherakama commented
> @sherakama added 2 more ENV variables to show/hide the QR code on each platform:
> 
> ```
> PASS_INCLUDE_QR_CODE="true"
> ANDROID_PASS_INCLUDE_QR_CODE="true"
> ```
> 
> Default values are `false`

@moisesnarvaez which environments would you like the wallet enabled on?

2024-07-16 15:26 UTC, sherakama commented on src/utilities/walletPass.js
> +          uri: 'https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/logo.png',
I've moved the environment variables into vault so they are now there and available to you. Please move the `logo.png` and `background.png` files into this codebase or into Storyblok as I'd like to have all the assets managed in places we already have established.

2024-07-18 02:18 UTC, moisesnarvaez commented
@sherakama  according to @willyumfrancis , it whould be disabled in all environments for now

2024-07-18 02:33 UTC, moisesnarvaez commented
@sherakama, on a different topic, can I use your expertise on this one?

We are building a ruby client to fetch the User profile information based on `MegaProfile.js`

Service (WIP)  https://gist.github.com/moisesnarvaez/192851ad733e4ebe5d838e3983cbe501

By any chance, do you know what the internal process is for getting the permissions/credentials to retrieve the user profile information? (This is for https://stanfordmag.org/ )

2024-07-22 23:02 UTC, sherakama commented
> @sherakama, on a different topic, can I use your expertise on this one?
> 
> We are building a ruby client to fetch the User profile information based on `MegaProfile.js`
> 
> Service (WIP) [gist.github.com/moisesnarvaez/192851ad733e4ebe5d838e3983cbe501](https://gist.github.com/moisesnarvaez/192851ad733e4ebe5d838e3983cbe501)
> 
> By any chance, do you know what the internal process is for getting the permissions/credentials to retrieve the user profile information? (This is for [stanfordmag.org](https://stanfordmag.org/) )

@moisesnarvaez and @willyumfrancis 

API access is granted based on an application so please use the following request form to request new credentials for your Ruby app: https://stanford.service-now.com/alumni_donor_services?id=sc_cat_item&sys_id=f7ad5f8a1b7668d4d78786ecdc4bcb07

If you're building out a client I would also request access to the API documentation as well. They have OAS and RAML files for consumption.

Good luck.

2024-07-22 23:53 UTC, willyumfrancis commented on src/utilities/walletPass.js
> +          uri: 'https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/logo.png',
@moisesnarvaez Following up on this little action item.

2024-07-22 23:54 UTC, willyumfrancis commented
> Hey @William-Misiaszek and @moisesnarvaez
> 
> I have taken a first pass through on the code and testing for this. I have left a number of questions and comments for you but I'd like to make sure that we can get this working on the development build. Please send me all of the environment variables that are required to get this to work and fix the window reference build error first so that we can get to testing the URLs.
> 
> Could you also provide me with a few test user account names (and logins if we don't have them) so that we can test users that have and don't have membership IDs in order to test all of the different component states?
> 
> Thank you.

I am asking our internal team for these two accounts (with and without membership). I have been modifying profileprofile.js in lieu of accounts in localhost.

2024-07-23 20:15 UTC, sherakama commented
> @sherakama How are we looking for a first week of August merge? I will try to get these test accounts to you ASAP.

Thank you for sharing those accounts @willyumfrancis but please refrain from posting any usernames, passwords, keys, certs or anything into this public thread and repository. I have removed them from the prior comment but I request that you have the passwords changed and then notify me when you do. 

I've added a `Remaining tasks` section to the pull request description (top of this page) with the outstanding items before merging.

I'll need new values with Local or Storyblok locations for the following env vars
`ANDROID_PASS_IMAGE_URL`
`ANDROID_PASS_LOGO_URL`

I've also done a little testing and require that this functionality works in the dedicated preview build found at [saa-dw-qa1--saa-wallet.netlify.app/wallet-pass-test](https://saa-dw-qa1--saa-wallet.netlify.app/wallet-pass-test)

I tried out my user (no membership) and the test user test.nine (membership) on both the browser and simulated devices. Along the way I noticed a few bugs, primarily around URLs linking to localhost for the Andriod API and the Apple wallet logo. These will need to be resolved and working before acceptance. 

**1. Anonymous user in browser** - Success
![Screenshot 2024-07-23 at 12 34 56](https://github.com/user-attachments/assets/655b70ae-2c6a-4f1d-b29f-0383758f8422)

**2. Anonymous user as unknown mobile device** - Console Errors
When loading as an anonymous mobile device, the Android API is attempted to be fetched from and fails. 
![Screenshot 2024-07-23 at 12 34 24](https://github.com/user-attachments/assets/fee77b80-55ce-47c6-8398-c50b14e24432)

**3. Anonymous user as Android Device** - Errors
When loading as an anonymous user on an Android device, the fetch to the android API fails.
![Screenshot 2024-07-23 at 12 32 56](https://github.com/user-attachments/assets/7c6d15c4-3b5c-4319-88cb-37560efee9ee)

**4. Test Member as Android Device** - Errors
When loading as logged in member user on an Android device, the android API fails.
![Screenshot 2024-07-23 at 12 31 56](https://github.com/user-attachments/assets/be5a1ac5-df23-4985-ac57-89c4faec8c89)

**5. Test Member as IOS Device** - Errors
When I load the page as a logged in Member on an IOS device I see the apple wallet icon, however, when I click on that icon I am redirected to localhost.
![Screenshot 2024-07-23 at 12 30 27](https://github.com/user-attachments/assets/28e7d5b9-370c-44d6-ad9d-67d9d67b7157)

**6. Test member user in browser** - Success
When I load the page as a logged in test member and toggle the QR code options they load and I am able to scan them with my phone. When I navigate to the URL on the phone I am not automatically sent to login but am shown the message to log in.
![Screenshot 2024-07-23 at 12 35 34](https://github.com/user-attachments/assets/715d1e1c-dc94-4ff7-ae2f-c72d6633270f)

**7. Test member user in browser** - Success
![Screenshot 2024-07-23 at 12 35 27](https://github.com/user-attachments/assets/ba63b9e5-b4cf-42e9-a867-0ff118d505c1)

**8. Test member on IOS device** - Partial Success
I am shown the add to wallet button but clicking on it sends me a localhost url.
![Screenshot 2024-07-23 at 12 30 19](https://github.com/user-attachments/assets/d17a32eb-fb20-477a-a71a-b64ec0a30775)

**9. Logged in Non-Member user in browser** - Success
I am shown the join messaging.
![Screenshot 2024-07-23 at 12 40 29](https://github.com/user-attachments/assets/abbd3ff6-6924-442f-a784-4356143676f4)

cc @moisesnarvaez

2024-07-31 04:03 UTC, moisesnarvaez commented
@sherakama  Thanks for the detailed tests and the response, in the last commit, this was covered:

**Android**
2. Anonymous user as unknown mobile device - Console Errors
3. Anonymous user as Android Device - Errors
4. Test Member as Android Device - Errors

**iOS**
5. Test Member as IOS Device - Errors
8. Test member on IOS device - Partial Success


In addition, these are the values for the ENV vars:
```
ANDROID_PASS_LOGO_URL="https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/logo.png"
ANDROID_PASS_IMAGE_URL="https://project-orion-production.s3.us-east-1.amazonaws.com/wallet/background.png"
```

cc @willyumfrancis

2024-07-31 21:28 UTC, sherakama commented
Thanks for the update @moisesnarvaez, 

I will have a review shortly. 

On the environment variables, sorry for any confusion but I am looking to have those URLs be pointed to Netlify or Storyblok locations and no longer use the project-orion s3 bucket URL. I'd like to have all assets included in this work be from existing project locations. Thank you.

2024-07-31 23:48 UTC, sherakama commented
@moisesnarvaez I have re-reviewed https://saa-dw-qa1--saa-wallet.netlify.app/wallet-pass-test/ 

2. Anonymous user as unknown mobile device - Success
3. Anonymous user as Android Device - console errors trying to connect to localhost:8000
4. Test Member as Android Device - same errors as number 3
5. Test Member as IOS Device - Error when clicking on `add to wallet` image. Links to localhost.

Number 8 has the same issue as number 5.   

Please test on the preview build to confirm your fixes. https://saa-dw-qa1--saa-wallet.netlify.app/wallet-pass-test/ 


Error for #3
```
walletPass.js:29 Refused to connect to 'http://localhost:8000/api/walletpass/android' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

2024-08-01 23:11 UTC, moisesnarvaez commented
@sherakama can you please double check  https://saa-dw-qa1--saa-wallet.netlify.app/wallet-pass-test/ is up to date with the latest changes? In the last commit ([4935794](https://github.com/SU-SWS/saa_alumni/pull/833/commits/4935794f7e3bf043bd1b7c178c5268f79b30ce19)) `getSiteUrl` was replaced by `location.origin`, that should have fixed all the "localhost:8000" issues.

<img width="456" alt="image" src="https://github.com/user-attachments/assets/8d22a1d7-85c1-46ef-9dfe-3ce4f8689dde">
in

2024-08-02 16:36 UTC, sherakama commented
![Screenshot_20240802-091627](https://github.com/user-attachments/assets/cca23cc5-e111-4181-ac8e-4e025387bc3b)
![Screenshot_20240802-091633](https://github.com/user-attachments/assets/1599ec09-1d79-4237-abe0-301721a4f282)
![Screenshot 2024-08-02 at 09 27 24](https://github.com/user-attachments/assets/d4cafdab-5a05-40ab-bf36-fceeb837db12)
![Screenshot 2024-08-02 at 09 28 07](https://github.com/user-attachments/assets/2c571a50-8dfb-422d-8ea3-8dc02628c4d5)

2024-08-02 20:45 UTC, sherakama commented
Ok, @moisesnarvaez 

I have some good news and some bad news.

The good news is that android is working 👍 

The bad news is that ios is not working on Netlify. The reason is that in the function bundling the `saacard.pass` directory is not included. Now, I tried to include it through [manually configuring the `netlify.toml` file](https://www.netlify.com/blog/2021/08/12/how-to-include-files-in-netlify-serverless-functions/#manual-configuration). 

But...
https://answers.netlify.com/t/do-gatsby-functions-work-with-the-included-files-property/44363/1

Unfortunately, the gatbsy functions do not support the included_files option. So you're at a bit of a pivot point here. You're going to either need to refactor the ios gatsby function into a netlify function that supports the manual configuration, or you'll need to change the `model` option into an inline object. Importing or including the individual files should get them bundled.

You should have access to the builds and logs for troubleshooting: https://app.netlify.com/sites/saa-wallet/deploys

And I also changed the build to a 'production like' instance so you will find the test URL is now [saa-wallet.netlify.app](https://saa-wallet.netlify.app/)

2024-08-14 06:05 UTC, moisesnarvaez commented
@sherakama, I refactored the Apple Pass generation code, and now we don't need to read the folder `saacard.pass`, I removed it from this Pull Request, in exchange, we need to define these ENV variables:


```
IOS_PASS_ICON_URL="https://a.storyblok.com/f/248824/29x29/85ec31dabb/icon.png"
IOS_PASS_ICON_2X_URL="https://a.storyblok.com/f/248824/58x58/0eca422913/icon-2x.png"
IOS_PASS_LOGO_URL="https://a.storyblok.com/f/248824/56x84/f6025cdcf6/logo.png"
IOS_PASS_LOGO_2X_URL="https://a.storyblok.com/f/248824/56x84/e0860ac485/logo-2x.png"
IOS_PASS_THUMBNAIL_URL="https://a.storyblok.com/f/248824/135x90/b1db77ba3a/thumbnail.png"
IOS_PASS_THUMBNAIL_2X_URL="https://a.storyblok.com/f/248824/270x180/8852aa6afb/thumbnail-2x.png"
```

PD: The last deployment was a success! https://app.netlify.com/sites/saa-wallet/deploys/66bc47a262cc9b00087215fb

2024-08-14 17:38 UTC, sherakama commented on src/utilities/walletPass.js
> +        passTypeIdentifier: 'pass.com.saacard',
There is an environment variable you've provided me for this and it is set to a different value. 

Can you double-check if `passTypeIdentifier` is correctly set here and if you still need the environment var `PASS_TYPE_IDENTIFIER`.

2024-08-14 17:39 UTC, sherakama commented
@moisesnarvaez 

Thanks for those changes. This is looking good and is super close. I've added the environment vars but when I try to generate an ios card I am seeing an error in the function

Test URL: https://saa-wallet.netlify.app/api/walletpass/ios (after logging in as test user)

See logs at: https://app.netlify.com/sites/saa-wallet/logs/functions/walletpass-ios-js

![Screenshot 2024-08-14 at 10 31 24](https://github.com/user-attachments/assets/0ad53f10-54db-4936-9d41-863154502e73)

Perhaps a related issue? https://github.com/alexandercerutti/passkit-generator/issues/180

2024-08-14 22:18 UTC, moisesnarvaez commented on src/utilities/walletPass.js
> +        passTypeIdentifier: 'pass.com.saacard',
Replaced by:
```
passTypeIdentifier: process.env.PASS_TYPE_IDENTIFIER,
```

But, with the ENV variables I have, I had to use the same value to make it correctly
```
PASS_TYPE_IDENTIFIER="pass.com.saacard"
```

2024-08-14 22:29 UTC, moisesnarvaez commented
@sherakama thanks for your time!

I did a small update regarding the `passTypeIdentifier`, about the other error, this is the value I use in the local ENV:

```
PASS_CERTIFICATE_PASSWORD="test"
```

PD: Previous conversation
![image](https://github.com/user-attachments/assets/0c3d31e6-d159-4a7a-88a2-74c99a1eddb9)

@sherakama, can you try setting the values of `PASS_CERTIFICATE_PASSWORD` to `test` or `QEO9wjuqNO8sZczl3atNSqKb4gDFbeUV`?

2024-08-14 22:29 UTC, moisesnarvaez commented
@willyumfrancis , according to the link Shea found: https://github.com/alexandercerutti/passkit-generator/issues/180#issuecomment-1856171556

Did you generate the certificates using the same values for `your-password` and `secret-passphrase`? If not, this may be the cause of the error.

2024-08-14 22:39 UTC, sherakama commented
Hey @moisesnarvaez,

This is a public repository. Please don't put sensitive values into comments. I removed it from the comments.

If you need to debug these environment vars you can override the values set by vault in Netlify

You should have access to do that on your sandbox site at https://app.netlify.com/sites/saa-wallet/configuration/env#environment-variables

Please go ahead and troubleshoot the values there. 

I request that you generate a strong password for this and perhaps regenerate as the previous value was exposed.

2024-08-14 22:46 UTC, moisesnarvaez commented
@sherakama Sorry about that, I'll keep it in mind for the future.

From the link you sent me, I can only see the following ENV variables:
```
FONTAWESOME_NPM_AUTH_TOKEN=
GATSBY_STORYBLOK_ACCESS_TOKEN=
PRODUCTION_GATSBY_STORYBLOK_ACCESS_TOKEN=
PRODUCTION_STORYBLOK_ACCESS_TOKEN=
STORYBLOK_ACCESS_TOKEN=
```

2024-08-14 22:48 UTC, sherakama commented
> @sherakama Sorry about that, I'll keep it in mind for the future.
> 
> From the link you sent me, I can only see the following ENV variables:
> 
> ```
> FONTAWESOME_NPM_AUTH_TOKEN=
> GATSBY_STORYBLOK_ACCESS_TOKEN=
> PRODUCTION_GATSBY_STORYBLOK_ACCESS_TOKEN=
> PRODUCTION_STORYBLOK_ACCESS_TOKEN=
> STORYBLOK_ACCESS_TOKEN=
> ```

Yep, due to size limitations we have to manage the rest outside of Netlify. The ones you see in Netlify will override the ones pulled from vault so go ahead and put in a new `PASS_CERTIFICATE_PASSWORD` entry in Netlify and it will override whatever is in vault.

Once you've got it squared away, let me know, and I'll go and look at the values you've set and match them to vault.

2024-08-17 03:01 UTC, moisesnarvaez commented
@sherakama, @willyumfrancis generated new keys and password, he will send them to you. I tested it locally and it worked well.

2024-08-20 20:06 UTC, willyumfrancis commented
I sent the new ENV Variable file to Shea in a secure email this morning. Feel free to slack me for any other items!

@moisesnarvaez @sherakama

2024-08-20 20:08 UTC, sherakama commented
@willyumfrancis and @moisesnarvaez 

I've updated the config and deployed the site at https://saa-wallet.netlify.app/wallet-pass-test/

I was successful in my browser (as far as I can tell) and I still need to test on an iOS device.

Can you give it a go?

2024-08-21 00:37 UTC, sherakama approved these changes
Approving. This looks to all be functioning as you'd like it to. 

@willyumfrancis I can move this along to the development environment if you'd like to test and/or create components/content around it there.

And we can now talk about a production date. This code can move into the production environment before the UI is published. I would recommend flushing it out and reviewing with your stakeholder on dev prior to production.

2024-08-26 20:02 UTC, willyumfrancis commented
Awesome work @moisesnarvaez  and Thank You @sherakama!

Yes, let's move this to our Dev Environment so we can work with stakeholders on the Front-End UI, and move the current content into Prod before the UI is finalized.

2024-08-26 22:31 UTC, sherakama commented
@willyumfrancis @moisesnarvaez 

Ok, I will proceed and move this code to dev. I will also shut down the sandbox sites and environments with the exception of the Storyblok environments. I will leave those alone for now.

2024-08-26 22:33 UTC, sherakama commented
I forgot to say,

@moisesnarvaez and @willyumfrancis, Congratulations on getting this work over the line.

2024-08-26 22:34 UTC, merged