ADAPT-3028: Anchor links; IDs for WYSIWYG and posters; update path to input styles in decanter and button updates
SU-SWS/saa_alumni pull request #93
Opened 2021-07-22 00:42 UTC by yvonnetangsu

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-07-22 21:25 UTC, yvonnetangsu commented on tailwind.config.js
> +    require(decanter + "/components/form/input.js")(),
Updated the path to point to the file that was renamed in recent decanter PR

2021-07-22 21:26 UTC, yvonnetangsu commented on package.json
> -    "gatsby-plugin-anchor-links": "^1.2.1",
Removed this as this plugin was flagged by Nathan that it actually broke anchor linking in Giving.

2021-07-23 00:14 UTC, yvonnetangsu commented
FYI @sherakama After this is merge, @rebeccahongsf  has a ticket to verify the anchor links so I'm not doing additional work on anchor links for now other than removing the problematic plugin `gatsby-plugin-anchor-links` that Nathan flagged.

2021-07-23 00:16 UTC, yvonnetangsu commented
@Lyafel Heads up this PR will include some changes to the button, since some of the base styles has been removed in Decanter v7 - I'm adding back some of the styles using TW classes into our component but please double check after this get merged in since there might be some search button component that I missed.

2021-07-23 16:49 UTC, yvonnetangsu commented
@sherakama If you could please take a look at this after your meetings today, that'd be awesome. This pulls in a newer version of Decanter so it would be easier if it gets into main. Thank you 🙏🏼

2021-07-23 17:14 UTC, sherakama commented on tailwind.config.js
> +    require(decanter + "/components/form/input.js")(),
I think you are going to have to add the `form-elements` file as well. The checkboxes on the search page are unusable at the moment. 

![Screen Shot 2021-07-23 at 10 09 01 AM](https://user-images.githubusercontent.com/550602/126817883-688778b3-0fd0-411f-a6e9-c30c8f1c1a86.png)

2021-07-23 17:21 UTC, sherakama commented on src/components/composite/poster.js
> +        id={id}
This prop is coming from user input. Please protect our hardcoded IDs by sanitizing out the anchors we have hardcoded like `#page-title` and ensure uniqueness by wrapping the value in something like `react-id-generator` https://github.com/SU-SWS/ood_online_giving/blob/main/src/components/embed/giveGabForm.js#L12

2021-07-23 17:22 UTC, sherakama commented on src/components/simple/wysiwyg.js
> +        id={id}
This is user input. Please sanitize and protect our hardcoded ids.

2021-07-23 17:23 UTC, sherakama requested changes
Thanks for getting to this upgrade but a few changes are required.

2021-07-23 17:53 UTC, yvonnetangsu commented on tailwind.config.js
> +    require(decanter + "/components/form/input.js")(),
Thanks for that! Updated

2021-07-23 17:55 UTC, yvonnetangsu commented on tailwind.config.js
> +    require(decanter + "/components/form/input.js")(),
Looks like I'll have to add the su- classnames to them as well

2021-07-23 20:02 UTC, yvonnetangsu commented on tailwind.config.js
> +    require(decanter + "/components/form/input.js")(),
This is done. I'll go work on sanitizing the id

2021-07-24 00:51 UTC, yvonnetangsu commented
@sherakama for next week:

A randomly generated 4 digital integer is attached to each page's main content id (eg, #main-content-8462) and page title id,. The skiplink, and hero scroll to link (when there is a hero component on the page) have both been updated to include this random integer generated on each page reload.

Please check a basic page, a dark page, and a story page; and test the skip link and hero banner scroll to link. Story page does not allow for adding a hero component so just check the skip link for story page is enough.

Basic page with hero
https://deploy-preview-93--stanford-alumni.netlify.app/test/yvonne/test-basic-page-interior-hero/

Dark page with hero
https://deploy-preview-93--stanford-alumni.netlify.app/test/yvonne/test-dark-page-with-hero/

Story page
https://deploy-preview-93--stanford-alumni.netlify.app/stories/back-to-the-land/

2021-07-27 05:49 UTC, sherakama commented on src/components/composite/poster.js
> +        id={id}
I'd still like to see this value run through something like the `react-id-generator` to ensure uniqueness. What happens when multiple posters are placed on the same page and the content author adds the same ID?

2021-07-27 05:54 UTC, sherakama commented on src/components/content-types/story/storyPageView.js
> +          id={`main-content-${uniqueIdSuffix}`}
I suppose this works here with the random integers but this is not a solution you would want to use for something like heading anchors or in content anchors as you wouldn't be able to share a URL with the anchor and have it work. Randomizing an anchor's ID limits its use to that specific page load and is not sharable via URL. 

Another approach would have been to run `main-content` and `page-title` through the `react-id-generator` package as that will prevent subsequent use of those ids as long as all IDs go through the generator.

2021-07-27 05:57 UTC, sherakama commented on src/components/simple/wysiwyg.js
> +        id={id}
This still hasn't been sanitized to prevent duplicate ids.

2021-07-27 06:01 UTC, sherakama commented on src/components/page-types/basicPage.js
> +                id={`page-title-${uniqueIdSuffix}`}
Don't we want this to be consistently `page-title` so we don't have to pass props around and guess where to anchor to from the other components?

2021-07-27 06:04 UTC, sherakama requested changes
I think you went a little too far with the random integer suffixes. I think you can revert back to having just the `main-content` and `page-title` IDs hardcoded in our templates as long as you run all content author inputted IDs through a unique ID enforcer. It would be best if the anchors did not randomize so that they can be predictable and bookmarkable.

2021-07-27 06:07 UTC, yvonnetangsu commented on src/components/simple/wysiwyg.js
> +        id={id}
@sherakama I guess I misunderstood your request. What I did was that I protected our 2 hardcoded ids which are placed on main content (for the skiplink) and the other on the page title (for the hero banner link). I added the random numbers at the end so it's unlikely that the users will add the same ids (since they're now randomized) to posters and WYSIWYGs.

I see now that your requests is to use the react-id-generator on the WYSIWYG and poster IDs as well - my only concern is that, there is no easy way for the content author to figure out the ids to link to unless they inspect it in the inspector (seems like they need to be trained) 🤔

2021-07-27 06:08 UTC, yvonnetangsu commented on src/components/content-types/story/storyPageView.js
> +          id={`main-content-${uniqueIdSuffix}`}
Yeah, the randomized one is only for the 2 anchors that we need for skiplinks and hero banner links (they're not used by content authors, just us in the code).

2021-07-27 06:16 UTC, yvonnetangsu commented
> I think you went a little too far with the random integer suffixes. I think you can revert back to having just the `main-content` and `page-title` IDs hardcoded in our templates as long as you run all content author inputted IDs through a unique ID enforcer. It would be best if the anchors did not randomize so that they can be predictable and bookmarkable.

Yeah I think I went a bit far, buuuut to my defense, I only randomized the 2 IDs that won't be used by regular content authors - I don't anticipate anyone would actually link to the `<main>` region (the main-content is for skiplink only) or the page title (which is often visible to screen reader only - the link is for the hero banner arrow link). The reason I added the randomized numbers at the end of these 2 ID is that, now a content author won't be able to add an id to a WYSIWYG or poster that ends up being identical to the page-title or main-content ids, since I suspect they won't be adding a 4 digital number at the end 😂 

I understand your concern with the other ids that the content authors can add, eg, for the posters and WYSIWYG and want to protect them to make them unique. I'll revise to run them through the id generator, but I think we need to add a note to Dena to add that to the training so the content authors will be able to inspect the id that's sanitized and link correctly to that.

2021-07-27 06:24 UTC, yvonnetangsu commented on src/components/page-types/basicPage.js
> +                id={`page-title-${uniqueIdSuffix}`}
Yup, this isn't a prop that's passed in from Storyblok. it's hardcoded page-title plus the random number. I passed it down as a prop from the parent Layout component where it was generated, so the Hero banner link gets the same random number, ie, when someone add a hero banner on the page, it will always link to the page-title (the pair will always have the same random integer at the end).

2021-07-27 07:12 UTC, yvonnetangsu commented
> I think you went a little too far with the random integer suffixes. I think you can revert back to having just the `main-content` and `page-title` IDs hardcoded in our templates as long as you run all content author inputted IDs through a unique ID enforcer. It would be best if the anchors did not randomize so that they can be predictable and bookmarkable.

Ok 😄  I removed the overkill stuff, and went with your approach, ran all content author inputted IDs through the react-id-generators (on the Section, WYSIWYG and Poster components), and went back to just main-content and page-title for those 2 hardcoded ids. Ready for another look - thanks, @sherakama 🙏🏼

2021-07-27 22:18 UTC, yvonnetangsu commented
And @sherakama Here's a page where you could check both the skiplink and the hero scroll to link
https://deploy-preview-93--stanford-alumni.netlify.app/test/yvonne/test-basic-page-interior-hero/

I updated the page with the anchors in the "steps to test" page as well (the page with no hero banner)

2021-07-28 05:36 UTC, sherakama commented on src/components/simple/wysiwyg.js
> +        id={id}
> My only concern is that, there is no easy way for the content author to figure out the ids to link to unless they inspect it in the inspector

I see what you mean. Perhaps nextId is not the right library for this. I am hoping for something that would ensure a unique string but not necessarily append an integer to every instance. For example, I would be looking for a function that I could pass 'test' into and get 'test' back from if it had not been used before. For subsequent inputs of 'test' I would get the added integer. 

This also gets a little nastier with the static build process as that is all one operation, and although having 'test' as an ID one time per page is legal, the fact that the build process is one operation, multiple pages with the name ID will cause the ID to increment. We would have to also nullify the increments on each page context.

I'll create a new ticket for this work.

2021-07-28 05:39 UTC, sherakama commented on src/components/simple/wysiwyg.js
> +        id={id}
https://stanfordits.atlassian.net/browse/ADAPT-3075

2021-07-28 05:40 UTC, sherakama approved these changes
GTG

2021-07-28 05:48 UTC, yvonnetangsu commented on src/components/simple/wysiwyg.js
> +        id={id}
Yeah totally agree with you there -  I'm a little worried about the id incrementing also as it is now not very predictable. Also, if I add a section in between 2 older sections, I'm suspecting that the id #s are going to change which would cause any existing anchor links to not work 😬  Thanks for creating that ticket. Let's investigate in August.

2021-07-28 05:49 UTC, merged