ADAPT-3057 Update Embed component caption to use the CaptionMedia
SU-SWS/saa_alumni pull request #94
Opened 2021-07-23 18:31 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- Update Embed component caption with CaptionMedia

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Review locally at `test/rebecca/embed-caption-test` or Netlify Preview

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- [ADAPT-3057](https://stanfordits.atlassian.net/browse/ADAPT-3057)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-07-23 19:57 UTC, yvonnetangsu commented on src/components/media/embedVideo.js
>            {caption && (
Instead of having CaptionMedia to just replace the caption part, could we pass the React player as children to CaptionMedia? 🙏🏼  That way, you could also use videoWidth for the mediaWidth prop in CaptionMedia.

2021-07-23 19:59 UTC, yvonnetangsu requested changes
If possible, please pass the embed media (including the aspect ratio wrapper) as children into the CaptionMedia component 😄 🙏🏼

2021-07-23 20:57 UTC, sherakama commented on src/components/media/embedVideo.js
> -  textAlign,
Where is this prop going? Did it get removed from SB as well?

2021-07-23 20:58 UTC, sherakama commented on src/components/media/embedVideo.js
> +            // </figcaption>
Please remove commented out code.

2021-07-23 22:46 UTC, rebeccahongsf commented on src/components/media/embedVideo.js
> -  textAlign,
I removed importing textAlign from datasource since there the styling is handled within [captionAlignment within the CaptionMedia](https://github.com/SU-SWS/saa_alumni/blob/main/src/components/media/captionMedia.js#L14-L21).

I didn't remove it as a whole since textAlign is still being used within SimpleImage 🤔  Would it make sense to also refactor the SimpleImage now so that we can remove the textAlign from the datasource as well?

2021-07-23 22:50 UTC, yvonnetangsu commented on src/components/media/embedVideo.js
> -  textAlign,
Hehe @rebeccahongsf I was going to add a ticket for you refactor SimpleImage after you're done with this one. Didn't want to put too much on your plate 😄 

I'm going to add the image processing request into that next ticket too. For this PR, just refactor the embedVideo component is good.

2021-07-23 23:21 UTC, sherakama commented on src/components/media/embedVideo.js
> -  textAlign,
Ok, sounds like a good transition. I won't hold up this PR.

2021-07-23 23:21 UTC, sherakama approved these changes

2021-07-25 19:24 UTC, yvonnetangsu approved these changes
Thank you for the revision, GTG! 🎉

2021-07-25 19:24 UTC, merged