ADAPT-2398: Created Vertical Nav Component and implementation.
SU-SWS/saa_alumni pull request #95
Opened 2021-07-26 06:38 UTC by alexandar87

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - The PR is for Vertical Nav component.

# Review By (Date)
- 28.7

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to /test/left-nav-test 
3. Verify that the submenu is there.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-07-26 16:52 UTC, yvonnetangsu commented on src/components/navigation/verticalNav.js
> +  // TODO: Add breakpoint function to toggle state of navigation based on the screensize
@alexandar87 Instead of using Javascript to check breakpoint and toggle state of nav, please have both version (desktop/mobile) html code rendered, but use TailwindCSS utilities to hide/show at specific breakpoint ranges, so eg, lg:su-hidden on the mobile version.

2021-07-26 16:55 UTC, yvonnetangsu commented on src/tailwind/plugins/theme/colors.js
> +    gray: "#D5D5D4", // Used for top border in Vertical Navigation
No need to add this as a new color, as it already exist as `su-black-20` (black 20%)

2021-07-26 16:58 UTC, yvonnetangsu commented on src/utilities/dataSource.js
> +  gray: "su-border-gray"
I'm not sure you need to add the border color to datasource. It should work without. The datasource are used for when we need to map key-value pairs in Storyblok (single options field) to data objects in our repo. Since border color isn't available as an option in Storyblok, we don't need to add it here.

2021-07-26 17:27 UTC, yvonnetangsu commented on src/components/navigation/verticalNav.js
> +      <button className="sm:su-hidden su-w-full su-text-center su-mt-20" onClick={showNav}
For accessibility, it's actually better for the hamburger button to be inside the `<nav>` element. I think you can get rid of the VerticalNavWrapper and put this directly into VerticalNav.

2021-07-26 17:29 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +  const isActive = window.location.href.indexOf(link.cached_url) > -1 ? true : false;
@sherakama I think we're running into a content author UX issue. When I'm testing, I find it really hard to preview the menu I'm building since it's hiding all the nested levels for the non-current pages. Do you think we could have everything showing when the editors are working in the global components directory in Storyblok?

2021-07-26 17:36 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +        classes={`su-no-underline su-py-2 su-block su-pl-15 su-transition-all hover:su-text-black ${ isActive ? "su-text-black su-border-l-4 su-border-black-90 " : "" }`}
There might be some hover/focus state changes needed. Please see Figma (the section that has all the states is at: https://www.figma.com/file/FeSiATfz2AcP1ziOvL2m02/SWS-Alumni-Homesite?node-id=1392%3A12434

![Screen Shot 2021-07-26 at 10 34 21 AM](https://user-images.githubusercontent.com/42749717/127033505-eb64a797-2510-460c-9d0f-4830d9b02d0f.png)

2021-07-26 17:37 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +        classes={`su-no-underline su-py-2 su-block su-pl-15 su-transition-all hover:su-text-black ${ isActive ? "su-text-black su-border-l-4 su-border-black-90 " : "" }`}
FYI hover and focus states should match (focus state can have additional browser default outlines on top of our hover state styles - no need to remove those)

2021-07-26 17:42 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +      <li className={`${ is_top_level ? "su-border-t su-border-solid su-border-gray su-basefont-21 su-py-12" : "su-py-4" } su-m-0 su-basefont-20`}>
FYI we want this nav to support multiple nesting levels, not just 2 levels with parent and child, ie, this vertical menu might be 3 levels deep or more. In that case, If I'm on the 2nd level (tertiary page menu item), and I want to add another nested level and if I toggle on "is_top_level", is it going to add a border to this 2nd level item? We only want borders in the top level items.

2021-07-26 17:46 UTC, yvonnetangsu commented
@alexandar87 I saw that in your test left nav page, you add the content nav into the "sidebar" content region. There's actually a region in the sidebar created specifically for the content nav/vertical nav. Could you please update it to support adding the vertical nav into this region (above where you currently add it)? Thanks 😄 
![Screen Shot 2021-07-26 at 10 44 42 AM](https://user-images.githubusercontent.com/42749717/127034687-8d1b4895-078e-4e33-90ae-ae466d3ad119.png)

2021-07-26 17:57 UTC, yvonnetangsu commented on src/components/navigation/verticalNav.js
> +  const showNav=()=> setToggleNav(!toggleNav);
I'm going to be a bit picky about the variable names here 😄 
Could you please follow the convention we have for MainNav.js, and tweak the variable names?
```
  const [navOpened, setNavOpened] = useState(false);
  const toggleNav = () => {
    setNavOpened(!navOpened);
  };
```
The reason is that, your current showNav function is really a toggleNav function, since it doesn't always just show the nav, so I'd like them to more accurately reflect what they actually do 🙏🏼  Thanks!

2021-07-26 18:00 UTC, yvonnetangsu commented
@alexandar87 First batch of feedback left. If you could please make those changes and fix the linting (`npm run lint:fix`) issues, I'll do another review. Thanks! 🙏🏼 😃

2021-07-26 18:06 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +  const isActive = window.location.href.indexOf(link.cached_url) > -1 ? true : false;
Another idea is to add a boolean toggle in Storyblok to show all the nested levels, so the content author can toggle that one when they're building the menu. After they finish building all the nested levels, they can then uncheck that toggle and publish, and it will function the way it's supposed to (hide nested levels except the child levels of current page)

2021-07-26 19:36 UTC, yvonnetangsu commented on src/components/navigation/verticalNav.js
> +      {toggleNav && <VerticalNavWrapper className="su-hidden sm:su-block" blok={vertical_nav[0].content} />}
Mobile nav should display for XS to MD breakpoints, so instead of sm:su-block, this would be `lg:su-block`

2021-07-26 19:39 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +const VerticalNavItem = ({blok: {text, link, child_items, is_top_level}}) => {
We use camel case for all our props/Storyblok schemas instead of using underscores. If you could please use camel case that'd be awesome 🙏🏼 . Things like `cached_url` etc is from the Storyblok Link component (this one we can't change) so those are exceptions.

2021-07-27 05:19 UTC, sherakama commented on src/components/navigation/verticalNavItem.js
> +const VerticalNavItem = ({blok: {text, link, child_items, is_top_level}}) => {
There is a linter that runs on PRs that you can also run on your local machine `npm run lint` and additionally `npm run lint:fix`

2021-07-27 05:22 UTC, sherakama commented on src/components/navigation/verticalNavItem.js
> +  const isActive = window.location.href.indexOf(link.cached_url) > -1 ? true : false;
@alexandar87, `window` is not always available to these components. Please protect against possible build errors: https://blog.greenroots.info/gatsby-the-window-is-not-defined-error-what-and-how-to-fix-it

@alexandar87 and @yvonnetangsu, I will create a new ticket for the UX experience. We can progressively enhance this one.

2021-07-27 05:25 UTC, sherakama commented on src/components/navigation/verticalNavItem.js
> +  const isActive = window.location.href.indexOf(link.cached_url) > -1 ? true : false;
https://stanfordits.atlassian.net/browse/ADAPT-3062

2021-07-27 05:28 UTC, sherakama commented on src/components/navigation/verticalNav.js
> +  // TODO: Add breakpoint function to toggle state of navigation based on the screensize
Ditto, 

I would prefer to see the use of CSS to control the hide/show of the functionality at different breakpoints.

2021-07-27 05:29 UTC, sherakama commented on src/components/navigation/verticalNavItem.js
> +      <li className={`${ is_top_level ? "su-border-t su-border-solid su-border-gray su-basefont-21 su-py-12" : "su-py-4" } su-m-0 su-basefont-20`}>
Thank you, Yvonne. Yes, I would prefer that the top-level gets calculated and is not user input.

2021-07-27 05:40 UTC, sherakama requested changes
Feedback left. Builds are breaking when the test page is published due to the window variable in the component.

2021-07-27 06:22 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +  const isActive = window.location.href.indexOf(link.cached_url) > -1 ? true : false;
@sherakama Good catch. I was a bit concerned about the "window" part but thought perhaps it did build - didn't realize the page wasn't published.

2021-07-27 09:33 UTC, alexandar87 commented on src/utilities/dataSource.js
> +  gray: "su-border-gray"
Removed!

2021-07-27 09:33 UTC, alexandar87 commented on src/tailwind/plugins/theme/colors.js
> +    gray: "#D5D5D4", // Used for top border in Vertical Navigation
Removed!

2021-07-27 09:34 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +      <button className="sm:su-hidden su-w-full su-text-center su-mt-20" onClick={showNav}
I moved the nav element in this component instead of the child one.

2021-07-27 09:38 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +  const showNav=()=> setToggleNav(!toggleNav);
Yes, that makes sense, updated!

2021-07-27 09:51 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +      {toggleNav && <VerticalNavWrapper className="su-hidden sm:su-block" blok={vertical_nav[0].content} />}
Done.

2021-07-27 09:51 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +  // TODO: Add breakpoint function to toggle state of navigation based on the screensize
Done.

2021-07-27 10:05 UTC, alexandar87 commented on src/components/navigation/verticalNavItem.js
> +const VerticalNavItem = ({blok: {text, link, child_items, is_top_level}}) => {
Sure, updated!

2021-07-27 10:44 UTC, alexandar87 commented on src/components/navigation/verticalNavItem.js
> +      <li className={`${ is_top_level ? "su-border-t su-border-solid su-border-gray su-basefont-21 su-py-12" : "su-py-4" } su-m-0 su-basefont-20`}>
This is awesome, I was not aware that `children:` even exist, I can't find it in the documentation... ```is_top_level``` is now useless, so I removed it.

2021-07-27 11:02 UTC, alexandar87 commented on src/components/navigation/verticalNavItem.js
> +        classes={`su-no-underline su-py-2 su-block su-pl-15 su-transition-all hover:su-text-black ${ isActive ? "su-text-black su-border-l-4 su-border-black-90 " : "" }`}
@yvonnetangsu can you tell me why are there arrows next to some of the menu items?

2021-07-27 11:59 UTC, alexandar87 commented
> @alexandar87 I saw that in your test left nav page, you add the content nav into the "sidebar" content region. There's actually a region in the sidebar created specifically for the content nav/vertical nav. Could you please update it to support adding the vertical nav into this region (where it says "coming soon.... Pick the section menu..", above where you currently add it)? Thanks 😄
> ![Screen Shot 2021-07-26 at 10 44 42 AM](https://user-images.githubusercontent.com/42749717/127034687-8d1b4895-078e-4e33-90ae-ae466d3ad119.png)

This already works, I'm able to add the Vertical Nav in this region, but for some reason, it is now showing on the page, I don't think it's related to this component, as I tried a few others and none of them are showing up. This might be something related to the page so I`ll take a closer look when I finish with the remaining updates.

2021-07-27 13:32 UTC, alexandar87 commented on src/components/navigation/verticalNavItem.js
> +  const isActive = window.location.href.indexOf(link.cached_url) > -1 ? true : false;
@yvonnetangsu this is done, I added some details in the ticket https://stanfordits.atlassian.net/browse/ADAPT-3062

2021-07-27 16:51 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +  }
Thank you for adding this!

2021-07-27 17:10 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +      )}
It seems to me that this would show the nested level if someone is on the parent page, but need it to work this way:
eg, let's say this is our vertical nav

parent link
- child 1
- child 2
- child 3

So currently, if someone is on parent page, they'll see child 1, 2, and 3 in the nav - that is good. However, we need it to work so that, e.g., if someone is on child 1, they'll need to be able to see the "sibling" pages - child 1, 2, and 3, in the nav also.

2021-07-27 17:40 UTC, yvonnetangsu commented on src/utilities/dataSource.js
> +  gray: "su-border-gray"
Thanks!

2021-07-27 17:42 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +        classes={`su-no-underline su-py-2 su-block su-pl-15 su-transition-all hover:su-text-black ${ isActive ? "su-text-black su-border-l-4 su-border-black-90 " : "" }`}
Hi @alexandar87 Those are external link indicators. So if the content author pick "url" (external link) in Storyblok, it should have that diagonal arrow. There is a boolean prop in SbLinks that enables the external link icon so you could just add that to SbLinks inside the nav.

2021-07-27 17:43 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +      <li className={`${ is_top_level ? "su-border-t su-border-solid su-border-gray su-basefont-21 su-py-12" : "su-py-4" } su-m-0 su-basefont-20`}>
Thank you! Yeah we installed a plugin for TailwindCSS that enables the "children:" variant. Pretty handy 😄

2021-07-27 17:45 UTC, yvonnetangsu commented on src/components/navigation/verticalNavWrapper.js
> +  blok: { items, showNestedLevels },
I like the showNestedLevels toggle - really improves the authoring experience. Thank you!

2021-07-27 17:47 UTC, yvonnetangsu commented on src/components/navigation/verticalNav.js
> +        aria-label="Open section menu"
This aria-label will need to change depending on whether nav is opened also. It should say "Close section menu" when it's opened.

2021-07-27 17:55 UTC, yvonnetangsu commented
@alexandar87 For XS to MD breakpoints, we'd like the nav to show up above the page title like in the below screenshot. I'll check with our designer to see what happens when there is no page title (eg, when hero banner is used instead of page title)
![Screen Shot 2021-07-27 at 10 53 41 AM](https://user-images.githubusercontent.com/42749717/127203882-6b7093ca-bb18-4950-becc-acdbfa081656.png)

2021-07-27 17:59 UTC, yvonnetangsu commented
Please take a look at our "main nav" component, and add the keyboard/click navigation functions for

- Nav should close when user clicks outside of it
- Hitting escape should close the nav or when tabbing away from the nav

There should be code that could just be pretty much copied and pasted here 😄 :
https://github.com/SU-SWS/saa_alumni/blob/main/src/components/navigation/mainNav.js

2021-07-27 18:02 UTC, yvonnetangsu commented
> > @alexandar87 I saw that in your test left nav page, you add the content nav into the "sidebar" content region. There's actually a region in the sidebar created specifically for the content nav/vertical nav. Could you please update it to support adding the vertical nav into this region (where it says "coming soon.... Pick the section menu..", above where you currently add it)? Thanks 😄
> 
> @yvonnetangsu This already works, I'm able to add the Vertical Nav in this region, but for some reason, it is now showing on the page, I don't think it's related to this component, as I tried a few others and none of them are showing up. This might be something related to the page so I`ll take a closer look when I finish with the remaining updates.

Thanks, @alexandar87 if you could please investigate that'd be great.

2021-07-27 18:04 UTC, yvonnetangsu commented
@alexandar87 Heads up we'll be pulling in some changes from Decanter which removes some of the button base styles, e.g., digital red background color and white text. In anticipation of that, if you could add those colors in, that'd be great. Thanks.

2021-07-27 21:08 UTC, nplowman commented on src/components/navigation/verticalNav.js
> +    </nav>
You probably don't need to have two `<VerticalNavWrapper>` elements. You can combine them with some simple ternary logic.

```
  // Define your classes somewhere above the return statement. 
  const openClasses = "lg:su-hidden su-block su-absolute su-shadow-xl su-bg-white su-w-full";
  const closedClasses = "lg-hidden lg:-su-block"
  // Consolidate the two VerticalNavWrappers to just one. 
  <VerticalNavWrapper className={`
    ${navOpened ? openClasses : closedClasses}
  `}
```

2021-07-27 21:11 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +    </nav>
@nplowman with that we will again end up needing to watch for the screen size in order to show the menu when the size goes over MD if it was previously closed.

2021-07-27 21:12 UTC, nplowman commented on src/components/navigation/verticalNavItem.js
> +      )}
![Screen Shot 2021-07-27 at 3 09 32 PM](https://user-images.githubusercontent.com/4481455/127227828-28d40ab9-91a3-4031-89e2-3184c50e99f2.png)

I created a couple of test pages so we could validate this.
It looks like sibling links are displayed correctly for the second level. 

However, I did find that the third level of links does not work as expected - when you select it, the menu is completely collapsed. 
Support for third level and deeper could probably wait unless we have an immediate need for it, but I'll let @sherakama or @yvonnetangsu comment on that.

2021-07-27 21:25 UTC, nplowman commented on src/components/navigation/verticalNav.js
> +    </nav>
Ok - as long as there's a valid reason for having two elements I'm ok leaving it as-is.

2021-07-27 21:28 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +    </nav>
Yep, @yvonnetangsu suggested this approach, you can see it here: https://github.com/SU-SWS/saa_alumni/pull/95/files/7546f44e2964e2b202a59d13f9e846ebd945476f#r676779831

2021-07-27 21:35 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +      )}
@nplowman Yes, I almost forgot to post about that one (the 3d level not showing). Sharing my screenshots below. The 3rd level and deeper links only show if the parent item link is removed:
![Screen Shot 2021-07-27 at 9 45 38 AM](https://user-images.githubusercontent.com/42749717/127230033-391e530a-fd8e-4750-93e0-1992ce592b18.png)
![Screen Shot 2021-07-27 at 9 45 52 AM](https://user-images.githubusercontent.com/42749717/127230042-9fc9d492-a03a-4737-8acf-321e45d66ea0.png)

I'm checking with my team to see if we'll have anything more than 2 levels in the vertical nav. Thanks!

2021-07-27 21:56 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +      )}
@alexandar87 @nplowman Looks like no immediate needs for 3rd level or deeper at the moment, but we'd like to get that working later on if possible. Thanks!

2021-07-28 00:30 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +      )}
Another update: we'll likely request for the 3rd level or deeper support in August. Thanks!

2021-07-28 04:58 UTC, sherakama commented on src/components/navigation/verticalNav.js
> +      aria-label="Vertical Menu"
```suggestion
      aria-label="Section Menu"
```

2021-07-28 05:00 UTC, sherakama commented on src/components/navigation/verticalNav.js
> +        blok={verticalNav[0].content}
We will likely need some protection against a content author creating and publishing an empty nav here or it might trigger a build failure with `.content` being undefined.

2021-07-28 05:01 UTC, sherakama commented on src/components/navigation/verticalNav.js
> +          blok={verticalNav[0].content}
We will likely need some protection against a content author creating and publishing an empty nav here or it might trigger a build failure with `.content` being undefined.

2021-07-28 05:03 UTC, sherakama commented on src/components/navigation/verticalNav.js
> +    </nav>
Yes, we prefer that media queries are done in CSS vs JS.

2021-07-28 05:04 UTC, sherakama commented on src/components/navigation/verticalNavItem.js
> +        classes={`su-no-underline su-border-l-4 su-py-14 su-block su-pl-10 su-transition-all hover:su-text-cardinal-red-xdark hover:su-border-cardinal-red-xdark hover:su-underline focus:su-text-cardi
```suggestion
        classes={`su-no-underline su-border-l-4 su-py-14 su-block su-pl-10 su-transition-all hover:su-text-cardinal-red-xdark hover:su-border-cardinal-red-xdark hocus:su-underline focus:su-text-cardinal-red-xdark focus:su-border-cardinal-red-xdark 
```

2021-07-28 05:13 UTC, sherakama commented on src/components/navigation/verticalNavItem.js
> +      )}
I created a ticket for this: https://stanfordits.atlassian.net/browse/ADAPT-3074

2021-07-28 05:13 UTC, sherakama commented on src/components/navigation/verticalNavWrapper.js
> +  blok: { items, showNestedLevels },
Great! Thanks.

2021-07-28 05:18 UTC, sherakama commented on src/components/navigation/verticalNavWrapper.js
> +  blok: { items, showNestedLevels },
If we want to tie the expansion to only the editor mode you can find a global variable available. `window.storyblok.inEditor` Perhaps you can use that to set the showNestedLevels?

<img width="1791" alt="Screen Shot 2021-07-27 at 10 17 08 PM" src="https://user-images.githubusercontent.com/550602/127267797-e12a1131-d1b5-4889-944e-148afe70d644.png">

2021-07-28 05:27 UTC, yvonnetangsu commented
@alexandar87 One more, the thicker left border on hover/focus/current pages should be 5px (from Figma). Looks like it's 4px at the moment 😄

2021-07-28 05:29 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +        classes={`su-no-underline su-border-l-4 su-py-14 su-block su-pl-10 su-transition-all hover:su-text-cardinal-red-xdark hover:su-border-cardinal-red-xdark hover:su-underline focus:su-text-cardi
^^^ This, and @alexandar87 in general, if the hover and focus states have some of the same styles, instead of writing separate `:hover` and `:focus` classes, you can combine them using `:hocus`.

2021-07-28 12:55 UTC, alexandar87 commented on src/components/navigation/verticalNavItem.js
> +      )}
Ok, so this is not really working as expected. The only reason it worked when @nplowman tested it was because the URL of the page he created was the same as the original page ```/test/left-nav-test/``` and ```test/left-nav-test-second-level``` as soon as I changed it to ```test/left-navigation-test-second-level``` it stopped working. I will have to see what is the best way to get the active trail. The current implementation will work only if the successor pages are going to be nested in the URL like ```first-level/second-level/third-level``` which I doubt. cc @yvonnetangsu

2021-07-28 13:03 UTC, alexandar87 commented on src/components/navigation/verticalNavItem.js
> +        classes={`su-no-underline su-border-l-4 su-py-14 su-block su-pl-10 su-transition-all hover:su-text-cardinal-red-xdark hover:su-border-cardinal-red-xdark hover:su-underline focus:su-text-cardi
It keeps surprising me every day, this is awesome :) Updated.

2021-07-28 14:41 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +        blok={verticalNav[0].content}
Updated.

2021-07-28 14:41 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +          blok={verticalNav[0].content}
Updated.

2021-07-28 15:06 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +        aria-label="Open section menu"
Done.

2021-07-28 16:00 UTC, yvonnetangsu commented
@alexandar87 I checked with Kerri our designer. For page with a hero banner on top of the page H1, please put the collapsed vertical nav at the very top of the page, eg, this page 
https://deploy-preview-95--stanford-alumni.netlify.app/test/yvonne/test-basic-page-interior-hero/

Please style the nav the same way, but it should sit on top of a white background with some padding around it.

2021-07-28 22:15 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +      )}
Yeah I suspect this would be a bit tricky as well - thanks for investigating, @alexandar87

2021-07-29 00:47 UTC, yvonnetangsu commented on src/components/navigation/verticalNavItem.js
> +        classes={`su-no-underline su-border-l-4 su-py-14 su-block su-pl-10 su-transition-all hover:su-text-cardinal-red-xdark hover:su-border-cardinal-red-xdark hover:su-underline focus:su-text-cardi
Thanks, yeah, I'm liking Tailwind a lot myself 😄

2021-07-29 00:49 UTC, yvonnetangsu commented
@alexandar87 I'm out Thursday and Friday. In the meantime, please continue to work on revisions based on our feedback here. Priorities including getting the sibling links to display, and having the collapsed mobile version above the H1 page title or the Hero banner. This is looking good - thank you!

2021-08-02 17:19 UTC, alexandar87 commented on src/components/navigation/verticalNavItem.js
> +      )}
This is fixed.

2021-08-02 17:21 UTC, alexandar87 commented on src/components/navigation/verticalNavWrapper.js
> +  blok: { items, showNestedLevels },
@sherakama looks like this will then disable the ability for an editor to see the menu in final collapsed mode.  Let me know if you still need me to implement this.

CC @yvonnetangsu

2021-08-02 17:23 UTC, alexandar87 commented
> @alexandar87 I'm out Thursday and Friday. In the meantime, please continue to work on revisions based on our feedback here. Priorities including getting the sibling links to display, and having the collapsed mobile version above the H1 page title or the Hero banner. This is looking good - thank you!

Both of these things are fixed. You can now enable this block in the section menu region, and siblings are visible.

2021-08-03 00:48 UTC, yvonnetangsu commented on src/components/partials/basicContentLeftSidebar.js
> +  blok: { content, sidebar, intro, sectionMenu },
Thanks for adding this. Please update the variable and logic in this file to include the `sectionMenu` also:

Currently `hasSidebar` only checks for whether there's content in the "sidebar" region, but we need to check if there is content in either `sidebar` or `sectionMenu`. For the `if` statement, please also add a check for `sectionMenu` so the main content region won't get rendered if nothing is there.

The portion in the file mentioned above (what it is currently)

```
  const hasSidebar = getNumBloks(sidebar) > 0;

  if (!hasIntro && !hasContent && !hasSidebar) {
    return null;
  }
```

2021-08-03 00:50 UTC, yvonnetangsu commented on src/components/navigation/verticalNavWrapper.js
> +      className={`${className} su-list-none su-p-0 children:su-border-t children:su-border-solid children:su-border-black-20 children:children:su-text-21`}
Please import `dcnb` and use it to chain classnames (see basicContentLeftSidebar.js file as an example)

2021-08-03 01:21 UTC, yvonnetangsu commented
@alexandar87 I merged the main branch into this, so there are some button style changes. However, it looks like the section menu button on mobile hasn't been fully styled, so please update the styling and the spacing to match our Figma mocks. it looks like we need to give it a max width as well 🙏🏼 
![Screen Shot 2021-08-02 at 6 19 43 PM](https://user-images.githubusercontent.com/42749717/127942863-cdbea26a-f26d-493d-aef9-9e0ba4389ed0.png)

2021-08-03 01:23 UTC, yvonnetangsu commented on src/components/navigation/verticalNav.js
> +        className="lg:su-hidden su-w-full su-flex su-justify-between su-font-semibold su-items-center su-mt-20"
```suggestion
        className="su-group lg:su-hidden su-w-full su-flex su-justify-between su-font-semibold su-items-center su-mt-20"
```
To style the svg icon on button hover/focus, we need to assign the focusable element a `su-group` class. Otherwise the `group-hocus:` variant won't work in the icon. Please add other TW classes as needed to style this button.

2021-08-03 01:25 UTC, yvonnetangsu commented on src/components/navigation/verticalNav.js
> +      su-relative su-mx-20 su-my-20`}
We don't need the margins for desktop version.

2021-08-03 01:29 UTC, yvonnetangsu commented
> Please take a look at our "main nav" component, and add the keyboard/click navigation functions for
> 
> * Nav should close when user clicks outside of it
> * Hitting escape should close the nav or when tabbing away from the nav
> 
> There should be code that could just be pretty much copied and pasted here 😄 :
> https://github.com/SU-SWS/saa_alumni/blob/main/src/components/navigation/mainNav.js

@alexandar87 Please work on adding support for these click/keyboard events - see above link for copypasta code.

2021-08-03 01:35 UTC, yvonnetangsu commented on src/components/navigation/verticalNavWrapper.js
> +  blok: { items, showNestedLevels },
I'm ok with the way it currently work, since that would allow for a more accurate final preview, but I'll let Shea make the final call.

2021-08-03 01:37 UTC, yvonnetangsu commented on src/components/page-types/basicPage.js
> +            className="lg:su-hidden su-block su-my-30"
I'm not sure you need the su-my-30 here since the vertical nav has margin already in its component file

2021-08-03 06:09 UTC, yvonnetangsu commented on src/components/navigation/verticalNavWrapper.js
> +          }
Thanks! This looks to be working properly for me. The 2nd level siblings are showing up.

2021-08-03 06:19 UTC, yvonnetangsu commented on src/components/navigation/verticalNavWrapper.js
> +    <ul
Please add `aria-hidden` attribute to the `ul` element depending on whether it's expanded

2021-08-03 06:23 UTC, yvonnetangsu commented
Getting really close, @alexandar87 Please revise base on comments, then I think we can merge this and you could start another branch for the deeper level nav work. Thanks!

2021-08-03 11:05 UTC, alexandar87 commented on src/components/navigation/verticalNavItem.js
> +        classes={`su-no-underline su-py-2 su-block su-pl-15 su-transition-all hover:su-text-black ${ isActive ? "su-text-black su-border-l-4 su-border-black-90 " : "" }`}
Ok done.

2021-08-03 11:10 UTC, alexandar87 commented on src/components/partials/basicContentLeftSidebar.js
> +  blok: { content, sidebar, intro, sectionMenu },
Done.

2021-08-03 11:14 UTC, alexandar87 commented on src/components/navigation/verticalNavWrapper.js
> +      className={`${className} su-list-none su-p-0 children:su-border-t children:su-border-solid children:su-border-black-20 children:children:su-text-21`}
Thanks, done.

2021-08-03 11:55 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +        className="lg:su-hidden su-w-full su-flex su-justify-between su-font-semibold su-items-center su-mt-20"
Hmm, it actually works fine without it, I added the remaining classes to make it as per design.

2021-08-03 12:01 UTC, alexandar87 commented on src/components/navigation/verticalNav.js
> +      su-relative su-mx-20 su-my-20`}
Removed.

2021-08-03 12:30 UTC, alexandar87 commented on src/components/page-types/basicPage.js
> +            className="lg:su-hidden su-block su-my-30"
Ok removed it from the component file as it's getting passed from here.

2021-08-03 13:15 UTC, alexandar87 commented on src/components/navigation/verticalNavWrapper.js
> +    <ul
Not sure how to do this, as we are printing two menus, one for mobile and another for desktop, and if I apply this rule, the desktop one will always have aria-hidden...

2021-08-03 23:57 UTC, yvonnetangsu commented on src/components/navigation/verticalNavWrapper.js
> +    <ul
I pushed up some code that should work. Only the mobile one would have the aria-hidden attribute. The desktop one doesn't have an aria attributes, but we can rely on whether it's hidden to hide/show it from the screen reader.

2021-08-04 00:26 UTC, yvonnetangsu commented on src/components/navigation/verticalNav.js
> +        className="lg:su-hidden su-w-full su-flex su-justify-between su-font-semibold su-items-center su-mt-20"
Thanks for the styling changes. I ended up adding the su-group class anyway, there was a subtle delay between the hovering and color change without it (I think it default to currentColor which is inherited from the parent link styles, when relying on that it usually causes the slight delay in color change).

2021-08-04 00:27 UTC, yvonnetangsu commented on src/components/partials/basicContentLeftSidebar.js
> +  blok: { content, sidebar, intro, sectionMenu },
Thanks!

2021-08-04 08:06 UTC, yvonnetangsu commented
![Screen Shot 2021-08-04 at 1 05 25 AM](https://user-images.githubusercontent.com/42749717/128145445-6b5302a7-9940-40f1-bfea-92eb4d4e251a.png)
Looks like this ^^^ can still cause a build error

2021-08-05 20:03 UTC, yvonnetangsu commented
@sherakama I replaced part of @alexandar87 's code using our CreateStories component, that resolved the build error when a vertical nav is added but not selected. I think this is ready for your final look.

2021-08-06 16:51 UTC, sherakama approved these changes
Thanks for the work.

2021-08-06 16:52 UTC, merged