Adapt 2670
SU-SWS/saa_alumni pull request #99
Opened 2021-07-27 16:15 UTC by Lyafel

# Summary
- Search results page mobile theming

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to /search
3. Verify mobile theming

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-07-27 19:11 UTC, nplowman commented
@Lyafel Let me know if you need any help with the merge conflicts. They are probably related to the changes I made for the Media search results.

2021-07-27 23:33 UTC, sherakama commented
@Lyafel please resolve the linting errors and the merge conflicts. We can ignore the codeclimate complaints.

2021-07-27 23:57 UTC, sherakama commented on src/components/search/searchFacet.js
> +                href="https://decanter.stanford.edu"
Not sure we want this prop here.

2021-07-27 23:59 UTC, sherakama commented on src/components/search/searchFacet.js
> +            <div className="su-flex su-justify-between su-px-[17px] su-pt-[18px] su-pb-[27px] su-pt-18 su-bg-foggy-light su-border-t su-border-black-20">
Duplicate `su-pt-` classes.

2021-07-28 00:00 UTC, yvonnetangsu commented on src/components/search/searchFacet.js
> +        </div>
@Lyafel I think we need this whole thing here to be a button, instead of having just the down chevron being clickable. So the whole rectangle box with the text "filter results" and the icon should be one big button 🙏🏼

2021-07-28 00:01 UTC, yvonnetangsu commented on src/components/search/searchFacet.js
> +              </svg>
We have the react hero icons package installed so you could just import individual icons instead of using the plain SVG markup here. Or, we also have a heroicon.js component under /simple that you could use as well.

2021-07-28 00:02 UTC, sherakama requested changes
This is looking really great. Thanks @Lyafel. A few minor comments and revisions requested but this works and looks fine to me. @yvonnetangsu your turn.

2021-07-28 00:05 UTC, yvonnetangsu commented
Please double check the width/height of this button. Looks like in inspector it's not a circle 😄 
![Screen Shot 2021-07-27 at 5 03 41 PM](https://user-images.githubusercontent.com/42749717/127242844-24fe2cd8-a1d4-48fa-b45d-d12846e9f6e4.png)

2021-07-28 00:10 UTC, yvonnetangsu commented
@Lyafel  Please take a look at our "main nav" component, and add the keyboard/click navigation functions for

- Nav should close when user clicks outside of it
- Hitting escape should close the nav or when tabbing away from the nav

There should be code that could just be pretty much copied and pasted here 😄 :
https://github.com/SU-SWS/saa_alumni/blob/main/src/components/navigation/mainNav.js

2021-07-28 00:25 UTC, yvonnetangsu commented
@Lyafel 
I'm just going with the Figma design. Looks like when the filter menu is opened, it should say "Filters" instead of "Filter results" in the bar/button.

Also, please double check the font sizes. Going with Figma, looks like filter labels should be 16px; "Clear all", "View results" , "Close", and the "Filter by" heading should be 18px; "Filter"/"Filter results" should be 21px.

"Close" text should be regular font instead of semibold.

Please also make the "Filter by" text a heading (can use Heading component) - that should make it more accessible 🙏🏼  Thank you!

![Screen Shot 2021-07-27 at 5 18 40 PM](https://user-images.githubusercontent.com/42749717/127243860-48687327-35d9-40d8-a747-d429fc63b570.png)

2021-07-28 00:27 UTC, yvonnetangsu submitted a review, later dismissed
Agree with @sherakama that this is looking great. Left some comments - please revise. There might be some other minor details later but I think we can do a final batch of fixups at the end. Thank you, @Lyafel !

2021-07-28 06:21 UTC, yvonnetangsu commented
Please check pagination - looks like on mobile (eg, I tested on iPhone X simulator on Chrome), they're overflowing the "centered container" (width defined by the `su-cc` CSS class).
![Screen Shot 2021-07-27 at 11 18 50 PM](https://user-images.githubusercontent.com/42749717/127273784-5f9fa61e-9103-461d-ac4b-8dec70ce21eb.png)

2021-07-28 06:26 UTC, yvonnetangsu commented
@Lyafel Please also merge the main branch into this branch, since there are some button changes from Decanter that might require adding some TW classes to get the right styling/color for the toggle buttons.

2021-08-02 17:30 UTC, yvonnetangsu commented on src/components/search/searchResults.js
> +                className="su-text-16 lg:su-text-base"
I believe we have different font sizes for mobile/desktop. Please double check Figma for font sizes and line heights.

2021-08-02 20:21 UTC, yvonnetangsu commented on src/components/search/searchResults.js
> +                className="su-text-16 lg:su-text-base"
FYI - We have different font size related TW classes from Decanter. Please see this list of available font size utilities :)
https://github.com/SU-SWS/decanter/blob/v7/src/plugins/theme/fontSize.js

2021-08-03 05:40 UTC, yvonnetangsu commented
@Lyafel The positioning of the chevron and "Close X" look a bit off to me, also, please double check the border/text color (I think the text should be su-text-digital-red-xlight). The whole button will need some hover/focus state also - checking with Kerri at the moment 😃 
![Screen Shot 2021-08-02 at 10 34 15 PM](https://user-images.githubusercontent.com/42749717/127963711-a1cbb348-515d-4753-abc7-816397267964.png)
![Screen Shot 2021-08-02 at 10 34 20 PM](https://user-images.githubusercontent.com/42749717/127963717-ca8eb51d-f1d5-42f6-93fc-3bcfb688f894.png)

2021-08-06 18:18 UTC, yvonnetangsu commented
@Lyafel I have a meeting with @kerri-augenstein this afternoon so I'll look at the mobile theme with her, and provide consolidated feedback after. Thank you for your patience 🙏🏼

2021-08-06 23:57 UTC, yvonnetangsu commented
> @Lyafel The positioning of the chevron and "Close X" look a bit off to me, also, please double check the border/text color (I think the text should be `su-text-digital-red-xlight` and border color is `su-black-30`). The whole button will need some hover/focus state also - checking with Kerri at the moment 😃
> ![Screen Shot 2021-08-02 at 10 34 15 PM](https://user-images.githubusercontent.com/42749717/127963711-a1cbb348-515d-4753-abc7-816397267964.png)
> ![Screen Shot 2021-08-02 at 10 34 20 PM](https://user-images.githubusercontent.com/42749717/127963717-ca8eb51d-f1d5-42f6-93fc-3bcfb688f894.png)

![Screen Shot 2021-08-06 at 1 42 51 PM](https://user-images.githubusercontent.com/42749717/128580882-a1c0c4f4-a548-4631-b9c9-15d9f0d2cfde.png)
The text in the button between its close/expanded state should be swapped, ie, "Filter Results" when it's collapsed, and "Filters" when it's expanded.

@Lyafel If you could please fix the quoted issue, and the above item I just added above, we can merge what we have in this PR, and I'm in the process of creating new mobile search theming tickets. cc @sherakama

2021-08-09 15:50 UTC, Lyafel commented
@yvonnetangsu ready

2021-08-09 18:40 UTC, sherakama commented
Adding @mattanglin to review.

2021-08-10 23:54 UTC, sherakama commented
@Lyafel please resolve the linting issues and the merge conflict and we can merge.

2021-08-11 19:02 UTC, mattanglin commented on src/components/search/searchPager.js
> +            </li>
Codeclimate is complaining about duplicate code for the next/prev links. We _could extract it out into a component_, but that seems unnecessary here?

@sherakama What's the standard course of action here? Can me just mark as "Won't Fix" in codeclimate?

2021-08-11 20:39 UTC, sherakama commented on src/components/search/searchPager.js
> +            </li>
This is up to the developer on the review. You could ask for the refactor if it really does make sense but if the refactor does not provide enough value, mark it as "Won't fix" in codeclimate and carry on.

2021-08-11 23:44 UTC, mattanglin approved these changes

2021-08-11 23:51 UTC, sherakama approved these changes
GTG

2021-08-11 23:52 UTC, merged